IRMA MATRIX SDK: iris::dist500::DebugData Class Reference
iris::dist500::DebugData Class Reference
Encapsulates debug data.
#include <DebugData.h>
Public Member Functions
DebugData (unsigned long pictureNumber, unsigned long long timestamp, int dataSource, unsigned char status, int dataSize, void *data)
Constructor.
DebugData ()
No-arg constructor (needed for Qt signalling)
DebugData (const DebugData &other)
Copy constructor.
void enableAutoFree (void)
Enables deallocation of data pointer in destructor.
void * getData (void)
Returns the data.
int getDataSize (void)
Returns the data size.
int getDataSource (void)
Returns the data source ID.
unsigned char getStatus (void)
Returns the data status.
DebugData * makeDeepCopy (void) const
Creates a deep copy of the current instance.
~DebugData ()
Destructor.
Public Member Functions inherited from iris::dist500::PictureBoundData
unsigned long getPictureNumber (void)
Returns the picture number.
unsigned char getSensorNo (void) const
unsigned long long getTimestamp (void)
Returns the timestamp.
PictureBoundData (unsigned long pictureNumber, unsigned long long timestamp)
Constructor.
void setPictureNumber (unsigned long pictureNumber)
Changes the picture number.
void setSensorNo (const unsigned char no)
void setTimestamp (unsigned long long timestamp)
Changes the timestamp.
Protected Attributes
bool autoFreeData
Controls if data pointer is free'd in destructor.
void * data
Holds the debug data.
unsigned int dataSize
Holds the size of debug data in bytes.
int dataSource
Holds the data source ID.
unsigned char status
Holds the debug data status.
Protected Attributes inherited from iris::dist500::PictureBoundData
unsigned long pictureNumber
Holds the picture number (created by sensor)
unsigned char sensorNo
unsigned long long timestamp
Holds the timestamp (created by sensor)
Detailed Description
Encapsulates debug data.
Constructor & Destructor Documentation
iris::dist500::DebugData::DebugData (unsigned long pictureNumber, unsigned long long timestamp, int dataSource, unsigned char status, int dataSize, void * data)
Constructor.
Parameters
pictureNumber
timestamp
dataSource
status
dataSize
data
iris::dist500::DebugData::DebugData (const DebugData & other)
Copy constructor.
Parameters
other Source object
Member Function Documentation
void * iris::dist500::DebugData::getData (void)
Returns the data.
Returns
Pointer to data
References data.
Referenced by iris::uff::UffRecorder::processNewDebugData().
int iris::dist500::DebugData::getDataSize (void)
Returns the data size.
Returns
Data size in bytes
References dataSize.
Referenced by iris::uff::UffRecorder::processNewDebugData().
int iris::dist500::DebugData::getDataSource (void)
Returns the data source ID.
Returns
Data source ID
References dataSource.
Referenced by iris::uff::UffRecorder::processNewDebugData().
unsigned char iris::dist500::DebugData::getStatus (void)
Returns the data status.
Returns
Data status
References status.
Referenced by iris::uff::UffRecorder::processNewDebugData().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/DebugData.h
SensorAPI/implementation/iris/dist500/DebugData.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !