IRMA MATRIX SDK: iris::dist500::CounterController Class Reference
iris::dist500::CounterController Class Reference
This class represents the counting modules' functionality within the DIST500 sensor.
#include <CounterController.h>
Public Types
typedef std::list< iris::uip::category > CategoryList
List of count categories.
typedef std::set< iris::uip::category_type > CategoryTypeSet
Set of count category types.
typedef std::list< iris::uip::category_counts > CountList
List of count results (per category)
typedef std::list< iris::uip::functionAreaStatus > FunctionAreaStatusList
List of function area statuses.
typedef std::list< iris::uip::sensorStatusNotification > SensorStatusNotificationList
List of sensor status notifications.
typedef std::set< iris::uip::sensor_status > SensorStatusSet
Set of sensor statuses.
Public Types inherited from iris::dist500::Dist500Base
typedef std::set< unsigned short > IdSet
typedef std::list< iris::uip::messageTypeDef > MessageTypeDefinitionList
typedef std::map< unsigned short, std::string > ParameterGroups
typedef std::map< unsigned short, ParameterInfo > ParameterInfos
typedef void(* TRANSFER_CONFIGURATION_CALLBACK) (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback for sensor configuration transfers.
Public Types inherited from iris::dist500::Source< CountResult * >
typedef Sink< CountResult * > SinkType
Typedef for matching Sink instances.
Public Member Functions
SENSOR_RESULT checkCategoryDefinitionAcceptance (const iris::uip::category &categoryDefinition, bool &accepted)
Checks whether the given count category is acceptable.
CounterController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT getCountCategories (unsigned short functionArea, CategoryList &categoryList)
Retrieves the supported count categories.
SENSOR_RESULT getCountResults (unsigned short functionArea, iris::uip::counter_type counterType, bool resetFlag, unsigned char categoryId, CountList &countList)
Retrieves the count results.
SENSOR_RESULT getFunctionAreaStatuses (FunctionAreaStatusList &statusList)
Retrieves the function area status(es)
SENSOR_RESULT getKnownCategoryTypes (CategoryTypeSet &typeSet)
Retrieves the known count category types.
SENSOR_RESULT getSensorStatuses (SensorStatusSet &statusSet)
Retrieves the sensor status(es)
SENSOR_RESULT resetCounts (const unsigned short functionArea, iris::uip::counter_type counterType)
Requests reset of the boarding/alighting counters.
SENSOR_RESULT resetSensorStatuses (const SensorStatusSet &statusSet, SensorStatusNotificationList &statusNotificationList)
Resets the sensor status(es) List of sensor status notifications informs about actual changes of sensor status(es)
SENSOR_RESULT setCountResults (unsigned short functionArea, iris::uip::counter_type counterType, bool countingFinished, const CountList &countList)
Sets the count results (for debugging purposes)
SENSOR_RESULT startCounting (void)
Starts counting.
SENSOR_RESULT stopCounting (void)
Stops counting.
Public Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _legacyGetDeviceInfo (unsigned short group, unsigned short param, char *buffer)
Retrieves a device feature.
SENSOR_RESULT activateConfiguration (void)
activates a configuration that is already in RAM
SENSOR_RESULT captureDevice (char *application)
Captures the sensor: Marks the device as captured, which can be queried by getCaptureState.
SENSOR_RESULT checkSupportForMessage (const unsigned char command, const unsigned char version, const unsigned char subCommand, bool &isSupported)
checkSupportForMessage Checks if the sensor can respond to the specified message.
SENSOR_RESULT describeParameter (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info, const bool includeName=false)
describeParameter Returns ParameterInfo for the specified parameter which contains the type and value range.
SENSOR_RESULT determineTimeoutParameters (void)
Measures the timeout params (offset and factor) by doing some comnmunication tests.
Dist500Base (iris::drivers::Sensor &sensor)
Constructor.
UipMessage * doSendAndGetApplReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * doSendAndGetReply (int level, UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack or application level message and receives one or more replies.
UipMessage * doSendAndGetServiceReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a service level message and receives one or more replies.
UipMessage * doSendAndGetStackReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT echoTest (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Performs an echo test (pings the sensor)
SENSOR_RESULT getCaptureState (char *applicationBuffer, int maxLen)
Returns the capture state.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, unsigned short &len, bool stackLevel=false)
Reads a configuration parameter.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, bool stackLevel=false)
Reads a configuration parameter from RAM of the sensor (not from flash).
virtual void getConnectionName (char *buffer)
Returns a description for the connection.
virtual void getLocalConnectionName (char *buffer)
Returns an identifier string for local connection (eg IP:port); Currently returns a fixed dummy string.
virtual void getName (char *nameBuffer, int maxLen)
Returns a description for the sensor (ConnectionName + @ + UipAddress)
SENSOR_RESULT getParameterGroupIds (IdSet &groupIds)
Retrieves a set of existing group ids.
SENSOR_RESULT getParameterGroups (ParameterGroups &groups)
Retrieves a map (ParameterGroups) of group ids to group name.
SENSOR_RESULT getParameterIds (const unsigned short groupId, IdSet &paramIds)
SENSOR_RESULT getParameterInfos (const unsigned short groupId, ParameterInfos &infos, const bool includeNames=false)
SENSOR_RESULT getParameterName (const unsigned short groupId, const unsigned short paramId, std::string &paramName)
getParameterName Returns only the name of the specified parameter
iris::drivers::Sensor & getSensor (void)
Returns the associated Sensor instance (from Driver)
unsigned char getUipAddress (void)
Returns the UIP address (integer between 1-255).
SENSOR_RESULT getWorkingMode (iris::uip::working_mode &mode)
Retrieves the sensor working mode (iris::uip::working_mode).
SENSOR_RESULT listAllSupportedMessages (MessageTypeDefinitionList &buffer)
listAllSupportedMessages lists all messages the sensor can respond to.
SENSOR_RESULT lockImmanentData (void)
lockImmanentData
SENSOR_RESULT pingNeighbour (const unsigned char neighbourAddress, const unsigned short payloadLen, const unsigned short repetitions, const unsigned short timeoutMs, unsigned short &successCount, unsigned short &averageTimeMs)
Asks a sensor to ping one of its neighbours (same FA) for a given number of repetitions.
SENSOR_RESULT pingSensor (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Pings a sensor.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT releaseDevice (void)
Releases ("uncaptures") the sensor.
void resetTimeoutParameters (void)
Resets the timeout params to the default values (offset 0, factor 1.0)
SENSOR_RESULT restoreConfigurationFromFlash (void)
Copies the configuration from flash memory to RAM.
SENSOR_RESULT saveConfigurationToFlash (void)
Copies the configuration from RAM to flash memory.
UipMessage * sendAndGetApplReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * sendAndGetServiceReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
UipMessage * sendAndGetStackReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT sendUipCommand (char type, unsigned char version, char command, unsigned short payloadLen, char *payload, unsigned int timeoutMs, char &replyType, unsigned char &replyVersion, char &replyCommand, unsigned short &replyPayloadLen, char *replyPayloadBuffer)
Sends a "free" UIP command to the sensor and waits for the reply.
SENSOR_RESULT setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel=false)
Sets a configuration parameter in the sensor's RAM (not in the flash).
SENSOR_RESULT setConfigurationParameterIfKnown (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool &paramWasUnknown, bool stackLevel=false)
Like setConfigurationParameter but only if that parameter is known.
void setUipAddress (unsigned char)
setUipAddress Sets a new UIP address for communication with this sensor.
void setUipTimeout (const int timeoutMs)
Sets timeout used for UIP send and get reply methods (whereafter usually a retry is performed).
SENSOR_RESULT setWorkingMode (const iris::uip::working_mode mode)
Sets the sensor working mode.
SENSOR_RESULT unlockImmanentData (void)
unlockImmanentData
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
virtual ~Dist500Base ()
Destructor.
Public Member Functions inherited from iris::dist500::CountResultSource
void pushCountResultToSinks (CountResult *result, unsigned long index, unsigned long indexCount)
Propagates a new CountResult to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< CountResult * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Static Public Member Functions
static bool broadcastStartCounting (void)
static bool broadcastStopCounting (void)
Static Public Member Functions inherited from iris::dist500::Dist500Base
static void disableAutomaticRetries (void)
disables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
static void enableAutomaticRetries (void)
enables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
Static Protected Member Functions
static void handleSpontaneousCountMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for C 6.0.
Static Protected Member Functions inherited from iris::dist500::Dist500Base
static void handleSpontaneousWorkingModeMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for U 2.0.
Additional Inherited Members
Protected Types inherited from iris::dist500::Dist500Base
typedef std::map< unsigned short, ParameterInfo > GroupParameterInfos
typedef std::map< unsigned short, ParameterValue > GroupParameterValues
typedef std::set< int > NoRetryMessageHashSet
typedef std::bitset< 1024 > ReceptionFlags
Protected Types inherited from iris::dist500::Source< CountResult * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos, ReceptionFlags &receivedParameters, iris::uip::ushort &expectedCount)
SENSOR_RESULT _legacyReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _optimizedReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings, const bool sendEmptyIfDefault, ReceptionFlags &receivedParams, iris::uip::ushort &expectedCount)
This is internally used in optimized sensor configuration readouts.
SENSOR_RESULT _setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel, bool ignoreUnknownParamErrors, bool &paramWasUnknown)
SENSOR_RESULT _writeConfiguration (iris::configuration::Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
bool automaticRetriesSupported (UipMessage *message)
Checks if automatic retries are currently supported for the specified message.
SENSOR_RESULT describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos)
describeAllGroupParametersWithoutNames Gets descriptions (GroupParameterInfos) of parameters within the specified configuration group.
SENSOR_RESULT describeParameterWithoutName (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info)
describeParameterWithoutName Gets type and value range information for the specified parameter.
SENSOR_RESULT getGroupName (const unsigned short groupId, std::string &groupName)
getGroupName Gets the name of the specified configuration group.
float getTimeoutFactor (void) const
Returns the timeout factor.
unsigned long getTimeoutOffset (void) const
Returns the timeout offset.
void initializeNoRetryMessageHashSet (void)
These are the messages that are not automatically repeated in case no reply arrives.
SENSOR_RESULT readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings=true, const bool sendEmptyIfDefault=true)
Used for sensor configuration readout, returns a map with parameter values for the specified configuration group.
void registerNoRetryMessage (unsigned char type, unsigned char version, unsigned char command)
Makes the specified message not be automatically resent if no replay arrives.
SENSOR_RESULT requestKeyPuzzle (unsigned short &puzzleLen, unsigned char *puzzleBuffer)
SENSOR_RESULT unlockImmanentData (const unsigned short keyLen, const unsigned char *key)
unlockImmanentData
Protected Member Functions inherited from iris::dist500::Source< CountResult * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (CountResult * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Attributes inherited from iris::dist500::Dist500Base
SpontaneousHandlers handlers
Handler manger for spontaeous UIP messages (sub-command *)
NoRetryMessageHashSet noRetryMessageHashSet
iris::drivers::Sensor & sensor
Reference to associatee driver's Sensor object.
float timeoutFactor
Factor to applied to standard timeouts.
unsigned long timeoutOffset
Constant offset to be applied to standard timeouts.
unsigned char uipAddress
UIP address of sensor.
int uipTimeout
Timeout in ms used for UIP send and get reply methods.
Protected Attributes inherited from iris::dist500::Source< CountResult * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Static Protected Attributes inherited from iris::dist500::Dist500Base
static bool automaticRetriesDisabled = false
Detailed Description
This class represents the counting modules' functionality within the DIST500 sensor.
Constructor & Destructor Documentation
iris::dist500::CounterController::CounterController (iris::drivers::Sensor & sensor)
Constructor.
Parameters
sensor reference from driver framework
References iris::dist500::Dist500Base::handlers, handleSpontaneousCountMessage(), and iris::dist500::Dist500Base::SpontaneousHandlers::registerHandler().
Member Function Documentation
SENSOR_RESULT iris::dist500::CounterController::checkCategoryDefinitionAcceptance (const iris::uip::category & categoryDefinition, bool & accepted)
Checks whether the given count category is acceptable.
The sensor may reject categories due to value range infractions or licensing issues.
Parameters
categoryDefinition Const reference to count category
accepted Acceptance flag (true if category is acceptable, false otherwise)
Returns
Operation result
References iris::uip::flag_not_set, iris::uip::flag_set, iris::uip::UipMessage::getPayloadLen(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::getCountCategories (unsigned short functionArea, CategoryList & categoryList)
Retrieves the supported count categories.
Parameters
functionArea Function area number
categoryList Reference to list of count categories receiving the data
Returns
Operation result
Note
some counting categories are under licensing
See also
getKnownCategoryTypes
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::getCountResults (unsigned short functionArea, iris::uip::counter_type counterType, bool resetFlag, unsigned char categoryId, CountList & countList)
Retrieves the count results.
Parameters
functionArea Function area number
counterType Counter type
resetFlag true resets the data after retrieval, false remains them untouched
categoryId Category ID
countList Reference to CountList receiving the data
Returns
Operation result
See also
setCountResults
resetCounts
References iris::uip::flag_not_set, iris::uip::flag_set, iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::getFunctionAreaStatuses (FunctionAreaStatusList & statusList)
Retrieves the function area status(es)
Parameters
statusList Reference to list of function area statuses receiving the data
Returns
Operation result
Note
some statuses are dependent on licensing
See also
getSensorStatuses
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::getKnownCategoryTypes (CategoryTypeSet & typeSet)
Retrieves the known count category types.
Parameters
typeSet Reference to set of count category types receiving the data
Returns
Operation result
See also
getCountCategories
References iris::uip::UipMessage::getPayloadLen(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::getSensorStatuses (SensorStatusSet & statusSet)
Retrieves the sensor status(es)
Parameters
statusSet Output set that receives sensor statuses (__sensor_status).
Returns
Operation result
See also
resetSensorStatuses
__sensor_status
getFunctionAreaStatuses
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
void iris::dist500::CounterController::handleSpontaneousCountMessage (Dist500Base * base, UipMessage * message) static protected
Callback function for spontaneous messages (sub-command *), here only for C 6.0.
Parameters
base Dist500Base instance (surrogate for this pointer)
message Spontaneously received message
References iris::uip::_category_counts::alighting, iris::uip::_category_counts::boarding, iris::uip::_category_counts::categoryId, iris::dist500::CountResultSource::pushCountResultToSinks(), and iris::uip::single_event.
Referenced by CounterController().
SENSOR_RESULT iris::dist500::CounterController::resetCounts (const unsigned short functionArea, iris::uip::counter_type counterType)
Requests reset of the boarding/alighting counters.
Parameters
functionArea Function area number
counterType Counter type
Returns
Operation result
See also
getCountResults
setCountResults
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::resetSensorStatuses (const SensorStatusSet & statusSet, SensorStatusNotificationList & statusNotificationList)
Resets the sensor status(es) List of sensor status notifications informs about actual changes of sensor status(es)
Parameters
statusSet Const reference to set of sensor statuses (SensorStatusSet)
statusNotificationList Reference to list of sensor status notifications (SensorStatusNotificationList)
Returns
Operation result
Note
this request is not repeated automatically after a timeout because of the risk of status changes in between not getting detected
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::uip::_sensorStatusNotification::status, iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::setCountResults (unsigned short functionArea, iris::uip::counter_type counterType, bool countingFinished, const CountList & countList)
Sets the count results (for debugging purposes)
Parameters
functionArea Function area number
counterType Counter type
countingFinished Flag indicating whether the counting-finished flag is to be set along with the counts (true set flag, false don't set flag)
countList Reference to CountList containing the data
Returns
Operation result
See also
getCountResults
resetCounts
References iris::uip::flag_not_set, iris::uip::flag_set, iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::startCounting (void)
Starts counting.
Returns
Operation result
See also
stopCounting
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::CounterController::stopCounting (void)
Stops counting.
Returns
Operation result
See also
startCounting
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/CounterController.h
SensorAPI/implementation/iris/dist500/CounterController.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !