IRMA MATRIX SDK: iris::dist500::DoorState Class Reference
iris::dist500::DoorState Class Reference
Encapsulates a door state as a class.
#include <DoorState.h>
Public Member Functions
DoorState (unsigned long pictureNumber, unsigned long long timestamp, unsigned short door, unsigned short functionArea, unsigned char left, unsigned char right)
Constructor.
DoorState ()
No-arg constructor (needed for Qt signalling)
unsigned short getDoor (void) const
Returns the door number.
unsigned short getFunctionArea (void) const
Returns the function area.
unsigned char getLeft (void) const
Returns the left wing's opening percentage.
unsigned char getRight (void) const
Returns the right wing's opening percentage.
void setDoor (unsigned short doorNum)
setDoor
void setFunctionArea (unsigned short fa)
setFunctionArea
void setLeft (unsigned char state)
setLeft
void setRight (unsigned char state)
setRight
Public Member Functions inherited from iris::dist500::PictureBoundData
unsigned long getPictureNumber (void)
Returns the picture number.
unsigned char getSensorNo (void) const
unsigned long long getTimestamp (void)
Returns the timestamp.
PictureBoundData (unsigned long pictureNumber, unsigned long long timestamp)
Constructor.
void setPictureNumber (unsigned long pictureNumber)
Changes the picture number.
void setSensorNo (const unsigned char no)
void setTimestamp (unsigned long long timestamp)
Changes the timestamp.
Protected Attributes
unsigned short door
Holds the door number.
unsigned short functionArea
Holds the function area.
unsigned char left
Holds the left wing's opening percentage.
unsigned char right
Holds the right wing's opening percentage.
Protected Attributes inherited from iris::dist500::PictureBoundData
unsigned long pictureNumber
Holds the picture number (created by sensor)
unsigned char sensorNo
unsigned long long timestamp
Holds the timestamp (created by sensor)
Detailed Description
Encapsulates a door state as a class.
See also
DoorController::getDoorState
Constructor & Destructor Documentation
iris::dist500::DoorState::DoorState (unsigned long pictureNumber, unsigned long long timestamp, unsigned short door, unsigned short functionArea, unsigned char left, unsigned char right)
Constructor.
Parameters
pictureNumber
timestamp
door
functionArea
left
right
Member Function Documentation
unsigned short iris::dist500::DoorState::getDoor (void) const
Returns the door number.
Returns
Door number
References door.
Referenced by iris::uff::UffRecorder::processNewDoorState(), and iris::uff::UffDecoder::repushData().
unsigned short iris::dist500::DoorState::getFunctionArea (void) const
Returns the function area.
Returns
Function area
References functionArea.
Referenced by iris::uff::UffDecoder::repushData().
unsigned char iris::dist500::DoorState::getLeft (void) const
Returns the left wing's opening percentage.
Returns
Left wing's opening percentage
References left.
Referenced by iris::uff::UffRecorder::processNewDoorState(), and iris::uff::UffDecoder::repushData().
unsigned char iris::dist500::DoorState::getRight (void) const
Returns the right wing's opening percentage.
Returns
Right wing's opening percentage
References right.
Referenced by iris::uff::UffRecorder::processNewDoorState(), and iris::uff::UffDecoder::repushData().
void iris::dist500::DoorState::setDoor (unsigned short doorNum)
setDoor
Parameters
doorNum
See also
SensorInfo::getDoorNumber
References door.
Referenced by iris::uff::UffDecoder::repushData().
void iris::dist500::DoorState::setFunctionArea (unsigned short fa)
setFunctionArea
Parameters
fa
See also
SensorInfo::getFunctionArea
References functionArea.
Referenced by iris::uff::UffDecoder::repushData().
void iris::dist500::DoorState::setLeft (unsigned char state)
setLeft
Parameters
state
References left.
Referenced by iris::uff::UffDecoder::repushData().
void iris::dist500::DoorState::setRight (unsigned char state)
setRight
Parameters
state
References right.
Referenced by iris::uff::UffDecoder::repushData().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/DoorState.h
SensorAPI/implementation/iris/dist500/DoorState.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !