IRMA MATRIX SDK: iris::dist500::Dist500 Class Reference
iris::dist500::Dist500 Class Reference
Represents a DIST500 sensor.
#include <Dist500.h>
Classes
class PictureAcquisitionGuard
This class controls automatic enabling/disabling of picture actuisition during certain operations (ie firmware updates).
Public Types
typedef std::set< iris::uip::firmware_feature_type > FirmwareFeatureSet
typedef std::list< unsigned long > RegisterList
typedef std::map< unsigned long, unsigned long > RegisterValueMap
Public Types inherited from iris::dist500::InstallationModeController
typedef std::list< DataSourceInfo > DataSourceInfoList
typedef std::list< DataSourceSelector > DataSourceSelectorList
typedef std::set< iris::uip::ushort > InstallationModeRegisterSet
enum InstallationModeType {
Full16, Distance16, Amplitude16, Full8,
Distance8, Amplitude8
}
Installation mode type, refers to image format that is streamed.
enum NotificationFlags { NotifyOnChange = 1, NotifyAtTimeIntervals = 2, NotifyAlways = 4, NotifyImmediately = 8 }
typedef void(* PROGRESS_CALLBACK) (void *userData, long pictureNumber, long maxPics, unsigned long long elapsedTime, unsigned long long maxTime)
Callback for installation mode progress.
typedef void(* STATUS_CALLBACK) (void *userData, bool running)
Callback for installation mode status.
Public Types inherited from iris::dist500::Dist500Base
typedef std::set< unsigned short > IdSet
typedef std::list< iris::uip::messageTypeDef > MessageTypeDefinitionList
typedef std::map< unsigned short, std::string > ParameterGroups
typedef std::map< unsigned short, ParameterInfo > ParameterInfos
typedef void(* TRANSFER_CONFIGURATION_CALLBACK) (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback for sensor configuration transfers.
Public Types inherited from iris::dist500::Source< Picture * >
typedef Sink< Picture * > SinkType
Typedef for matching Sink instances.
Public Types inherited from iris::dist500::Source< RegisterValues * >
typedef Sink< RegisterValues * > SinkType
Typedef for matching Sink instances.
Public Types inherited from iris::dist500::Source< DebugData * >
typedef Sink< DebugData * > SinkType
Typedef for matching Sink instances.
Public Types inherited from iris::dist500::FpgaController
enum FpgaRegister {
CommandRegister, StatusRegister, ModeRegister, FirmwareRegister,
ThresholdLowRegister, ThresholdHighRegister, SaturationLowRegister, SaturationHighRegister,
DistanceOffsetRegister, ExposureTimeRegister, MaxTemperatureRegister, CurrentTemperatureRegister,
StatusBitSelectionRegister, PicturePeriodRegister, IlluminationControlRegister, DebugModeRegister = 31
}
FPGA register number definitions.
Public Types inherited from iris::dist500::FirmwareController
enum CONTAINER_PARAMETER_RESULT {
CONTAINER_WRONG_PARAMETER_VALUE, CONTAINER_UNKNOWN_PARAMETER, CONTAINER_UNKNOWN_SENSOR_PARAMETER, CONTAINER_PARAMETER_NOT_WRITE,
CONTAINER_PARAMETER_WRONG_UPDATE_STATE
}
Container paramter update result codes.
enum CONTAINER_UPDATE_RESULT {
CONTAINER_UPDATE_PASSED = 0, CONTAINER_UPDATE_FAILED, CONTAINER_OPEN_FILE_FAILED, CONTAINER_SET_WORKING_MODE_FAILED,
CONTAINER_GROUP_INCOMPLETE, CONTAINER_APPLICATION_UPDATE_FAILED, CONTAINER_APPLICATION_VERIFY_FAILED, CONTAINER_COMMUNICATION_UPDATE_FAILED,
CONTAINER_COMMUNICATION_VERIFY_FAILED, CONTAINER_FPGA_UPDATE_FAILED, CONTAINER_FIRST_FPGA_UPDATE_FAILED, CONTAINER_SECOND_FPGA_UPDATE_FAILED,
CONTAINER_FIRST_FPGA_VERIFY_FAILED, CONTAINER_SECOND_FPGA_VERIFY_FAILED, CONTAINER_RESTART_FAILED, CONTAINER_READ_CONFIGURATION_FAILED,
CONTAINER_CHANGE_CONFIGURATION_FAILED, CONTAINER_GET_UPDATE_PARAMETER_FAILED, CONTAINER_WRITE_CONFIG_FAILED, CONTAINER_SAVE_CONFIG_FAILED,
UNSUPPORTED_CONTAINER_FILE, CONTAINER_READ_FPGA_IMAGE_FAILED, CONTAINER_FPGA_IMAGE_MISMATCH, CONTAINER_RESTORE_CONFIGURATION_FROM_FLASH_FAILED,
CONTAINER_GET_PARAMETER_FAILED
}
Container file update result codes.
typedef iris::dist500::Dist500List Dist500List
Dist500List.
typedef std::list< FirmwareController * > FirmwareControllerList
Typedef for a list of FirmwareController instances.
enum FirmwareFitHardwareResult {
FIRWARE_CHECK_PASSED, FIRWARE_CHECK_FAILED, NO_VALID_FILE_EXTENSION, CANNOT_OPEN_CONTAINER,
NO_APPLICATION_FOUND, CANNOT_DECODE_HEXFILE, HEXFILE_ADDRESS_RANGE_FAULTY, ALLOC_MEMORY_FAILED,
NO_IRIS_AUTHENTICATION, NO_LDR_FILE_FOUND, CANNOT_READ_FIRMWARE_VERSION, CHECK_MESSAGE_SUPPORT_FAILED,
GET_REVISION_CODE_FAILED, UNKNOWN_REVISION_CODE, FIRMWARE_NOT_MATCH_TO_HARDWARE
}
Result of the query if the firmware matches the Hardware.
typedef std::map< iris::dist500::Dist500 *, FirmwareFitHardwareResult > FirmwareFitHardwareResultMap
Maps sensor instances to firmware fit hardware result.
typedef std::list< SensorFirmware > FirmwareSkippedList
typedef unsigned char MacAddress[6]
Type for a MAC address (6 octets)
typedef struct iris::dist500::FirmwareController::_ParameterUpdateInformation ParameterUpdateInformation
Typedef for a parameter update result.
typedef std::list< ParameterUpdateInformation > ParameterUpdateInformationList
enum SensorFirmware { APPLICATION_FIRMWARE, COMMUNICATION_FIRMWARE, FPGA1_FIRMWARE, FPGA2_FIRMWARE }
Firmware information for skip list.
typedef struct iris::dist500::FirmwareController::_UpdateInformation UpdateInformation
Typedef for a container update information.
typedef std::map< iris::dist500::Dist500 *, UpdateInformation > UpdateResultMap
Maps sensor instances to container update information.
Public Types inherited from iris::dist500::CounterController
typedef std::list< iris::uip::category > CategoryList
List of count categories.
typedef std::set< iris::uip::category_type > CategoryTypeSet
Set of count category types.
typedef std::list< iris::uip::category_counts > CountList
List of count results (per category)
typedef std::list< iris::uip::functionAreaStatus > FunctionAreaStatusList
List of function area statuses.
typedef std::list< iris::uip::sensorStatusNotification > SensorStatusNotificationList
List of sensor status notifications.
typedef std::set< iris::uip::sensor_status > SensorStatusSet
Set of sensor statuses.
Public Types inherited from iris::dist500::Source< CountResult * >
typedef Sink< CountResult * > SinkType
Typedef for matching Sink instances.
Public Types inherited from iris::dist500::DoorController
enum ManualHallSensorStatus { ForcedOff = 0, ForcedOn = 1, Neutral = 2, __FirstUnusedManualHallSensorStatus }
Public Types inherited from iris::dist500::Source< DoorState * >
typedef Sink< DoorState * > SinkType
Typedef for matching Sink instances.
Public Types inherited from iris::dist500::Source< HallSensorState * >
typedef Sink< HallSensorState * > SinkType
Typedef for matching Sink instances.
Public Member Functions
SENSOR_RESULT disableExposureControl ()
Switches the automatic exposure controll off.
Dist500 (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT enableExposureControl (void)
Switches the automatic exposure control on.
SENSOR_RESULT getDspRegisters (const RegisterList &registerList, RegisterValueMap &registerValueMap)
Gets a list with DSP registers useful for introspection.
SENSOR_RESULT getFirmwareFeatures (FirmwareFeatureSet &featureSet)
Returns a set of supported firmware features.
SENSOR_RESULT getSensorRevisionCode (unsigned short &revisionCode)
Returns the sensor revision code.
SENSOR_RESULT getStatusLedMode (iris::uip::status_led_work_mode &mode)
Returns the status LED mode.
SENSOR_RESULT isPictureAcquisitionRunning (bool &running)
Checks if picture acquisition is running.
SENSOR_RESULT resetCommunicationTestCounter (void)
Used with sendCommunicationTestMessage to reset the counter in the sensor.
SENSOR_RESULT resetDsp (void)
Orders the sensor to restart which takes a couple of seconds to become fully operational.
SENSOR_RESULT sendCommunicationTestMessage (const unsigned long number, unsigned long &expectedNumber, const unsigned short testDataLen, const char *const payload)
Sends a test message with a number which is expected to be returned in the reply payload; number can be reset with resetCommunicationTestCounter.
SENSOR_RESULT setStatusLedMode (const iris::uip::status_led_work_mode mode)
Sets the status LED mode (on, off or blinking behaviour).
SENSOR_RESULT startPictureAcquisision (void)
Starts the picture acquisition.
SENSOR_RESULT stopPictureAcquisision (void)
Stops the picture acquisition.
virtual ~Dist500 ()
Destructor.
Public Member Functions inherited from iris::dist500::InstallationModeController
SENSOR_RESULT disableInstallationMode (void)
Terminates a running installation mode.
void disableInstallationModeRetrigger (void)
SENSOR_RESULT disableTestrideMode (void)
Disables "Testride mode".
SENSOR_RESULT enableInstallationMode (InstallationModeType type, void *userData, STATUS_CALLBACK statusCallback, PROGRESS_CALLBACK progressCallback, unsigned int maxPictures, unsigned long long maxTime)
Starts the installation mode.
void enableInstallationModeRetrigger (void)
SENSOR_RESULT enableTestrideMode (void)
Enables "Testride mode", Testride is an internal iris tool.
InstallationModeController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT listDebugDataSources (DataSourceInfoList &sources)
SENSOR_RESULT selectDebugDataSources (const DataSourceSelectorList &requestedSources)
SENSOR_RESULT selectDebugDataSources (const DataSourceSelectorList &requestesSources, DataSourceSelectorList &knownSources)
bool setInstallationModeRegisterSet (const InstallationModeRegisterSet &regs)
SENSOR_RESULT singleShot (unsigned long &pictureNumber, unsigned long long &timestamp, unsigned short *buffer)
bool waitForInstallationModeEnd (int timeoutMs)
Waits for termination of installation mode.
virtual ~InstallationModeController ()
Destructor.
Public Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _legacyGetDeviceInfo (unsigned short group, unsigned short param, char *buffer)
Retrieves a device feature.
SENSOR_RESULT activateConfiguration (void)
activates a configuration that is already in RAM
SENSOR_RESULT captureDevice (char *application)
Captures the sensor: Marks the device as captured, which can be queried by getCaptureState.
SENSOR_RESULT checkSupportForMessage (const unsigned char command, const unsigned char version, const unsigned char subCommand, bool &isSupported)
checkSupportForMessage Checks if the sensor can respond to the specified message.
SENSOR_RESULT describeParameter (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info, const bool includeName=false)
describeParameter Returns ParameterInfo for the specified parameter which contains the type and value range.
SENSOR_RESULT determineTimeoutParameters (void)
Measures the timeout params (offset and factor) by doing some comnmunication tests.
Dist500Base (iris::drivers::Sensor &sensor)
Constructor.
UipMessage * doSendAndGetApplReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * doSendAndGetReply (int level, UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack or application level message and receives one or more replies.
UipMessage * doSendAndGetServiceReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a service level message and receives one or more replies.
UipMessage * doSendAndGetStackReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT echoTest (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Performs an echo test (pings the sensor)
SENSOR_RESULT getCaptureState (char *applicationBuffer, int maxLen)
Returns the capture state.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, unsigned short &len, bool stackLevel=false)
Reads a configuration parameter.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, bool stackLevel=false)
Reads a configuration parameter from RAM of the sensor (not from flash).
virtual void getConnectionName (char *buffer)
Returns a description for the connection.
virtual void getLocalConnectionName (char *buffer)
Returns an identifier string for local connection (eg IP:port); Currently returns a fixed dummy string.
virtual void getName (char *nameBuffer, int maxLen)
Returns a description for the sensor (ConnectionName + @ + UipAddress)
SENSOR_RESULT getParameterGroupIds (IdSet &groupIds)
Retrieves a set of existing group ids.
SENSOR_RESULT getParameterGroups (ParameterGroups &groups)
Retrieves a map (ParameterGroups) of group ids to group name.
SENSOR_RESULT getParameterIds (const unsigned short groupId, IdSet &paramIds)
SENSOR_RESULT getParameterInfos (const unsigned short groupId, ParameterInfos &infos, const bool includeNames=false)
SENSOR_RESULT getParameterName (const unsigned short groupId, const unsigned short paramId, std::string &paramName)
getParameterName Returns only the name of the specified parameter
iris::drivers::Sensor & getSensor (void)
Returns the associated Sensor instance (from Driver)
unsigned char getUipAddress (void)
Returns the UIP address (integer between 1-255).
SENSOR_RESULT getWorkingMode (iris::uip::working_mode &mode)
Retrieves the sensor working mode (iris::uip::working_mode).
SENSOR_RESULT listAllSupportedMessages (MessageTypeDefinitionList &buffer)
listAllSupportedMessages lists all messages the sensor can respond to.
SENSOR_RESULT lockImmanentData (void)
lockImmanentData
SENSOR_RESULT pingNeighbour (const unsigned char neighbourAddress, const unsigned short payloadLen, const unsigned short repetitions, const unsigned short timeoutMs, unsigned short &successCount, unsigned short &averageTimeMs)
Asks a sensor to ping one of its neighbours (same FA) for a given number of repetitions.
SENSOR_RESULT pingSensor (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Pings a sensor.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT releaseDevice (void)
Releases ("uncaptures") the sensor.
void resetTimeoutParameters (void)
Resets the timeout params to the default values (offset 0, factor 1.0)
SENSOR_RESULT restoreConfigurationFromFlash (void)
Copies the configuration from flash memory to RAM.
SENSOR_RESULT saveConfigurationToFlash (void)
Copies the configuration from RAM to flash memory.
UipMessage * sendAndGetApplReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * sendAndGetServiceReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
UipMessage * sendAndGetStackReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT sendUipCommand (char type, unsigned char version, char command, unsigned short payloadLen, char *payload, unsigned int timeoutMs, char &replyType, unsigned char &replyVersion, char &replyCommand, unsigned short &replyPayloadLen, char *replyPayloadBuffer)
Sends a "free" UIP command to the sensor and waits for the reply.
SENSOR_RESULT setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel=false)
Sets a configuration parameter in the sensor's RAM (not in the flash).
SENSOR_RESULT setConfigurationParameterIfKnown (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool &paramWasUnknown, bool stackLevel=false)
Like setConfigurationParameter but only if that parameter is known.
void setUipAddress (unsigned char)
setUipAddress Sets a new UIP address for communication with this sensor.
void setUipTimeout (const int timeoutMs)
Sets timeout used for UIP send and get reply methods (whereafter usually a retry is performed).
SENSOR_RESULT setWorkingMode (const iris::uip::working_mode mode)
Sets the sensor working mode.
SENSOR_RESULT unlockImmanentData (void)
unlockImmanentData
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
virtual ~Dist500Base ()
Destructor.
Public Member Functions inherited from iris::dist500::PictureSource
void pushPictureToSinks (Picture *data, unsigned long index, unsigned long indexCount)
Propagates a new Picture to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< Picture * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Member Functions inherited from iris::dist500::RegisterValuesSource
void pushRegisterValuesToSinks (RegisterValues *data, unsigned long index, unsigned long indexCount)
Propagates new RegisterValues to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< RegisterValues * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Member Functions inherited from iris::dist500::DebugDataSource
void pushDebugDataToSinks (DebugData *data, unsigned long index, unsigned long indexCount)
Propagates a new DebugData to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< DebugData * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Member Functions inherited from iris::dist500::FpgaController
FpgaController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT getCurrentTemperatureRegister (unsigned char &temperature)
Gets the value of the "Current Temperature" FPGA register.
SENSOR_RESULT getDebugModeRegister (unsigned char &debug)
Gets the value of the "Debug Mode" FPGA register.
SENSOR_RESULT getDistanceOffsetRegister (unsigned char &offset)
Gets the value of the "Distance Offset" FPGA register.
SENSOR_RESULT getExposureTimeRegister (unsigned char &exposure)
Gets the value of the "Exposure Time" FPGA register.
SENSOR_RESULT getFirmwareRegister (unsigned char &version)
Gets the value of the "Firmware" FPGA register.
SENSOR_RESULT getFpgaRegister (const FpgaRegister registr, unsigned char &buffer)
Returns the current value of an FPGA register.
SENSOR_RESULT getIlluminationControlRegister (unsigned char &illumination)
Gets the value of the "Illumination Control" FPGA register.
SENSOR_RESULT getMaxTemperatureRegister (unsigned char &temperature)
Gets the value of the "Max Temperature" FPGA register.
SENSOR_RESULT getModeRegister (unsigned char &mode)
Gets the value of the "Mode" FPGA register.
SENSOR_RESULT getPicturePeriodRegister (unsigned char &period)
Gets the value of the "Picture Period" FPGA register.
SENSOR_RESULT getSaturationRegister (unsigned short &saturation)
Gets the value of the "Saturation" FPGA register pair.
SENSOR_RESULT getStatusBitSelectionRegister (unsigned char &selection)
Gets the value of the "Status Bit Selection" FPGA register.
SENSOR_RESULT getStatusRegister (unsigned char &status)
Gets the value of the "Status" FPGA register.
SENSOR_RESULT getThresholdRegister (unsigned short &threshold)
Gets the value of the "Threshold" FPGA register pair.
SENSOR_RESULT setCommandRegister (const unsigned char command)
Sets the value of the "Command" FPGA register.
SENSOR_RESULT setDebugModeRegister (const unsigned char debug)
Sets the value of the "Debug Mode" FPGA register.
SENSOR_RESULT setDistanceOffsetRegister (const unsigned char offset)
Sets the value of the "Distance Offset" FPGA register.
SENSOR_RESULT setExposureTimeRegister (unsigned char exposure)
Sets the value of the "Exposure Time" FPGA register.
SENSOR_RESULT setFpgaRegister (const FpgaRegister registr, const unsigned char value)
Sets the value of an FPGA register.
SENSOR_RESULT setIlluminationControlRegister (const unsigned char illumination)
Sets the value of the "Illumination Control" FPGA register.
SENSOR_RESULT setMaxTemperatureRegister (const unsigned char temperature)
Sets the value of the "Max Temperature" FPGA register.
SENSOR_RESULT setModeRegister (const unsigned char mode)
Sets the value of the "Mode" FPGA register.
SENSOR_RESULT setPicturePeriodRegister (unsigned char period)
Sets the value of the "Picture Period" FPGA register.
SENSOR_RESULT setSaturationRegister (const unsigned short saturation)
Sets the value of the "Saturation" FPGA register pair.
SENSOR_RESULT setStatusBitSelectionRegister (const unsigned char selection)
Sets the value of the "Status Bit Selection" FPGA register.
SENSOR_RESULT setThresholdRegister (const unsigned short threshold)
Sets the value of the "Threshold" FPGA register pair.
SENSOR_RESULT uploadFullSingleUffMoviePicture (unsigned long picNumber, unsigned long long timestamp, unsigned short *picture, const char numberOfDoors, const iris::uip::door_status *doorState, bool ledOn)
Uploads a full single Picture into the sensor.
SENSOR_RESULT uploadUffMovie (const std::string &filename, int &picCount)
Uploads an UFF movie into the sensor for simulation.
virtual ~FpgaController ()
Destructor.
Public Member Functions inherited from iris::dist500::FirmwareController
virtual SENSOR_RESULT configureSensorGroup (const FirmwareControllerList &slaves, const iris::configuration::CommunicationGroup::IpAddress &ipAddr, const iris::configuration::CommunicationGroup::IpAddress &netMask, const iris::configuration::CommunicationGroup::IpAddress &gwAddr, const unsigned short port, const iris::configuration::CommunicationGroup::IpAddress &sntp1Addr, const iris::configuration::CommunicationGroup::IpAddress &sntp2Addr, ConfigurationInterceptor &interceptor)
Configures a sensor as master and optionally one or more sensors as slaves to this master;.
virtual SENSOR_RESULT configureStandalone (const iris::configuration::CommunicationGroup::IpAddress &ipAddr, const iris::configuration::CommunicationGroup::IpAddress &netMask, const iris::configuration::CommunicationGroup::IpAddress &gwAddr, const unsigned short port, const iris::configuration::CommunicationGroup::IpAddress &sntp1Addr, const iris::configuration::CommunicationGroup::IpAddress &sntp2Addr, ConfigurationInterceptor &interceptor)
Configures one sensor as single sensor.
FirmwareController (iris::drivers::Sensor &sensor)
Constructor.
FirmwareFitHardwareResult firmwareFitsHardware (const std::string &hexFile, void *userData=0)
Checks if the given firmware matches the hardware.
bool firmwareFitsHardware (const std::string &hexFile, Dist500List &remainingGroupSensors, FirmwareFitHardwareResultMap &resultMap, void *userData=0)
Checks if the given firmware matches the hardware.
unsigned short getGroupIndex (void)
Returns the group index.
SensorGroup * getSensorGroup (void)
Returns the SensorGroup instance.
SensorInfo getSensorInfo (bool forceRefresh=false)
Retrieves information about the sensor.
bool hasSensorInfo (void) const
Checks whether a cached sensor info exists.
void invalidateSensorInfo (void)
Clears the sensor information cache.
virtual SENSOR_RESULT loadFpgaImage (const std::string &bitfileName, bool primary, void *userData, UPDATE_CALLBACK updateCallback)
Loads the primary or secondary FPGA bitfile (firmware)
virtual SENSOR_RESULT loadFpgaImage (const unsigned char *fileContents, unsigned int fileSize, bool primary, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performApplicationFirmwareUpdate (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback)
Updates the application firmware part from the given .LDR file.
virtual SENSOR_RESULT performApplicationFirmwareUpdate (char *hexfileContents, unsigned long hexfileSize, const std::string &hexfileName, const std::string &firmwareTimestamp, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performApplicationFirmwareVerification (const std::string &hexfileName, void *userData, UPDATE_CALLBACK verificationCallback)
virtual SENSOR_RESULT performApplicationFirmwareVerification (char *hexfileContents, unsigned long hexfileSize, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performBootloaderFirmwareUpdate (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback)
Updates the bootloader firmware part from the given .LDR file.
virtual SENSOR_RESULT performBootloaderFirmwareUpdate (char *hexfileContents, unsigned long hexfileSize, const std::string &hexfileName, const std::string &firmwareTimestamp, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performBootloaderFirmwareVerification (const std::string &hexfileName, void *userData, UPDATE_CALLBACK verificationCallback)
virtual SENSOR_RESULT performBootloaderFirmwareVerification (char *hexfileContents, unsigned long hexfileSize, void *userData, UPDATE_CALLBACK updateCallback)
bool performContainerUpdate (const std::string &containerFilename, UpdateResultMap &resultMap, bool checkSensorConsistency=true, void *userData=0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback=0)
Updates firmware and parameter from the given .D5FC file.
bool performContainerUpdate (const std::string &containerFilename, Dist500List &remainingGroupSensors, UpdateResultMap &resultMap, bool checkSensorConsistency=true, void *userData=0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback=0)
Updates firmware and parameter from the given .D5FC file.
bool performContainerUpdateDefaults (const std::string &containerFilename, Dist500List &remainingGroupSensors, UpdateResultMap &resultMap, bool checkSensorConsistency, bool defaultValues, void *userData=0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback=0)
Updates firmware and parameter from the given .D5FC file.
virtual SENSOR_RESULT performFpgaImageVerification (const std::string &bitfileName, bool primary, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performFpgaImageVerification (const unsigned char *fileContents, unsigned int fileSize, bool primary, void *userData, UPDATE_CALLBACK updateCallback)
void setGroupIndex (unsigned short gi)
Sets the sensor index within a group.
void setSensorGroup (SensorGroup *sg)
Sets the associated SensorGroip.
virtual SENSOR_RESULT writeApplicationFirmwareInfoBlock (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback)
Updates the application firmware info block according to the given .LDR file.
virtual SENSOR_RESULT writeBootloaderFirmwareInfoBlock (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback)
Updates the bootloader firmware info block according to the given .LDR file.
virtual ~FirmwareController ()
Destructor.
Public Member Functions inherited from iris::dist500::FlashController
SENSOR_RESULT eraseFirmware (iris::uip::firmware_type firmwareType)
eraseFirmware Erases a backup firmware in the sensor.
SENSOR_RESULT eraseMemory (unsigned long address)
Erases a Flash sector.
FlashController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT readFirmware (uip::ushort messageCount, iris::uip::firmware_type firmwareType, iris::uip::backup_type backupType, uip::ulong byteOffset, iris::uip::uchar *buffer, uip::ushort numberOfBytes)
readFirmware Reads the specified firmwareType
SENSOR_RESULT readMemory (unsigned long address, char *buffer, unsigned short byteCount)
Reads data from the flash.
SENSOR_RESULT switchFirmware (iris::uip::ulonglong uniqueRequestId, iris::uip::uchar firmwareFlagsCount, const iris::uip::firmware_type *firmwareTypeFlags)
switchFirmware Switches the specified type(s) of firmware.
SENSOR_RESULT writeFirmware (uip::ushort messageCount, iris::uip::firmware_type firmwareType, uip::ulong byteOffset, iris::uip::uchar *buffer, uip::ushort numberOfBytes)
writeFirmware Writes the specified firmwareType.
SENSOR_RESULT writeMemory (unsigned long address, char *buffer, unsigned short byteCount, bool verify=false)
Writes data into the Flash.
virtual ~FlashController ()
Destructor.
Public Member Functions inherited from iris::dist500::CounterController
SENSOR_RESULT checkCategoryDefinitionAcceptance (const iris::uip::category &categoryDefinition, bool &accepted)
Checks whether the given count category is acceptable.
CounterController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT getCountCategories (unsigned short functionArea, CategoryList &categoryList)
Retrieves the supported count categories.
SENSOR_RESULT getCountResults (unsigned short functionArea, iris::uip::counter_type counterType, bool resetFlag, unsigned char categoryId, CountList &countList)
Retrieves the count results.
SENSOR_RESULT getFunctionAreaStatuses (FunctionAreaStatusList &statusList)
Retrieves the function area status(es)
SENSOR_RESULT getKnownCategoryTypes (CategoryTypeSet &typeSet)
Retrieves the known count category types.
SENSOR_RESULT getSensorStatuses (SensorStatusSet &statusSet)
Retrieves the sensor status(es)
SENSOR_RESULT resetCounts (const unsigned short functionArea, iris::uip::counter_type counterType)
Requests reset of the boarding/alighting counters.
SENSOR_RESULT resetSensorStatuses (const SensorStatusSet &statusSet, SensorStatusNotificationList &statusNotificationList)
Resets the sensor status(es) List of sensor status notifications informs about actual changes of sensor status(es)
SENSOR_RESULT setCountResults (unsigned short functionArea, iris::uip::counter_type counterType, bool countingFinished, const CountList &countList)
Sets the count results (for debugging purposes)
SENSOR_RESULT startCounting (void)
Starts counting.
SENSOR_RESULT stopCounting (void)
Stops counting.
Public Member Functions inherited from iris::dist500::CountResultSource
void pushCountResultToSinks (CountResult *result, unsigned long index, unsigned long indexCount)
Propagates a new CountResult to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< CountResult * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Member Functions inherited from iris::dist500::DoorController
SENSOR_RESULT disableHallSensor (void)
Disable the hall sensor.
DoorController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT enableHallSensor (void)
Enable the hall sensor.
SENSOR_RESULT getDoorState (unsigned short functionArea, unsigned short doorNumber, unsigned char &leftState, unsigned char &rightState)
Retrieves a door state.
SENSOR_RESULT getHallSensorFunction (iris::uip::hall_sensor_function &function)
Get the hall sensor function.
SENSOR_RESULT getHallSensorState (unsigned char &state)
Retrieves the hall sensor state.
SENSOR_RESULT setDoorState (unsigned short functionArea, unsigned short doorNumber, unsigned char leftState, unsigned char rightState)
Sets the state of a door.
SENSOR_RESULT setHallSensorFunction (iris::uip::hall_sensor_function function)
Set the hall sensor function.
SENSOR_RESULT setHallSensorState (ManualHallSensorStatus state)
Sets the state of the hall sensor.
Public Member Functions inherited from iris::dist500::DoorStateSource
void pushDoorStateToSinks (DoorState *data, unsigned long index, unsigned long indexCount)
Propagates a new DoorState to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< DoorState * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Member Functions inherited from iris::dist500::HallSensorStateSource
void pushHallSensorStateToSinks (HallSensorState *data, unsigned long index, unsigned long indexCount)
Propagates a new HallSensorState to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< HallSensorState * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Member Functions inherited from iris::dist500::LoggerController
SENSOR_RESULT deleteAllLogEntries (std::string &errorString)
SENSOR_RESULT getLogEntries (iris::uip::ushort numberOfEntries, iris::uip::support_level_enumeration supportLevelEnumeration, LogMap &logMap, std::string &errorString)
SENSOR_RESULT getOperationTimeCounter (iris::uip::operation_time_counter_enumeration counterType, iris::uip::ulonglong &operationTime, iris::uip::ulong &numberOfEvents, std::string &errorString)
SENSOR_RESULT getUpdateHistoryEntries (iris::uip::ushort numberOfEntries, UpdateHistoryMap &logMap, std::string &errorString)
LoggerController (iris::drivers::Sensor &sensor)
Static Protected Member Functions
static bool dispatchCallback (iris::drivers::Sensor &sensor, void *userData, const int level, const UipMessage *message)
Static callback for incoming messages in "streaming" installation mode.
Static Protected Member Functions inherited from iris::dist500::InstallationModeController
static void handleSpontaneousDebugDataMessage (Dist500Base *base, UipMessage *message)
static void handleSpontaneousPictureMessage30 (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for P 3.0.
static void handleSpontaneousPictureMessage31 (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for P 3.1.
static void handleSpontaneousPictureMessage32 (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for P 3.2.
static bool isSensorInUse (InstallationModeController *sensor)
static void registerRunningSensor (InstallationModeController *sensor)
static void registerStoppingSensor (InstallationModeController *sensor)
static void unregisterRunningSensor (InstallationModeController *sensor)
Static Protected Member Functions inherited from iris::dist500::Dist500Base
static void handleSpontaneousWorkingModeMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for U 2.0.
Static Protected Member Functions inherited from iris::dist500::FirmwareController
static void _hexFileCallback (void *userData, const unsigned long address, const unsigned char *const data, const unsigned char len)
Static (global) callback for hex file decoding.
static bool checkSensorsConsistency (Dist500List &sensorList, UpdateResultMap &resultMap)
Check if all sensors of a group exist.
static void configurationContainerCallback (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback function for configuration parameter update.
static SENSOR_RESULT findFirmwareInfoWatermark (bool &hasWatermark, char *&infoStart)
Checks is a firmware info watermark in the give firmware.
static bool firmwareFitsHardwareCheck (iris::hexfiles::HexFileStreamReader &hexReader, const std::string &hexfileName, Dist500 *sensor, FirmwareFitHardwareResult &fitResult, void *userData)
Performs the check for one sensor.
static void getDefaultSensorSerialPrefix (std::map< uint8_t, uint32_t > &prefixMap)
getDefaultSensorSerialPrefix
static void hexFileReleaseInfoCallback (void *userData, const unsigned long address, const unsigned char *const data, const unsigned char len)
Static (global) callback for hex file decoding.
static bool performContainerFirmwareUpdate (const std::string &containerFilename, Dist500List &sensorList, UpdateResultMap &resultMap, bool checkSensorConsistency, bool defaultValues, void *userData, CONTAINER_UPDATE_CALLBACK containerUpdateCallback)
Performs the container firmware update from the given .D5FC file.
static bool performContainerParameterUpdate (Dist500 &sensor, iris::legacy::Dist500FirmwareContainerDecoder &decoder, iris::configuration::Dist500Configuration &config, iris::dist500::Dist500Base::ConfigurationMismatches &mismatches, bool defaultValues, UpdateResultMap &resultMap, void *userData)
Performs configuration parameter update from container file.
static bool performFirmwareFitsHardwareCheck (const std::string &hexFile, Dist500List &sensorList, FirmwareFitHardwareResultMap &resultMap, void *userData)
Performs the checks if the given firmware matches the hardware.
static void resetToDefaultOperation (iris::configuration::Dist500Configuration &config)
Resets all sensor configuration data with certain exceptions needed to enable default operation of sensor.
static bool updateContainerApplication (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, bool &skipped, void *userData)
Performs a application firmware update from container file.
static void updateContainerCallback (void *userData, unsigned int step, unsigned int totalSteps, double stepPercentage, double totalPercentage)
Callback function container update.
static bool updateContainerCommunication (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, bool &skipped, void *userData)
Performs a communication firmware update from container file.
static bool updateContainerFpga (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, bool primary, bool skipFpgaRelease, bool &skipped, void *userData)
Performs a FPGA firmware update from container file.
static bool verifyContainerApplication (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, void *userData)
Performs a application firmware verifcation from container file.
static bool verifyContainerCommunication (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, void *userData)
Performs a communication firmware verifcation from container file.
static bool verifyContainerFpga (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, bool primary, bool skipFpgaRelease, void *userData)
Performs a FPGA firmware verifcation from container file.
static void waitForSensors (Dist500List &sensors, ContainerUpdateUserData &containerUpdateUserData, unsigned int timeMs, unsigned int intervals)
waitForSensors Waits for sensors and invokes callback for progress bar update
Static Protected Member Functions inherited from iris::dist500::CounterController
static void handleSpontaneousCountMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for C 6.0.
Static Protected Member Functions inherited from iris::dist500::DoorController
static void handleSpontaneousDoorMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for D 3.0.
static void handleSpontaneousHallSensorMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for D 3.1.
Additional Inherited Members
Static Public Member Functions inherited from iris::dist500::Dist500Base
static void disableAutomaticRetries (void)
disables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
static void enableAutomaticRetries (void)
enables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
Static Public Member Functions inherited from iris::dist500::FirmwareController
static bool firmwareFitsHardwareForSensors (const std::string &hexFile, Dist500List &sensorList, FirmwareFitHardwareResultMap &resultMap, void *userData=0)
Checks if the given firmware matches the hardware.
static bool getIrisOnlyUpdateAuthorized (void)
static bool performContainerUpdateForSensors (const std::string &containerFilename, Dist500List &sensorList, UpdateResultMap &resultMap, bool checkSensorConsistency=true, void *userData=0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback=0)
Updates firmware and parameter from the given .D5FC file.
static void setIrisOnlyUpdateAuthorized (bool authorized)
Static Public Member Functions inherited from iris::dist500::CounterController
static bool broadcastStartCounting (void)
static bool broadcastStopCounting (void)
Public Attributes inherited from iris::dist500::InstallationModeController
InstallationModeType instModeType
Holds the current installation mode type.
Static Public Attributes inherited from iris::dist500::FirmwareController
static const unsigned long ConfigurationDataFlashAddress = FlashStartAddress + 0x100000
static const unsigned long FIRMWARE_INFO_SIZE = 0x14C
static const unsigned long FIRMWARE_INFO_WITH_CRC_SIZE = 0x150
static const unsigned long FlashBankSize = 0x200000
static const unsigned long FlashSectorSize = 0x20000
static const unsigned long FlashStartAddress = 0x20000000
static const unsigned long START_FIRMWARE_INFO_APPL = 0x001FFEB0
static const unsigned long START_FIRMWARE_INFO_BOOT = 0x000FFEB0
Protected Types inherited from iris::dist500::InstallationModeController
typedef std::set< InstallationModeController * > InstModeSensorsSet
Protected Types inherited from iris::dist500::Dist500Base
typedef std::map< unsigned short, ParameterInfo > GroupParameterInfos
typedef std::map< unsigned short, ParameterValue > GroupParameterValues
typedef std::set< int > NoRetryMessageHashSet
typedef std::bitset< 1024 > ReceptionFlags
Protected Types inherited from iris::dist500::Source< Picture * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Types inherited from iris::dist500::Source< RegisterValues * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Types inherited from iris::dist500::Source< DebugData * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Types inherited from iris::dist500::FirmwareController
typedef std::list< int32_t > ListFpgaFilesContainerIndex
typedef std::map< Dist500 *, SensorInformation > SensorInformationMap
Protected Types inherited from iris::dist500::Source< CountResult * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Types inherited from iris::dist500::Source< DoorState * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Types inherited from iris::dist500::Source< HallSensorState * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Member Functions inherited from iris::dist500::InstallationModeController
SENSOR_RESULT _listDebugDataSources (DataSourceInfoList &sources, ReceptionFlags &receivedSources)
SENSOR_RESULT continueInstallationMode (void)
void discardCallbacks (void)
Disables all callbacks.
void firePictureCallback (unsigned char subPicNo, unsigned char subPicTotal, char subPicType, unsigned long pictureNumber, unsigned long long timestamp, unsigned short *values)
Calls the new picture callback function.
void fireRegisterValuesCallback (unsigned long pictureNumber, unsigned long long timestamp, unsigned short regCount, unsigned short *regNos, unsigned short *regVals)
Calls the new register values callback function.
Protected Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos, ReceptionFlags &receivedParameters, iris::uip::ushort &expectedCount)
SENSOR_RESULT _legacyReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _optimizedReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings, const bool sendEmptyIfDefault, ReceptionFlags &receivedParams, iris::uip::ushort &expectedCount)
This is internally used in optimized sensor configuration readouts.
SENSOR_RESULT _setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel, bool ignoreUnknownParamErrors, bool &paramWasUnknown)
SENSOR_RESULT _writeConfiguration (iris::configuration::Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
bool automaticRetriesSupported (UipMessage *message)
Checks if automatic retries are currently supported for the specified message.
SENSOR_RESULT describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos)
describeAllGroupParametersWithoutNames Gets descriptions (GroupParameterInfos) of parameters within the specified configuration group.
SENSOR_RESULT describeParameterWithoutName (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info)
describeParameterWithoutName Gets type and value range information for the specified parameter.
SENSOR_RESULT getGroupName (const unsigned short groupId, std::string &groupName)
getGroupName Gets the name of the specified configuration group.
float getTimeoutFactor (void) const
Returns the timeout factor.
unsigned long getTimeoutOffset (void) const
Returns the timeout offset.
void initializeNoRetryMessageHashSet (void)
These are the messages that are not automatically repeated in case no reply arrives.
SENSOR_RESULT readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings=true, const bool sendEmptyIfDefault=true)
Used for sensor configuration readout, returns a map with parameter values for the specified configuration group.
void registerNoRetryMessage (unsigned char type, unsigned char version, unsigned char command)
Makes the specified message not be automatically resent if no replay arrives.
SENSOR_RESULT requestKeyPuzzle (unsigned short &puzzleLen, unsigned char *puzzleBuffer)
SENSOR_RESULT unlockImmanentData (const unsigned short keyLen, const unsigned char *key)
unlockImmanentData
Protected Member Functions inherited from iris::dist500::Source< Picture * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (Picture * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Member Functions inherited from iris::dist500::Source< RegisterValues * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (RegisterValues * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Member Functions inherited from iris::dist500::Source< DebugData * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (DebugData * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Member Functions inherited from iris::dist500::FpgaController
SENSOR_RESULT activateMovie (void)
Activates the movie by resetting the simulation.
SENSOR_RESULT prepareMovieUpload (int &picCount)
Prepares the upload of an UFF movie for simulation.
SENSOR_RESULT uploadMoviePicture (unsigned char subPicNo, unsigned char subPicTotal, iris::uip::sub_pic_type subPicType, unsigned long picNumber, unsigned long long timestamp, unsigned short *pixels, const char numberOfDoors, const iris::uip::door_status *doorState, bool ledOn)
Uploads a movie (sub-)picture to the sensor.
Protected Member Functions inherited from iris::dist500::FirmwareController
SENSOR_RESULT findBootloaderWatermark (bool &hasWatermark)
void hexFileCallback (const unsigned long address, const unsigned char *const data, const unsigned char len)
Callback (sensor-specific) for hex file decoding.
SENSOR_RESULT performFirmwarePartUpdate (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback, bool application, bool onlyWriteInfo=false)
Updates a firmware part from the given .LDR file.
SENSOR_RESULT performFirmwarePartUpdate (char *hexfileContents, const unsigned long hexfileSize, const std::string firmwareFilename, const std::string &firmwareTimestamp, void *userData, UPDATE_CALLBACK updateCallback, bool application, bool onlyWriteInfo=false)
SENSOR_RESULT performFirmwarePartUpdate (iris::hexfiles::HexFileStreamReader &hex, const std::string &hexfileName, const std::string &firmwareTimestamp, void *userData, UPDATE_CALLBACK updateCallback, bool application, bool onlyWriteInfo=false)
SENSOR_RESULT performFirmwarePartVerification (hexfiles::HexFileStreamReader &hex, void *userData, UPDATE_CALLBACK verificationCallback, bool application)
Protected Member Functions inherited from iris::dist500::Source< CountResult * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (CountResult * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Member Functions inherited from iris::dist500::Source< DoorState * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (DoorState * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Member Functions inherited from iris::dist500::Source< HallSensorState * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (HallSensorState * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Attributes inherited from iris::dist500::InstallationModeController
iris::synchronization::Mutex callbackMutex
Mutex for installation mode parameters.
iris::uip::ushort instModeRegCount
iris::uip::ushort instModeRegNos [MaxInstModeRegCount]
volatile bool instModeRunning
unsigned long lastPictureNumber
Holds the last picture number in installation mode.
unsigned long long lastTimestamp
Holds the timestamp of the last picture in installation mode.
unsigned int maxPictures
Holds the installation mode picture limit.
unsigned long long maxTime
Holds the installation mode time limit.
Picture * pictureBuffer
Buffer for Picture instance.
unsigned int pictureCount
Holds the current installation mode picture count.
unsigned short pixelBuffer [1000]
Buffer for pixel values.
PROGRESS_CALLBACK progressCallback
Installation mode progress callback.
STATUS_CALLBACK statusCallback
Installation mode status callback.
iris::synchronization::Event terminationEvent
Installation mode termination event.
bool useInstallationModeRetrigger
void * userData
User-defined additional parameter for installation mode callback.
Protected Attributes inherited from iris::dist500::Dist500Base
SpontaneousHandlers handlers
Handler manger for spontaeous UIP messages (sub-command *)
NoRetryMessageHashSet noRetryMessageHashSet
iris::drivers::Sensor & sensor
Reference to associatee driver's Sensor object.
float timeoutFactor
Factor to applied to standard timeouts.
unsigned long timeoutOffset
Constant offset to be applied to standard timeouts.
unsigned char uipAddress
UIP address of sensor.
int uipTimeout
Timeout in ms used for UIP send and get reply methods.
Protected Attributes inherited from iris::dist500::Source< Picture * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Protected Attributes inherited from iris::dist500::Source< RegisterValues * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Protected Attributes inherited from iris::dist500::Source< DebugData * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Protected Attributes inherited from iris::dist500::FirmwareController
bool determineHexFileAddressRange
Indicated whether addresses are to be evaluated (true) or if data is to be copied to firmware buffer (false)
char * firmware
Buffer for firmware, only used temporarily (otherwise 0)
unsigned long firmwareDecodedSize
firmwareDecodedSize Stores length of binary data that was decoded from the Intel HEX file
unsigned short groupIndex
Contraing the sensor index within the group.
unsigned long maxHexFileAddress
Holds the maximum address in a hex file.
unsigned long minHexFileAddress
Holds the minimum address in a hex file.
SensorGroup * sensorGroup
Refres to the SensorGtroup, if any.
SensorInfo * sensorInfo
May hold a SensorInfo instance for caching (0 if unused)
Protected Attributes inherited from iris::dist500::Source< CountResult * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Protected Attributes inherited from iris::dist500::Source< DoorState * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Protected Attributes inherited from iris::dist500::Source< HallSensorState * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Static Protected Attributes inherited from iris::dist500::InstallationModeController
static const int MaxInstModeRegCount = 32
static iris::synchronization::Mutex requestMutex
static RequestThread * requestThread = 0
static InstModeSensorsSet runningSensors
static InstModeSensorsSet stoppingSensors
Static Protected Attributes inherited from iris::dist500::Dist500Base
static bool automaticRetriesDisabled = false
Static Protected Attributes inherited from iris::dist500::FirmwareController
static bool determineHexFileReleaseInfoAddressRange
Indicated whether addresses are to be evaluated (true) or if data is to be copied to firmware buffer (false)
static bool irisOnlyUpdateAuthorized
static const unsigned int MAX_FPGA_BITFILE_SIZE = MAX_FPGA_IMAGE_SIZE + 1024
static const unsigned int MAX_FPGA_IMAGE_SIZE = 128 * 1024
static unsigned long maxHexFileReleaseInfoAddress
Holds the maximum address in a hex file.
static unsigned long minHexFileReleaseInfoAddress
Holds the minimum address in a hex file.
static char * releaseInfoFirmware
Buffer for firmware.
Detailed Description
Represents a DIST500 sensor.
Constructor & Destructor Documentation
iris::dist500::Dist500::Dist500 (iris::drivers::Sensor & sensor)
Constructor.
Parameters
sensor
References dispatchCallback(), and iris::drivers::Sensor::setDispatchCallback().
Member Function Documentation
SENSOR_RESULT iris::dist500::Dist500::disableExposureControl ()
Switches the automatic exposure controll off.
Returns
Operation result
See also
enableExposureControl
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
bool iris::dist500::Dist500::dispatchCallback (iris::drivers::Sensor & sensor, void * userData, const int level, const UipMessage * message) static protected
Static callback for incoming messages in "streaming" installation mode.
Parameters
sensor Sensor instance
userData User-defined additional parameter
level UIP message level
message UIP message
Returns
true if message has been processed, false otherwise
References iris::dist500::Dist500Base::SpontaneousHandlers::forward(), iris::dist500::Dist500Base::handlers, and iris::dist500::InstallationModeController::userData.
Referenced by Dist500().
SENSOR_RESULT iris::dist500::Dist500::enableExposureControl (void)
Switches the automatic exposure control on.
Returns
Operation result
See also
disableExposureControl
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::Dist500::getDspRegisters (const RegisterList & registerList, RegisterValueMap & registerValueMap)
Gets a list with DSP registers useful for introspection.
Parameters
registerList
registerValueMap
Returns
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::Dist500::getFirmwareFeatures (FirmwareFeatureSet & featureSet)
Returns a set of supported firmware features.
See enumeration firmware_feature_type. Some older firmwares do not support this message. See checkSupportForMessage().
Parameters
featureSet
Returns
Operation success
References iris::messages::DynamicBuffer::getLength(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::Dist500::getSensorRevisionCode (unsigned short & revisionCode)
Returns the sensor revision code.
Parameters
revisionCode Output parameter
Returns
See also
SensorInfo
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
Referenced by iris::dist500::FirmwareController::firmwareFitsHardwareCheck().
SENSOR_RESULT iris::dist500::Dist500::getStatusLedMode (iris::uip::status_led_work_mode & mode)
Returns the status LED mode.
This is not related to the infrared illumination LEDs.
Parameters
mode Output parameter containing an iris::uip::status_led_work_mode
Returns
See also
setStatusLedMode
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::Dist500::isPictureAcquisitionRunning (bool & running)
Checks if picture acquisition is running.
Returns
Operation result
Deprecated:
the typographic error is also left for backwards (compile) compatibility.
References iris::dist500::FpgaController::getStatusRegister(), and iris::dist500::OPERATION_PASSED.
SENSOR_RESULT iris::dist500::Dist500::resetCommunicationTestCounter (void)
Used with sendCommunicationTestMessage to reset the counter in the sensor.
Returns
Operation result
References iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::Dist500::resetDsp (void)
Orders the sensor to restart which takes a couple of seconds to become fully operational.
Also called "soft reboot" whereas a "hard reboot" is made by powering off and on.
Returns
Operation result
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::FirmwareController::invalidateSensorInfo(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
Referenced by iris::dist500::FirmwareController::performContainerFirmwareUpdate().
SENSOR_RESULT iris::dist500::Dist500::sendCommunicationTestMessage (const unsigned long number, unsigned long & expectedNumber, const unsigned short testDataLen, const char *const payload)
Sends a test message with a number which is expected to be returned in the reply payload; number can be reset with resetCommunicationTestCounter.
Parameters
number
expectedNumber
testDataLen
payload
Returns
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::Dist500::setStatusLedMode (const iris::uip::status_led_work_mode mode)
Sets the status LED mode (on, off or blinking behaviour).
This is not related to the infrared illumination LEDs.
Parameters
mode Is a iris::uip::status_led_work_mode
Returns
See also
getStatusLedMode
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::Dist500::startPictureAcquisision (void)
Starts the picture acquisition.
Returns
Operation result
See also
stopPictureAcquisision
Deprecated:
the typographic error is also left for backwards (compile) compatibility.
References iris::dist500::FpgaController::setCommandRegister().
SENSOR_RESULT iris::dist500::Dist500::stopPictureAcquisision (void)
Stops the picture acquisition.
Returns
Operation result
See also
startPictureAcquisision
Deprecated:
the typographic error is also left for backwards (compile) compatibility.
References iris::dist500::FpgaController::setCommandRegister().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/Dist500.h
SensorAPI/implementation/iris/dist500/Dist500.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !