IRMA MATRIX SDK: iris::dist500::FpgaController Class Reference
iris::dist500::FpgaController Class Reference
Implements FPGA related functions within the DIST500 firmware.
#include <FpgaController.h>
Public Types
enum FpgaRegister {
CommandRegister, StatusRegister, ModeRegister, FirmwareRegister,
ThresholdLowRegister, ThresholdHighRegister, SaturationLowRegister, SaturationHighRegister,
DistanceOffsetRegister, ExposureTimeRegister, MaxTemperatureRegister, CurrentTemperatureRegister,
StatusBitSelectionRegister, PicturePeriodRegister, IlluminationControlRegister, DebugModeRegister = 31
}
FPGA register number definitions.
Public Types inherited from iris::dist500::Dist500Base
typedef std::set< unsigned short > IdSet
typedef std::list< iris::uip::messageTypeDef > MessageTypeDefinitionList
typedef std::map< unsigned short, std::string > ParameterGroups
typedef std::map< unsigned short, ParameterInfo > ParameterInfos
typedef void(* TRANSFER_CONFIGURATION_CALLBACK) (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback for sensor configuration transfers.
Public Member Functions
FpgaController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT getCurrentTemperatureRegister (unsigned char &temperature)
Gets the value of the "Current Temperature" FPGA register.
SENSOR_RESULT getDebugModeRegister (unsigned char &debug)
Gets the value of the "Debug Mode" FPGA register.
SENSOR_RESULT getDistanceOffsetRegister (unsigned char &offset)
Gets the value of the "Distance Offset" FPGA register.
SENSOR_RESULT getExposureTimeRegister (unsigned char &exposure)
Gets the value of the "Exposure Time" FPGA register.
SENSOR_RESULT getFirmwareRegister (unsigned char &version)
Gets the value of the "Firmware" FPGA register.
SENSOR_RESULT getFpgaRegister (const FpgaRegister registr, unsigned char &buffer)
Returns the current value of an FPGA register.
SENSOR_RESULT getIlluminationControlRegister (unsigned char &illumination)
Gets the value of the "Illumination Control" FPGA register.
SENSOR_RESULT getMaxTemperatureRegister (unsigned char &temperature)
Gets the value of the "Max Temperature" FPGA register.
SENSOR_RESULT getModeRegister (unsigned char &mode)
Gets the value of the "Mode" FPGA register.
SENSOR_RESULT getPicturePeriodRegister (unsigned char &period)
Gets the value of the "Picture Period" FPGA register.
SENSOR_RESULT getSaturationRegister (unsigned short &saturation)
Gets the value of the "Saturation" FPGA register pair.
SENSOR_RESULT getStatusBitSelectionRegister (unsigned char &selection)
Gets the value of the "Status Bit Selection" FPGA register.
SENSOR_RESULT getStatusRegister (unsigned char &status)
Gets the value of the "Status" FPGA register.
SENSOR_RESULT getThresholdRegister (unsigned short &threshold)
Gets the value of the "Threshold" FPGA register pair.
SENSOR_RESULT setCommandRegister (const unsigned char command)
Sets the value of the "Command" FPGA register.
SENSOR_RESULT setDebugModeRegister (const unsigned char debug)
Sets the value of the "Debug Mode" FPGA register.
SENSOR_RESULT setDistanceOffsetRegister (const unsigned char offset)
Sets the value of the "Distance Offset" FPGA register.
SENSOR_RESULT setExposureTimeRegister (unsigned char exposure)
Sets the value of the "Exposure Time" FPGA register.
SENSOR_RESULT setFpgaRegister (const FpgaRegister registr, const unsigned char value)
Sets the value of an FPGA register.
SENSOR_RESULT setIlluminationControlRegister (const unsigned char illumination)
Sets the value of the "Illumination Control" FPGA register.
SENSOR_RESULT setMaxTemperatureRegister (const unsigned char temperature)
Sets the value of the "Max Temperature" FPGA register.
SENSOR_RESULT setModeRegister (const unsigned char mode)
Sets the value of the "Mode" FPGA register.
SENSOR_RESULT setPicturePeriodRegister (unsigned char period)
Sets the value of the "Picture Period" FPGA register.
SENSOR_RESULT setSaturationRegister (const unsigned short saturation)
Sets the value of the "Saturation" FPGA register pair.
SENSOR_RESULT setStatusBitSelectionRegister (const unsigned char selection)
Sets the value of the "Status Bit Selection" FPGA register.
SENSOR_RESULT setThresholdRegister (const unsigned short threshold)
Sets the value of the "Threshold" FPGA register pair.
SENSOR_RESULT uploadFullSingleUffMoviePicture (unsigned long picNumber, unsigned long long timestamp, unsigned short *picture, const char numberOfDoors, const iris::uip::door_status *doorState, bool ledOn)
Uploads a full single Picture into the sensor.
SENSOR_RESULT uploadUffMovie (const std::string &filename, int &picCount)
Uploads an UFF movie into the sensor for simulation.
virtual ~FpgaController ()
Destructor.
Public Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _legacyGetDeviceInfo (unsigned short group, unsigned short param, char *buffer)
Retrieves a device feature.
SENSOR_RESULT activateConfiguration (void)
activates a configuration that is already in RAM
SENSOR_RESULT captureDevice (char *application)
Captures the sensor: Marks the device as captured, which can be queried by getCaptureState.
SENSOR_RESULT checkSupportForMessage (const unsigned char command, const unsigned char version, const unsigned char subCommand, bool &isSupported)
checkSupportForMessage Checks if the sensor can respond to the specified message.
SENSOR_RESULT describeParameter (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info, const bool includeName=false)
describeParameter Returns ParameterInfo for the specified parameter which contains the type and value range.
SENSOR_RESULT determineTimeoutParameters (void)
Measures the timeout params (offset and factor) by doing some comnmunication tests.
Dist500Base (iris::drivers::Sensor &sensor)
Constructor.
UipMessage * doSendAndGetApplReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * doSendAndGetReply (int level, UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack or application level message and receives one or more replies.
UipMessage * doSendAndGetServiceReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a service level message and receives one or more replies.
UipMessage * doSendAndGetStackReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT echoTest (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Performs an echo test (pings the sensor)
SENSOR_RESULT getCaptureState (char *applicationBuffer, int maxLen)
Returns the capture state.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, unsigned short &len, bool stackLevel=false)
Reads a configuration parameter.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, bool stackLevel=false)
Reads a configuration parameter from RAM of the sensor (not from flash).
virtual void getConnectionName (char *buffer)
Returns a description for the connection.
virtual void getLocalConnectionName (char *buffer)
Returns an identifier string for local connection (eg IP:port); Currently returns a fixed dummy string.
virtual void getName (char *nameBuffer, int maxLen)
Returns a description for the sensor (ConnectionName + @ + UipAddress)
SENSOR_RESULT getParameterGroupIds (IdSet &groupIds)
Retrieves a set of existing group ids.
SENSOR_RESULT getParameterGroups (ParameterGroups &groups)
Retrieves a map (ParameterGroups) of group ids to group name.
SENSOR_RESULT getParameterIds (const unsigned short groupId, IdSet &paramIds)
SENSOR_RESULT getParameterInfos (const unsigned short groupId, ParameterInfos &infos, const bool includeNames=false)
SENSOR_RESULT getParameterName (const unsigned short groupId, const unsigned short paramId, std::string &paramName)
getParameterName Returns only the name of the specified parameter
iris::drivers::Sensor & getSensor (void)
Returns the associated Sensor instance (from Driver)
unsigned char getUipAddress (void)
Returns the UIP address (integer between 1-255).
SENSOR_RESULT getWorkingMode (iris::uip::working_mode &mode)
Retrieves the sensor working mode (iris::uip::working_mode).
SENSOR_RESULT listAllSupportedMessages (MessageTypeDefinitionList &buffer)
listAllSupportedMessages lists all messages the sensor can respond to.
SENSOR_RESULT lockImmanentData (void)
lockImmanentData
SENSOR_RESULT pingNeighbour (const unsigned char neighbourAddress, const unsigned short payloadLen, const unsigned short repetitions, const unsigned short timeoutMs, unsigned short &successCount, unsigned short &averageTimeMs)
Asks a sensor to ping one of its neighbours (same FA) for a given number of repetitions.
SENSOR_RESULT pingSensor (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Pings a sensor.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT releaseDevice (void)
Releases ("uncaptures") the sensor.
void resetTimeoutParameters (void)
Resets the timeout params to the default values (offset 0, factor 1.0)
SENSOR_RESULT restoreConfigurationFromFlash (void)
Copies the configuration from flash memory to RAM.
SENSOR_RESULT saveConfigurationToFlash (void)
Copies the configuration from RAM to flash memory.
UipMessage * sendAndGetApplReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * sendAndGetServiceReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
UipMessage * sendAndGetStackReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT sendUipCommand (char type, unsigned char version, char command, unsigned short payloadLen, char *payload, unsigned int timeoutMs, char &replyType, unsigned char &replyVersion, char &replyCommand, unsigned short &replyPayloadLen, char *replyPayloadBuffer)
Sends a "free" UIP command to the sensor and waits for the reply.
SENSOR_RESULT setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel=false)
Sets a configuration parameter in the sensor's RAM (not in the flash).
SENSOR_RESULT setConfigurationParameterIfKnown (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool &paramWasUnknown, bool stackLevel=false)
Like setConfigurationParameter but only if that parameter is known.
void setUipAddress (unsigned char)
setUipAddress Sets a new UIP address for communication with this sensor.
void setUipTimeout (const int timeoutMs)
Sets timeout used for UIP send and get reply methods (whereafter usually a retry is performed).
SENSOR_RESULT setWorkingMode (const iris::uip::working_mode mode)
Sets the sensor working mode.
SENSOR_RESULT unlockImmanentData (void)
unlockImmanentData
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
virtual ~Dist500Base ()
Destructor.
Protected Member Functions
SENSOR_RESULT activateMovie (void)
Activates the movie by resetting the simulation.
SENSOR_RESULT prepareMovieUpload (int &picCount)
Prepares the upload of an UFF movie for simulation.
SENSOR_RESULT uploadMoviePicture (unsigned char subPicNo, unsigned char subPicTotal, iris::uip::sub_pic_type subPicType, unsigned long picNumber, unsigned long long timestamp, unsigned short *pixels, const char numberOfDoors, const iris::uip::door_status *doorState, bool ledOn)
Uploads a movie (sub-)picture to the sensor.
Protected Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos, ReceptionFlags &receivedParameters, iris::uip::ushort &expectedCount)
SENSOR_RESULT _legacyReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _optimizedReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings, const bool sendEmptyIfDefault, ReceptionFlags &receivedParams, iris::uip::ushort &expectedCount)
This is internally used in optimized sensor configuration readouts.
SENSOR_RESULT _setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel, bool ignoreUnknownParamErrors, bool &paramWasUnknown)
SENSOR_RESULT _writeConfiguration (iris::configuration::Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
bool automaticRetriesSupported (UipMessage *message)
Checks if automatic retries are currently supported for the specified message.
SENSOR_RESULT describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos)
describeAllGroupParametersWithoutNames Gets descriptions (GroupParameterInfos) of parameters within the specified configuration group.
SENSOR_RESULT describeParameterWithoutName (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info)
describeParameterWithoutName Gets type and value range information for the specified parameter.
SENSOR_RESULT getGroupName (const unsigned short groupId, std::string &groupName)
getGroupName Gets the name of the specified configuration group.
float getTimeoutFactor (void) const
Returns the timeout factor.
unsigned long getTimeoutOffset (void) const
Returns the timeout offset.
void initializeNoRetryMessageHashSet (void)
These are the messages that are not automatically repeated in case no reply arrives.
SENSOR_RESULT readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings=true, const bool sendEmptyIfDefault=true)
Used for sensor configuration readout, returns a map with parameter values for the specified configuration group.
void registerNoRetryMessage (unsigned char type, unsigned char version, unsigned char command)
Makes the specified message not be automatically resent if no replay arrives.
SENSOR_RESULT requestKeyPuzzle (unsigned short &puzzleLen, unsigned char *puzzleBuffer)
SENSOR_RESULT unlockImmanentData (const unsigned short keyLen, const unsigned char *key)
unlockImmanentData
Additional Inherited Members
Static Public Member Functions inherited from iris::dist500::Dist500Base
static void disableAutomaticRetries (void)
disables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
static void enableAutomaticRetries (void)
enables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
Protected Types inherited from iris::dist500::Dist500Base
typedef std::map< unsigned short, ParameterInfo > GroupParameterInfos
typedef std::map< unsigned short, ParameterValue > GroupParameterValues
typedef std::set< int > NoRetryMessageHashSet
typedef std::bitset< 1024 > ReceptionFlags
Static Protected Member Functions inherited from iris::dist500::Dist500Base
static void handleSpontaneousWorkingModeMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for U 2.0.
Protected Attributes inherited from iris::dist500::Dist500Base
SpontaneousHandlers handlers
Handler manger for spontaeous UIP messages (sub-command *)
NoRetryMessageHashSet noRetryMessageHashSet
iris::drivers::Sensor & sensor
Reference to associatee driver's Sensor object.
float timeoutFactor
Factor to applied to standard timeouts.
unsigned long timeoutOffset
Constant offset to be applied to standard timeouts.
unsigned char uipAddress
UIP address of sensor.
int uipTimeout
Timeout in ms used for UIP send and get reply methods.
Static Protected Attributes inherited from iris::dist500::Dist500Base
static bool automaticRetriesDisabled = false
Detailed Description
Implements FPGA related functions within the DIST500 firmware.
Member Enumeration Documentation
enum iris::dist500::FpgaController::FpgaRegister
FPGA register number definitions.
Enumerator
CommandRegister
Command register (0)
StatusRegister
Status register (1)
ModeRegister
Mode register (2)
FirmwareRegister
Firmware register (3)
ThresholdLowRegister
Threshold (low) register (4)
ThresholdHighRegister
Threshold (high) register (5)
SaturationLowRegister
Saturation (low) register (6)
SaturationHighRegister
Saturation (high) register (7)
DistanceOffsetRegister
Distance offset register (8)
ExposureTimeRegister
Exposure time register (9)
MaxTemperatureRegister
Maximum temperature register (10)
CurrentTemperatureRegister
Current temperature register (11)
StatusBitSelectionRegister
Status bit selection register (12)
PicturePeriodRegister
Picture period register (13)
IlluminationControlRegister
Illumination control register (14)
DebugModeRegister
Debug mode register (31)
Constructor & Destructor Documentation
iris::dist500::FpgaController::FpgaController (iris::drivers::Sensor & sensor)
Constructor.
Parameters
sensor Sensor reference from driver framework
Member Function Documentation
SENSOR_RESULT iris::dist500::FpgaController::activateMovie (void) protected
Activates the movie by resetting the simulation.
Returns
Operation result
Deprecated:
The movie memory is disabled in current firmware. Simulation is now performed frame-by-frame.
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
Referenced by uploadUffMovie().
SENSOR_RESULT iris::dist500::FpgaController::getCurrentTemperatureRegister (unsigned char & temperature)
Gets the value of the "Current Temperature" FPGA register.
Parameters
temperature Buffer for current value
Returns
Operation result
References CurrentTemperatureRegister, and getFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::getDebugModeRegister (unsigned char & debug)
Gets the value of the "Debug Mode" FPGA register.
Parameters
debug Buffer for current value
Returns
Operation result
References DebugModeRegister, and getFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::getDistanceOffsetRegister (unsigned char & offset)
Gets the value of the "Distance Offset" FPGA register.
Parameters
offset Buffer for current value
Returns
Operation result
References DistanceOffsetRegister, and getFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::getExposureTimeRegister (unsigned char & exposure)
Gets the value of the "Exposure Time" FPGA register.
Parameters
exposure Buffer for current value
Returns
Operation result
References ExposureTimeRegister, and getFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::getFirmwareRegister (unsigned char & version)
Gets the value of the "Firmware" FPGA register.
Parameters
version Buffer for value
Returns
Operation result
References FirmwareRegister, and getFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::getFpgaRegister (const FpgaRegister registr, unsigned char & buffer)
Returns the current value of an FPGA register.
Parameters
registr
buffer
Returns
Operation result
Note
"registr" is used because "register" is a C++ keyword
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::uip::_reg::registerValue, iris::dist500::Dist500Base::sendAndGetApplReply(), and iris::dist500::Dist500Base::uipAddress.
Referenced by getCurrentTemperatureRegister(), getDebugModeRegister(), getDistanceOffsetRegister(), getExposureTimeRegister(), getFirmwareRegister(), getIlluminationControlRegister(), getMaxTemperatureRegister(), getModeRegister(), getPicturePeriodRegister(), getSaturationRegister(), getStatusBitSelectionRegister(), getStatusRegister(), and getThresholdRegister().
SENSOR_RESULT iris::dist500::FpgaController::getIlluminationControlRegister (unsigned char & illumination)
Gets the value of the "Illumination Control" FPGA register.
Parameters
illumination Buffer for current value
Returns
Operation result
References getFpgaRegister(), and IlluminationControlRegister.
SENSOR_RESULT iris::dist500::FpgaController::getMaxTemperatureRegister (unsigned char & temperature)
Gets the value of the "Max Temperature" FPGA register.
Parameters
temperature Buffer for current value
Returns
Operation result
References getFpgaRegister(), and MaxTemperatureRegister.
SENSOR_RESULT iris::dist500::FpgaController::getModeRegister (unsigned char & mode)
Gets the value of the "Mode" FPGA register.
Parameters
mode Buffer for current value
Returns
Operation result
References getFpgaRegister(), and ModeRegister.
SENSOR_RESULT iris::dist500::FpgaController::getPicturePeriodRegister (unsigned char & period)
Gets the value of the "Picture Period" FPGA register.
Parameters
period Buffer for current value
Returns
Operation result
References getFpgaRegister(), and PicturePeriodRegister.
SENSOR_RESULT iris::dist500::FpgaController::getSaturationRegister (unsigned short & saturation)
Gets the value of the "Saturation" FPGA register pair.
Parameters
saturation Buffer for current value
Returns
Operation result
References getFpgaRegister(), iris::dist500::OPERATION_PASSED, SaturationHighRegister, and SaturationLowRegister.
SENSOR_RESULT iris::dist500::FpgaController::getStatusBitSelectionRegister (unsigned char & selection)
Gets the value of the "Status Bit Selection" FPGA register.
Parameters
selection Buffer for current value
Returns
Operation result
References getFpgaRegister(), and StatusBitSelectionRegister.
SENSOR_RESULT iris::dist500::FpgaController::getStatusRegister (unsigned char & status)
Gets the value of the "Status" FPGA register.
Parameters
status Buffer for current value
Returns
Operation result
References getFpgaRegister(), and StatusRegister.
Referenced by iris::dist500::Dist500::isPictureAcquisitionRunning().
SENSOR_RESULT iris::dist500::FpgaController::getThresholdRegister (unsigned short & threshold)
Gets the value of the "Threshold" FPGA register pair.
Parameters
threshold Buffer for current value
Returns
Operation result
References getFpgaRegister(), iris::dist500::OPERATION_PASSED, ThresholdHighRegister, and ThresholdLowRegister.
SENSOR_RESULT iris::dist500::FpgaController::prepareMovieUpload (int & picCount) protected
Prepares the upload of an UFF movie for simulation.
Parameters
picCount Number of pictures
Returns
Operation result
Deprecated:
The movie memory is disabled in current firmware. Simulation is now performed frame-by-frame.
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
Referenced by uploadUffMovie().
SENSOR_RESULT iris::dist500::FpgaController::setCommandRegister (const unsigned char command)
Sets the value of the "Command" FPGA register.
Parameters
command New value
Returns
Operation result
References CommandRegister, and setFpgaRegister().
Referenced by iris::dist500::Dist500::startPictureAcquisision(), and iris::dist500::Dist500::stopPictureAcquisision().
SENSOR_RESULT iris::dist500::FpgaController::setDebugModeRegister (const unsigned char debug)
Sets the value of the "Debug Mode" FPGA register.
Parameters
debug New value
Returns
Operation result
References DebugModeRegister, and setFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::setDistanceOffsetRegister (const unsigned char offset)
Sets the value of the "Distance Offset" FPGA register.
Parameters
offset New value
Returns
Operation result
References DistanceOffsetRegister, and setFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::setExposureTimeRegister (unsigned char exposure)
Sets the value of the "Exposure Time" FPGA register.
Parameters
exposure New value
Returns
Operation result
References ExposureTimeRegister, and setFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::setFpgaRegister (const FpgaRegister registr, const unsigned char value)
Sets the value of an FPGA register.
Parameters
registr
value
Returns
Operation result
Note
"registr" is used because "register" is a C++ keyword
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::uip::_reg::registerNumber, iris::uip::_reg::registerValue, iris::dist500::Dist500Base::sendAndGetApplReply(), and iris::dist500::Dist500Base::uipAddress.
Referenced by setCommandRegister(), setDebugModeRegister(), setDistanceOffsetRegister(), setExposureTimeRegister(), setIlluminationControlRegister(), setMaxTemperatureRegister(), setModeRegister(), setPicturePeriodRegister(), setSaturationRegister(), setStatusBitSelectionRegister(), and setThresholdRegister().
SENSOR_RESULT iris::dist500::FpgaController::setIlluminationControlRegister (const unsigned char illumination)
Sets the value of the "Illumination Control" FPGA register.
Parameters
illumination New value
Returns
Operation result
References IlluminationControlRegister, and setFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::setMaxTemperatureRegister (const unsigned char temperature)
Sets the value of the "Max Temperature" FPGA register.
Returns
Operation result
References MaxTemperatureRegister, and setFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::setModeRegister (const unsigned char mode)
Sets the value of the "Mode" FPGA register.
Parameters
mode New value
Returns
Operation result
References ModeRegister, and setFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::setPicturePeriodRegister (unsigned char period)
Sets the value of the "Picture Period" FPGA register.
Parameters
period New value
Returns
Operation result
References PicturePeriodRegister, and setFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::setSaturationRegister (const unsigned short saturation)
Sets the value of the "Saturation" FPGA register pair.
Parameters
saturation New value
Returns
Operation result
References iris::dist500::OPERATION_PASSED, SaturationHighRegister, SaturationLowRegister, and setFpgaRegister().
SENSOR_RESULT iris::dist500::FpgaController::setStatusBitSelectionRegister (const unsigned char selection)
Sets the value of the "Status Bit Selection" FPGA register.
Parameters
selection New value
Returns
Operation result
References setFpgaRegister(), and StatusBitSelectionRegister.
SENSOR_RESULT iris::dist500::FpgaController::setThresholdRegister (const unsigned short threshold)
Sets the value of the "Threshold" FPGA register pair.
Parameters
threshold New value
Returns
Operation result
References iris::dist500::OPERATION_PASSED, setFpgaRegister(), ThresholdHighRegister, and ThresholdLowRegister.
SENSOR_RESULT iris::dist500::FpgaController::uploadFullSingleUffMoviePicture (unsigned long picNumber, unsigned long long timestamp, unsigned short * picture, const char numberOfDoors, const iris::uip::door_status * doorState, bool ledOn)
Uploads a full single Picture into the sensor.
Parameters
picNumber
timestamp
picture
Returns
References iris::uip::amplitude, iris::uip::distance, iris::dist500::OPERATION_PASSED, and uploadMoviePicture().
SENSOR_RESULT iris::dist500::FpgaController::uploadMoviePicture (unsigned char subPicNo, unsigned char subPicTotal, iris::uip::sub_pic_type subPicType, unsigned long picNumber, unsigned long long timestamp, unsigned short * pixels, const char numberOfDoors, const iris::uip::door_status * doorState, bool ledOn) protected
Uploads a movie (sub-)picture to the sensor.
Parameters
subPicNo Number of current sub-picture (1-based)
subPicTotal Total sub-pics per cycle
subPicType Type of sub-picture (D: distance, A: amplitude)
picNumber Picture number
timestamp Timestamp
pixels Pointer to picture data
Returns
Operation result
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
Referenced by uploadFullSingleUffMoviePicture(), and uploadUffMovie().
SENSOR_RESULT iris::dist500::FpgaController::uploadUffMovie (const std::string & filename, int & picCount)
Uploads an UFF movie into the sensor for simulation.
Parameters
filename Name of UFF file
picCount Number of uploaded pictures (may be less than the picture count of the UFF file if simulation RAM is too small)
Returns
Operation result
Deprecated:
The movie memory is disabled in current firmware. Simulation is now performed frame-by-frame.
References activateMovie(), iris::uip::amplitude, iris::uff::UffDecoder::close(), iris::uip::distance, iris::uip::_door_status::doorAddress, iris::uip::_door_status::functionAreaAddress, iris::uff::UffDecoder::getPictureCount(), iris::dist500::Pixels1000::linear, iris::uff::UffDecoder::open(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_PASSED, prepareMovieUpload(), iris::uff::UffDecoder::readPictureAndData(), uploadMoviePicture(), and iris::dist500::Pic::wholePicture.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/FpgaController.h
SensorAPI/implementation/iris/dist500/FpgaController.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !