IRMA MATRIX SDK: iris::drivers::DriverManager Class Reference
iris::drivers::DriverManager Class Reference
Manages a list of loaded Driver instances.
#include <DriverManager.h>
Public Types
typedef std::vector< Driver * > DriverList
Contains the list of loaded drivers.
Public Member Functions
void createAndActivateDefaultDrivers (const bool noIcefPriority=false, const bool noCanActivation=false)
Activates default drivers (currently ICEF, UDP and CAN) if possible.
Driver & getDriverFor (const std::string &mnemonic)
Returns a reference to the driver which handles the given URL prefix.
iris::synchronization::Mutex & getExclusionGroupMutex (const Driver &driver)
DriverList getKnownDrivers (void)
Retrieves a list of the currently known drivers.
Sensor & getSensorFor (const std::string &url)
Returns a Sensor object for the given URL.
bool isDynamic (Driver &driver)
Checks whether the driver was loaded from a driver library.
bool isMnemonicKnown (const std::string &mnemonic) const
Checks whether any driver is loaded that handles the given URL prefix.
bool isUrlValid (const std::string &url)
Checks whether the given URL is valid.
bool isValid (const Driver &driver)
Checks whether the given driver is valid.
Driver & loadDriver (const std::string &driverLibName, const bool activate=true)
Loads the given driver.
DriverList loadDrivers (const std::string &driverLibPath, bool activate=true, const bool recursive=true)
Loads all drivers found in the given directory.
std::string makeUrl (const std::string &urlPrefix, const std::string &addr) const
Creates a full URL string from the given components.
void registerDriver (Driver &driver, const bool activate=true)
Adds given driver to the map of known drivers.
Driver::AddressList scanAllDevices (const bool enable=false)
Performs sensor address scans for all known drivers.
Driver::AddressList scanDriverDevices (const std::string &mnemonic, const bool enable=false, void *userData=0, Driver::SCAN_CALLBACK callback=0)
Performs sensor address scan for driver given by URL prefix.
bool shutdownAllDrivers (const bool suppressExceptions=false)
void splitAddress (const std::string &addr, std::string &addrCommon, std::string &addrUip) const
splitAddress
void splitUrl (const std::string &url, std::string &urlPrefix, std::string &addr) const
Splits up a full URL into its components.
void unloadDriver (Driver &driver)
Unloads the given driver and frees its resources.
void unregisterDriver (Driver &driver, const bool deactivate=true)
Removes given driver from the map of known drivers.
Static Public Member Functions
static DriverManager & getInstance (void)
Returns the global DriverManager instance.
Static Public Attributes
static const int magicNumber = 0x53495249
Constant to check dynamic library against iris driver interface.
Protected Types
typedef Driver *(* CreateInstanceFunc) (void)
Standard C function signature for callback function inside dynamic library which implements a Driver instance factory.
typedef std::map< Driver *, iris::synchronization::Mutex * > DriverMutexMap
typedef std::map< std::string, bool > DynamicDrivers
typedef std::map< std::string, iris::synchronization::Mutex * > GroupMutexMap
typedef std::map< std::string, Driver * > KnownDrivers
Maps URL prefixes to Driver instances.
typedef int(* MagicNumberFunc) (void)
Standard C funtion signature for callback function inside dynamic library which need to return the correct magic number.
Protected Member Functions
DriverManager ()
Constructor.
bool isDriver (const iris::sharedlibs::SharedLib &lib, CreateInstanceFunc &cif)
Checks if the given SharedLib instance represents a driver library.
virtual ~DriverManager ()
Destructor.
Protected Attributes
DriverMutexMap driverMutexes
DynamicDrivers dynamicDrivers
GroupMutexMap groupMutexes
KnownDrivers knownDrivers
Map of loaded drivers.
iris::synchronization::Mutex mutex
Mutex to synchronize access to knownDrivers member.
Static Protected Attributes
static DriverManager * instance = 0
Global SharedLibManger instance.
static const std::string urlSeparator = "://"
String constant for the URL separator "://".
Detailed Description
Manages a list of loaded Driver instances.
Member Typedef Documentation
typedef int(* iris::drivers::DriverManager::MagicNumberFunc) (void) protected
Standard C funtion signature for callback function inside dynamic library which need to return the correct magic number.
See also
magicNumber
Constructor & Destructor Documentation
iris::drivers::DriverManager::DriverManager () protected
Constructor.
Note
Non-public to enforce singleton
iris::drivers::DriverManager::~DriverManager () protected virtual
Destructor.
Note
Non-public to enforce singleton
Member Function Documentation
void iris::drivers::DriverManager::createAndActivateDefaultDrivers (const bool noIcefPriority = false, const bool noCanActivation = false)
Activates default drivers (currently ICEF, UDP and CAN) if possible.
If necessary static Driver instance is created and driver is registered
Parameters
noIcefPriority Flag controlling handling of UDP driver (true UDP driver is created and activated in addition to ICEF driver, false only ICEF driver is created and activated)
noCanActivation Flag controlling activation of CAN driver (true CAN driver is not activated, false CAN driver is activated
Exceptions
Exception if none of the default drivers could be activated
References iris::drivers::can::CanDriver::startupDriver(), and iris::drivers::Driver::startupDriver().
Driver & iris::drivers::DriverManager::getDriverFor (const std::string & mnemonic)
Returns a reference to the driver which handles the given URL prefix.
Parameters
mnemonic URL prefix (without :// separator)
Returns
Driver
Exceptions
Exception if no matching driver is loaded
Referenced by iris::dist500::updateSensorConnectionsViaBroadcast().
DriverManager & iris::drivers::DriverManager::getInstance (void) static
Returns the global DriverManager instance.
Returns
Reference to static instance
Note
Singleton pattern
Referenced by iris::drivers::Connection::getUrl(), and iris::dist500::updateSensorConnectionsViaBroadcast().
DriverManager::DriverList iris::drivers::DriverManager::getKnownDrivers (void)
Retrieves a list of the currently known drivers.
Returns
Driver list
Sensor & iris::drivers::DriverManager::getSensorFor (const std::string & url)
Returns a Sensor object for the given URL.
Parameters
url Full sensor URL
Returns
Sensor instance
Exceptions
Exception if no matching driver is loaded or if URL is invalid
Note
The given URL will automatically be enabled (and reset to its current enable state if something in case of failure)
References iris::drivers::Driver::disableAddress(), iris::drivers::Driver::enableAddress(), iris::drivers::Driver::getSensor(), and iris::drivers::Driver::isAddressEnabled().
Referenced by iris::dist500::updateSensorConnectionsViaBroadcast().
bool iris::drivers::DriverManager::isDriver (const iris::sharedlibs::SharedLib & lib, CreateInstanceFunc & cif) protected
Checks if the given SharedLib instance represents a driver library.
Tests for conformity with the iris driver interface
References iris::sharedlibs::SharedLib::getSymbolAddr().
bool iris::drivers::DriverManager::isDynamic (Driver & driver)
Checks whether the driver was loaded from a driver library.
Returns
true if driver was loaded from a driver library, false< otherwise
References iris::drivers::Driver::getUrlPrefix().
bool iris::drivers::DriverManager::isMnemonicKnown (const std::string & mnemonic) const
Checks whether any driver is loaded that handles the given URL prefix.
Parameters
mnemonic URL prefix (without :// separator)
Returns
true if a matching driver is loaded, false otherwise
bool iris::drivers::DriverManager::isUrlValid (const std::string & url)
Checks whether the given URL is valid.
Parameters
url Full sensor URL
Returns
true if URL is valid, false otherwise
References iris::drivers::Driver::isAddressValid().
bool iris::drivers::DriverManager::isValid (const Driver & driver)
Checks whether the given driver is valid.
Parameters
driver Driver to be checked
Returns
true is valid, false otherwise
References iris::drivers::Driver::getUrlPrefix().
Driver & iris::drivers::DriverManager::loadDriver (const std::string & driverLibName, const bool activate = true)
Loads the given driver.
Parameters
driverLibName File name of the driver library
activate Activation flag (true results in activation after loading, false only loads the driver)
Returns
Driver instance
Exceptions
Exception if driver cannot be loaded
References iris::drivers::Driver::getUrlPrefix(), iris::sharedlibs::SharedLibManager::loadLibrary(), iris::drivers::Driver::startupDriver(), and iris::sharedlibs::SharedLibManager::unloadLibrary().
DriverManager::DriverList iris::drivers::DriverManager::loadDrivers (const std::string & driverLibPath, bool activate = true, const bool recursive = true)
Loads all drivers found in the given directory.
Drivers in subdirectories can be included if desired
Parameters
driverLibPath Path containing the driver libraries
activate Activation flag (true results in activation after loading, false only loads the driver)
recursive Flag indicating if sub-directories should be searched as well
Returns
List of successfully loaded drivers
References iris::drivers::Driver::startupDriver().
std::string iris::drivers::DriverManager::makeUrl (const std::string & urlPrefix, const std::string & addr) const
Creates a full URL string from the given components.
Parameters
urlPrefix URL prefix (without :// separator)
addr Sensor address (without :// separator)
Returns
Full URL string (prefix://address)
Referenced by iris::drivers::Connection::getUrl(), and iris::dist500::updateSensorConnectionsViaBroadcast().
void iris::drivers::DriverManager::registerDriver (Driver & driver, const bool activate = true)
Adds given driver to the map of known drivers.
Parameters
driver Driver instance
activate Activation flag (true results in activation after registering, false only registers the driver)
Exceptions
Exception if driver is already registered or driver handles an already registered URL prefix
References iris::drivers::Driver::getUrlPrefix(), and iris::drivers::Driver::startupDriver().
Driver::AddressList iris::drivers::DriverManager::scanAllDevices (const bool enable = false)
Performs sensor address scans for all known drivers.
Callback and related user-defined parameter not used
Parameters
enable Communication enable flag (true enables all found addresses for subsequent communication, false disables all found addresses for subsequent communication)
References iris::drivers::Driver::enableAddresses(), iris::drivers::Driver::getUrlPrefix(), iris::drivers::Driver::isActive(), and iris::drivers::Driver::performAddressScan().
Driver::AddressList iris::drivers::DriverManager::scanDriverDevices (const std::string & mnemonic, const bool enable = false, void * userData = 0, Driver::SCAN_CALLBACK callback = 0)
Performs sensor address scan for driver given by URL prefix.
Parameters
mnemonic URL prefix (without :// separator)
enable Communication enable flag (true enables all found addresses for subsequent communication, false disables all found addresses for subsequent communication)
userData User-defined additional parameter for callback
callback Callback for sensor address scan
References iris::drivers::Driver::enableAddresses(), and iris::drivers::Driver::performAddressScan().
void iris::drivers::DriverManager::splitAddress (const std::string & addr, std::string & addrCommon, std::string & addrUip) const
splitAddress
Parameters
addr
addrCommon
addrUip
Referenced by iris::dist500::updateSensorConnectionsViaBroadcast().
void iris::drivers::DriverManager::splitUrl (const std::string & url, std::string & urlPrefix, std::string & addr) const
Splits up a full URL into its components.
Parameters
url URL to be split (prefix://address)
urlPrefix String receiving the URL prefix (without :// separator)
addr String receiving the sensor address (without :// separator)
Exceptions
Exception if URL is invalid
Referenced by iris::dist500::updateSensorConnectionsViaBroadcast().
void iris::drivers::DriverManager::unloadDriver (Driver & driver)
Unloads the given driver and frees its resources.
The Driver instance itself is also freed
Parameters
driver Driver to be unloaded
Note
References to the driver are invalid after that operation
References iris::drivers::Driver::getUrlPrefix(), and iris::drivers::Driver::shutdownDriver().
void iris::drivers::DriverManager::unregisterDriver (Driver & driver, const bool deactivate = true)
Removes given driver from the map of known drivers.
Parameters
driver Driver instance
deactivate Deactivation flag (true results in deactivation after unregistering, false only unregisters the driver)
Exceptions
Exception if driver matches by mnemonic (URL prefix), but the instance is different
References iris::drivers::Driver::getUrlPrefix(), and iris::drivers::Driver::shutdownDriver().
Member Data Documentation
DriverManager * iris::drivers::DriverManager::instance = 0 static protected
Global SharedLibManger instance.
Note
Singleton
const int iris::drivers::DriverManager::magicNumber = 0x53495249 static
Constant to check dynamic library against iris driver interface.
Equals 0x53495249 which reads "iris" in little endian notation
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/drivers/DriverManager.h
SensorAPI/implementation/iris/drivers/DriverManager.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !