IRMA MATRIX SDK: iris::drivers::can::CanDriver Class Reference
iris::drivers::can::CanDriver Class Reference
Implements a CAN driver.
#include <CanDriver.h>
Classes
class CanErrorCondition
struct CanFrame
class Recombiner
Public Types
typedef void(* CAN_IRMA_DEBUG_CALLBACK) (void *userData, const CanFrame &frame, const int code, const int dest, const int addr)
typedef std::list< CanFrame * > CanFrameList
enum FrameType { DataFrame, RemoteFrame, ErrorFrame }
typedef CanDriverImplementation *(* IMPLEMENTATION_FACTORY_FUNCTION) (CanDriver &driver)
typedef std::map< std::string, IMPLEMENTATION_FACTORY_FUNCTION > ImplementationFactoryMap
typedef void(* RAW_CAN_DEBUG_CALLBACK) (void *userData, const CanFrame &frame)
typedef void(* RAW_CAN_ERROR_CALLBACK) (void *userData, const CanErrorCondition &condition)
typedef std::map< int, Recombiner * > RecombinerMap
typedef void(* UIP_CAN_IRMA_DEBUG_CALLBACK) (void *userData, const CanFrame &frame, const UipCanIrmaRecombinerStatus status)
enum UipCanIrmaRecombinerStatus {
FrameTooShortError, LastFrameIncomplete, InvalidPayloadLen, UnexpectedSubFrameNumber,
FrameCountOrTotalLenMismatch, SubFrameProcessed, UipFrameCompleted
}
Public Types inherited from iris::drivers::Driver
typedef std::list< std::string > AddressList
Holds a list of sensor addresses.
typedef std::map< std::string, Connection * > ConnectionMap
Maps addresses to Connection objects.
typedef std::multimap< std::string, Connection * > ConnectionMultiMap
Maps main-addresses to Connection objects.
typedef void(* DEBUG_CALLBACK) (void *userData, const int level, const std::string &addr, const UipMessage *msg)
typedef iris::dist500::Dist500List Dist500List
typedef std::set< std::string > OptionNameSet
typedef void(* SCAN_CALLBACK) (void *userData, const Driver &driver, const std::string &url)
Callback for sensor address scan.
typedef std::list< iris::dist500::SensorGroup * > SensorGroupList
Public Member Functions
CanDriver ()
Constructor.
void canErrorConditionCallback (const CanErrorCondition &condition)
void canReceptionCallback (const CanFrame &frame)
void clearCanIrmaDebugListener (void)
void clearRawCanDebugListener (void)
void clearRawCanErrorListener (void)
void clearUipCanIrmaDebugListener (void)
AddressList performAddressScan (void *userData=0, SCAN_CALLBACK callback=0) const
Returns the list of all sensors addresses that can currently be found.
void sendBroadcastMessage (const int level, const UipMessage *message) const
Sends the given message in broadcast mode.
void sendMessage (const int level, const std::string &addr, const UipMessage *message) const
Sends the given message.
void sendMessage (const int level, const std::string &addr, const UipMessage *message, const bool broadcast) const
void setCanIrmaDebugListener (CAN_IRMA_DEBUG_CALLBACK listener, void *userData=0)
void setRawCanDebugListener (RAW_CAN_DEBUG_CALLBACK listener, void *userData=0)
void setRawCanErrorListener (RAW_CAN_ERROR_CALLBACK listener, void *userData=0)
void setUipCanIrmaDebugListener (UIP_CAN_IRMA_DEBUG_CALLBACK listener, void *userData=0)
void shutdownDriver (void)
Deinitializes the driver.
CanFrameList splitUipMessage (int level, const std::string &addr, UipMessage *uipMessage, const bool broadcast) const
void startupDriver (void)
Initializes the driver.
bool supportsParallelAccess (void) const
Indicates if parallel communication with several sensors is supported or not.
void uipReceptionCallback (const int level, const int addr, UipMessage *message)
virtual ~CanDriver ()
Destructor.
Public Member Functions inherited from iris::drivers::Driver
void clearDebugListener (void)
void disableAddress (const std::string &addr, bool keepSensor=false, bool keepConnection=false)
Disables the given address for subsequent communication.
void disableAddresses (const AddressList &addresses)
Disables all given addresses for subsequent communication.
void disableAllAddresses (void)
Disables all currently enabled addresses.
void enableAddress (const std::string &addr, Sensor *sensorInstance=0)
Enables the given address for subsequent communication.
void enableAddresses (const AddressList &addresses)
Enables all given addresses for subsequent communication.
iris::synchronization::Mutex & getAccessMutex (void)
AddressList getActiveAddresses (void)
Returns the list of currently active (enabled) addresses.
Connection & getConnection (const std::string &addr)
Returns a connection object for the given sensor address.
iris::synchronization::Mutex & getExclusionGroupMutex (void)
const std::string getName (void) const
Returns the driver name.
std::string getOption (const std::string &optionName, const bool useDefaultIfNotSet=true) const
std::string getOption (const std::string &optionName, const std::string &defaultValue) const
OptionNameSet getOptionNames (const bool onlySetOptions=false)
Sensor & getSensor (const std::string &addr)
Returns the associated Sensor instance.
const std::string getUrlPrefix (void) const
Returns the URL prefix.
const std::string getVersion (void) const
Returns the driver version.
bool isActive (void) const
Checks whether the driver is active or not.
bool isAddressEnabled (const std::string &addr) const
Checks whether the given address is currently enabled.
bool isAddressValid (const std::string &addr) const
Checks whether the given address is valid or not.
bool isOptionSet (const std::string &optionName) const
bool isOptionValid (const std::string &optionName, const std::string &optionValue) const
virtual void sendBroadcastMessage (const int level, const UipMessage *message) const
Sends the given message in broadcast mode.
virtual void sendMessage (const int level, const std::string &addr, const UipMessage *message) const
Sends the given message.
void setDebugListener (DEBUG_CALLBACK listener, void *userData=0)
void setOption (const std::string &optionName, const std::string &optionValue)
void setOptionDefault (const std::string &optionName)
bool supportsOption (const std::string &optionName) const
void unsetOption (const std::string &optionName)
Static Public Member Functions
static void registerCanDriverImplementation (const std::string &name, IMPLEMENTATION_FACTORY_FUNCTION factoryFunction)
Static Public Member Functions inherited from iris::drivers::Driver
static SensorGroupList groupSensors (const Dist500List sensors)
Public Attributes
bool canIrmaServicePc
boost::condition_variable event
CanDriverImplementation * implementation
RecombinerMap recombiners
bool scanInProgress
Flag indicating whether a device scan is active.
AddressList scanList
Holds a list containing the scanned sensor addresses.
bool started
Public Attributes inherited from iris::drivers::Driver
iris::synchronization::Mutex accessMutex
ConnectionMap activeConnections
Contains the map of currently active (enabled) addresses along with their corresponding Connection objects.
ConnectionMultiMap distinctConnections
Contains the map of currently active (enabled) main-addresses along with their corresponding Connection objects.
iris::synchronization::Mutex mutex
Static Public Attributes
static const std::string & BusSpeedOptionName
static const std::string & CanInterfaceOptionName
static const std::string & CanIrmaServicePcOptionName
static const std::string & ImplementationOptionName
Protected Attributes
CAN_IRMA_DEBUG_CALLBACK canIrmaDebugListener
void * canIrmaDebugListenerUserData
RAW_CAN_DEBUG_CALLBACK rawCanDebugListener
void * rawCanDebugListenerUserData
RAW_CAN_ERROR_CALLBACK rawCanErrorListener
void * rawCanErrorListenerUserData
UIP_CAN_IRMA_DEBUG_CALLBACK uipCanIrmaDebugListener
void * uipCanIrmaDebugListenerUserData
Protected Attributes inherited from iris::drivers::Driver
bool active
DEBUG_CALLBACK debugListener
void * debugListenerUserData
const std::string name
Descriptive name of the driver.
OptionDefaultsMap optionDefaults
OptionValuesMap options
OptionValidatorMap optionValidators
const boost::regex urlAddrRegEx
Regular expression to check for syntactical sensor addresses (without prefix and :// separator)
const std::string urlPrefix
Prefix for sensor URLs, without the :// separator.
const std::string version
Version string, eg 1.0.0.
Static Protected Attributes
static ImplementationFactoryMap implementationFactoryMap
Friends
class CanDriverImplementation
Additional Inherited Members
Protected Types inherited from iris::drivers::Driver
typedef std::map< std::string, std::string > OptionDefaultsMap
typedef std::map< std::string, OptionValidator * > OptionValidatorMap
typedef std::map< std::string, std::string > OptionValuesMap
Protected Member Functions inherited from iris::drivers::Driver
void checkOption (const std::string &optionName, const std::string &optionValue) const
void checkOptionName (const std::string optionName) const
virtual Connection * createConnection (const std::string &addr)
Creates a new Connection instance for the given address.
void dispatchMessage (const int level, const std::string &addr, const UipMessage *msg)
Dispatches an incoming message to the destination sensor.
Driver (const std::string &name, const std::string &urlPrefix, const std::string &version, const std::string &urlAddrRegEx)
Constructor.
void ensureValidAddress (const std::string &addr) const
Verifies the validity of the given address.
virtual std::string getExclusionGroupName (void) const
Connection * getInternalConnection (const std::string &addr)
void registerOption (const std::string &optionName, const std::string &defaultValue, OptionValidator *validator)
void removeOption (const std::string &optionName)
void setActive (void)
void setInactive (void)
virtual ~Driver ()
Destructor.
Detailed Description
Implements a CAN driver.
Member Function Documentation
iris::drivers::Driver::AddressList iris::drivers::can::CanDriver::performAddressScan (void * userData = 0, SCAN_CALLBACK callback = 0) const virtual
Returns the list of all sensors addresses that can currently be found.
Returns
Address list (without URL prefix and :// separator)
Reimplemented from iris::drivers::Driver.
References scanInProgress, scanList, and sendBroadcastMessage().
void iris::drivers::can::CanDriver::sendBroadcastMessage (const int level, const UipMessage * message) const
Sends the given message in broadcast mode.
Parameters
level UIP level (0..2)
message Message to be sent
References sendMessage().
Referenced by performAddressScan().
void iris::drivers::can::CanDriver::sendMessage (const int level, const std::string & addr, const UipMessage * message) const
Sends the given message.
Parameters
level UIP level (0..2)
addr Sensor address
message Message to be sent
Referenced by sendBroadcastMessage().
bool iris::drivers::can::CanDriver::supportsParallelAccess (void) const virtual
Indicates if parallel communication with several sensors is supported or not.
Returns
Parallel support flag
Reimplemented from iris::drivers::Driver.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/drivers/can/CanDriver.h
SensorAPI/implementation/iris/drivers/can/CanDriver.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !