IRMA MATRIX SDK: iris::drivers::Driver Class Reference
iris::drivers::Driver Class Reference
Represents a physical connection driver to communicate via UIP, eg on top of UDP or ICEF.
#include <Driver.h>
Classes
class ChoiceValidator
class DoubleValidator
class IntegerValidator
class IpAddressValidator
class IpNetworkValidator
class ListValidator
class OnOffOptionValidator
class OptionValidator
class RegExValidator
Public Types
typedef std::list< std::string > AddressList
Holds a list of sensor addresses.
typedef std::map< std::string, Connection * > ConnectionMap
Maps addresses to Connection objects.
typedef std::multimap< std::string, Connection * > ConnectionMultiMap
Maps main-addresses to Connection objects.
typedef void(* DEBUG_CALLBACK) (void *userData, const int level, const std::string &addr, const UipMessage *msg)
typedef iris::dist500::Dist500List Dist500List
typedef std::set< std::string > OptionNameSet
typedef void(* SCAN_CALLBACK) (void *userData, const Driver &driver, const std::string &url)
Callback for sensor address scan.
typedef std::list< iris::dist500::SensorGroup * > SensorGroupList
Public Member Functions
void clearDebugListener (void)
void disableAddress (const std::string &addr, bool keepSensor=false, bool keepConnection=false)
Disables the given address for subsequent communication.
void disableAddresses (const AddressList &addresses)
Disables all given addresses for subsequent communication.
void disableAllAddresses (void)
Disables all currently enabled addresses.
void enableAddress (const std::string &addr, Sensor *sensorInstance=0)
Enables the given address for subsequent communication.
void enableAddresses (const AddressList &addresses)
Enables all given addresses for subsequent communication.
iris::synchronization::Mutex & getAccessMutex (void)
AddressList getActiveAddresses (void)
Returns the list of currently active (enabled) addresses.
Connection & getConnection (const std::string &addr)
Returns a connection object for the given sensor address.
iris::synchronization::Mutex & getExclusionGroupMutex (void)
const std::string getName (void) const
Returns the driver name.
std::string getOption (const std::string &optionName, const bool useDefaultIfNotSet=true) const
std::string getOption (const std::string &optionName, const std::string &defaultValue) const
OptionNameSet getOptionNames (const bool onlySetOptions=false)
Sensor & getSensor (const std::string &addr)
Returns the associated Sensor instance.
const std::string getUrlPrefix (void) const
Returns the URL prefix.
const std::string getVersion (void) const
Returns the driver version.
bool isActive (void) const
Checks whether the driver is active or not.
bool isAddressEnabled (const std::string &addr) const
Checks whether the given address is currently enabled.
bool isAddressValid (const std::string &addr) const
Checks whether the given address is valid or not.
bool isOptionSet (const std::string &optionName) const
bool isOptionValid (const std::string &optionName, const std::string &optionValue) const
virtual AddressList performAddressScan (void *userData=0, SCAN_CALLBACK callback=0) const
Returns the list of all sensors addresses that can currently be found.
virtual void sendBroadcastMessage (const int level, const UipMessage *message) const
Sends the given message in broadcast mode.
virtual void sendMessage (const int level, const std::string &addr, const UipMessage *message) const
Sends the given message.
void setDebugListener (DEBUG_CALLBACK listener, void *userData=0)
void setOption (const std::string &optionName, const std::string &optionValue)
void setOptionDefault (const std::string &optionName)
virtual void shutdownDriver (void)
Deinitializes the driver.
virtual void startupDriver (void)
Initializes the driver.
bool supportsOption (const std::string &optionName) const
virtual bool supportsParallelAccess (void) const
Indicates if parallel communication with several sensors is supported or not.
void unsetOption (const std::string &optionName)
Static Public Member Functions
static SensorGroupList groupSensors (const Dist500List sensors)
Public Attributes
iris::synchronization::Mutex accessMutex
ConnectionMap activeConnections
Contains the map of currently active (enabled) addresses along with their corresponding Connection objects.
ConnectionMultiMap distinctConnections
Contains the map of currently active (enabled) main-addresses along with their corresponding Connection objects.
iris::synchronization::Mutex mutex
Protected Types
typedef std::map< std::string, std::string > OptionDefaultsMap
typedef std::map< std::string, OptionValidator * > OptionValidatorMap
typedef std::map< std::string, std::string > OptionValuesMap
Protected Member Functions
void checkOption (const std::string &optionName, const std::string &optionValue) const
void checkOptionName (const std::string optionName) const
virtual Connection * createConnection (const std::string &addr)
Creates a new Connection instance for the given address.
void dispatchMessage (const int level, const std::string &addr, const UipMessage *msg)
Dispatches an incoming message to the destination sensor.
Driver (const std::string &name, const std::string &urlPrefix, const std::string &version, const std::string &urlAddrRegEx)
Constructor.
void ensureValidAddress (const std::string &addr) const
Verifies the validity of the given address.
virtual std::string getExclusionGroupName (void) const
Connection * getInternalConnection (const std::string &addr)
void registerOption (const std::string &optionName, const std::string &defaultValue, OptionValidator *validator)
void removeOption (const std::string &optionName)
void setActive (void)
void setInactive (void)
virtual ~Driver ()
Destructor.
Protected Attributes
bool active
DEBUG_CALLBACK debugListener
void * debugListenerUserData
const std::string name
Descriptive name of the driver.
OptionDefaultsMap optionDefaults
OptionValuesMap options
OptionValidatorMap optionValidators
const boost::regex urlAddrRegEx
Regular expression to check for syntactical sensor addresses (without prefix and :// separator)
const std::string urlPrefix
Prefix for sensor URLs, without the :// separator.
const std::string version
Version string, eg 1.0.0.
Friends
class DriverManager
Detailed Description
Represents a physical connection driver to communicate via UIP, eg on top of UDP or ICEF.
Member Typedef Documentation
typedef void(* iris::drivers::Driver::SCAN_CALLBACK) (void *userData, const Driver &driver, const std::string &url)
Callback for sensor address scan.
Parameters
userData User-defined additional parameter for callback
driver Driver instance
url Full sensor URL
Constructor & Destructor Documentation
iris::drivers::Driver::Driver (const std::string & name, const std::string & urlPrefix, const std::string & version, const std::string & urlAddrRegEx) protected
Constructor.
Initializes a new driver instance with the given set
Member Function Documentation
Connection * iris::drivers::Driver::createConnection (const std::string & addr) protected virtual
Creates a new Connection instance for the given address.
Will usually be overloaded by concrete driver implementations to provide specialized Connection subclassed.
Parameters
addr Sensor address (without prefix and :// separator)
Returns
New Connection instance
Referenced by enableAddress().
void iris::drivers::Driver::disableAddress (const std::string & addr, bool keepSensor = false, bool keepConnection = false)
Disables the given address for subsequent communication.
Parameters
addr Address to be disabled (without URL prefix and :// separator)
keepSensor Prohibits deletion of the associated sensor instance.
keepConnection Prohibits deletion of the associated connection.
Exceptions
Exception if address is invalid
References activeConnections, distinctConnections, isAddressEnabled(), iris::drivers::Connection::unregisterAddressKeepSensor(), and iris::drivers::Connection::unregisterSensor().
Referenced by disableAddresses(), iris::drivers::DriverManager::getSensorFor(), and iris::dist500::updateSensorConnectionsViaBroadcast().
void iris::drivers::Driver::disableAddresses (const AddressList & addresses)
Disables all given addresses for subsequent communication.
Parameters
addresses List of addresses to be disabled (without URL prefix and :// separator)
Exceptions
Exception if any address in the list is invalid
References disableAddress(), and ensureValidAddress().
Referenced by disableAllAddresses().
void iris::drivers::Driver::dispatchMessage (const int level, const std::string & addr, const UipMessage * msg) protected
Dispatches an incoming message to the destination sensor.
Parameters
level UIP level (0..2)
addr Sensor address
msg Message to be delivered
References iris::drivers::Connection::dispatchMessage().
Referenced by iris::drivers::udp::UdpDriver::handle_receive().
void iris::drivers::Driver::enableAddress (const std::string & addr, Sensor * sensorInstance = 0)
Enables the given address for subsequent communication.
Parameters
addr Address to be enabled (without URL prefix and :// separator)
sensorInstance Optional sensor instance to use, otherwise it will be created. Useful when updating an address (e.g. DHCP).
Exceptions
Exception if address is invalid
References activeConnections, createConnection(), distinctConnections, isAddressEnabled(), and iris::drivers::Connection::registerSensor().
Referenced by enableAddresses(), iris::drivers::DriverManager::getSensorFor(), and iris::dist500::updateSensorConnectionsViaBroadcast().
void iris::drivers::Driver::enableAddresses (const AddressList & addresses)
Enables all given addresses for subsequent communication.
Parameters
addresses List of addresses to be enabled (without URL prefix and :// separator)
Exceptions
Exception if any address in the list is invalid
References enableAddress(), and ensureValidAddress().
Referenced by iris::drivers::DriverManager::scanAllDevices(), and iris::drivers::DriverManager::scanDriverDevices().
void iris::drivers::Driver::ensureValidAddress (const std::string & addr) const protected
Verifies the validity of the given address.
Throws an exception if it is not valid.
Parameters
addr Address to be verified
Exceptions
Exception if address is invalid
Note
This method is called internally from several methods to ensure the validity of address parameters
References getName(), and isAddressValid().
Referenced by disableAddresses(), enableAddresses(), and isAddressEnabled().
Driver::AddressList iris::drivers::Driver::getActiveAddresses (void)
Returns the list of currently active (enabled) addresses.
Returns
Address list (without URL prefix and :// separator)
References activeConnections.
Referenced by disableAllAddresses().
Connection & iris::drivers::Driver::getConnection (const std::string & addr)
Returns a connection object for the given sensor address.
Parameters
addr Sensor address (without prefix and :// separator)
Returns
A connection instance for the given address
Exceptions
Exception if the address is invalid
Referenced by getSensor().
const std::string iris::drivers::Driver::getName (void) const
Returns the driver name.
Returns
Driver name
References name.
Referenced by ensureValidAddress(), and iris::dist500::FirmwareController::getSensorInfo().
Sensor & iris::drivers::Driver::getSensor (const std::string & addr)
Returns the associated Sensor instance.
Parameters
addr Sensor address
Returns
Sensor instance
References getConnection(), and iris::drivers::Connection::getSensor().
Referenced by iris::drivers::DriverManager::getSensorFor().
const std::string iris::drivers::Driver::getUrlPrefix (void) const
Returns the URL prefix.
Returns
Prefix (without :// separator)
References urlPrefix.
Referenced by iris::drivers::Connection::getUrlPrefix(), iris::drivers::DriverManager::isDynamic(), iris::drivers::DriverManager::isValid(), iris::drivers::DriverManager::loadDriver(), iris::drivers::DriverManager::registerDriver(), iris::drivers::DriverManager::scanAllDevices(), iris::drivers::DriverManager::unloadDriver(), iris::drivers::DriverManager::unregisterDriver(), and iris::dist500::updateSensorConnectionsViaBroadcast().
const std::string iris::drivers::Driver::getVersion (void) const
Returns the driver version.
Returns
Version string (eg 1.0.0)
References version.
Referenced by iris::dist500::FirmwareController::getSensorInfo().
bool iris::drivers::Driver::isActive (void) const
Checks whether the driver is active or not.
Returns
true if driver is active, false otherwise
Referenced by iris::drivers::DriverManager::scanAllDevices(), iris::drivers::can::CanDriver::shutdownDriver(), iris::drivers::icef::IcefDriver::shutdownDriver(), iris::drivers::udp::UdpDriver::shutdownDriver(), iris::drivers::serial::SerialDriver::shutdownDriver(), iris::drivers::can::CanDriver::startupDriver(), iris::drivers::icef::IcefDriver::startupDriver(), iris::drivers::udp::UdpDriver::startupDriver(), iris::drivers::serial::SerialDriver::startupDriver(), and ~Driver().
bool iris::drivers::Driver::isAddressEnabled (const std::string & addr) const
Checks whether the given address is currently enabled.
Parameters
addr Address to be checked (without URL prefix and :// separator)
Returns
true if enabled, falseotherwise
References activeConnections, and ensureValidAddress().
Referenced by disableAddress(), enableAddress(), and iris::drivers::DriverManager::getSensorFor().
bool iris::drivers::Driver::isAddressValid (const std::string & addr) const
Checks whether the given address is valid or not.
The check is performed using the regular expression stored in the urlAddrRegEx field
Parameters
addr Address to be checked (without prefix and :// separator)
Returns
true if address is valid, false otherwise
References urlAddrRegEx.
Referenced by ensureValidAddress(), iris::drivers::DriverManager::isUrlValid(), and iris::drivers::Connection::setAddress().
Driver::AddressList iris::drivers::Driver::performAddressScan (void * userData = 0, SCAN_CALLBACK callback = 0) const virtual
Returns the list of all sensors addresses that can currently be found.
Parameters
userData User-defined additional parameter for callback
callback Callback for sensor address scan
Returns
Address list (without URL prefix and :// separator)
Reimplemented in iris::drivers::serial::SerialDriver, iris::drivers::udp::UdpDriver, iris::drivers::icef::IcefDriver, and iris::drivers::can::CanDriver.
Referenced by iris::drivers::DriverManager::scanAllDevices(), iris::drivers::DriverManager::scanDriverDevices(), and iris::dist500::updateSensorConnectionsViaBroadcast().
void iris::drivers::Driver::sendBroadcastMessage (const int level, const UipMessage * message) const virtual
Sends the given message in broadcast mode.
Parameters
level UIP level (0..2)
message Message to be sent
Reimplemented in iris::drivers::serial::SerialDriver, iris::drivers::udp::UdpDriver, and iris::drivers::icef::IcefDriver.
Referenced by iris::drivers::Connection::sendBroadcastMessage().
void iris::drivers::Driver::sendMessage (const int level, const std::string & addr, const UipMessage * message) const virtual
Sends the given message.
Parameters
level UIP level (0..2)
addr Sensor address
message Message to be sent
Reimplemented in iris::drivers::serial::SerialDriver, iris::drivers::udp::UdpDriver, and iris::drivers::icef::IcefDriver.
Referenced by iris::drivers::Connection::sendMessage().
bool iris::drivers::Driver::supportsParallelAccess (void) const virtual
Indicates if parallel communication with several sensors is supported or not.
Returns
Parallel support flag
Reimplemented in iris::drivers::serial::SerialDriver, iris::drivers::icef::IcefDriver, and iris::drivers::can::CanDriver.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/drivers/Driver.h
SensorAPI/implementation/iris/drivers/Driver.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !