IRMA MATRIX SDK: iris::dist500::Dist500Base Class Reference
iris::dist500::Dist500Base Class Reference
Implements basic sensor functions like communication, configuration and UIP retry and timeout control.
#include <Dist500Base.h>
Classes
class ConfigurationMismatches
The ConfigurationMismatches class.
class ParameterInfo
The ParameterInfo class holds parameter information like name and value range.
class ParameterValue
The ParameterValue class.
class SpontaneousHandlers
Implements a dispatcher which maps spontaneous UIP frames (sub-command *) to message handler methods.
class TemporaryConfiguration
The TemporaryConfiguration class.
Public Types
typedef std::set< unsigned short > IdSet
typedef std::list< iris::uip::messageTypeDef > MessageTypeDefinitionList
typedef std::map< unsigned short, std::string > ParameterGroups
typedef std::map< unsigned short, ParameterInfo > ParameterInfos
typedef void(* TRANSFER_CONFIGURATION_CALLBACK) (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback for sensor configuration transfers.
Public Member Functions
SENSOR_RESULT _legacyGetDeviceInfo (unsigned short group, unsigned short param, char *buffer)
Retrieves a device feature.
SENSOR_RESULT activateConfiguration (void)
activates a configuration that is already in RAM
SENSOR_RESULT captureDevice (char *application)
Captures the sensor: Marks the device as captured, which can be queried by getCaptureState.
SENSOR_RESULT checkSupportForMessage (const unsigned char command, const unsigned char version, const unsigned char subCommand, bool &isSupported)
checkSupportForMessage Checks if the sensor can respond to the specified message.
SENSOR_RESULT describeParameter (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info, const bool includeName=false)
describeParameter Returns ParameterInfo for the specified parameter which contains the type and value range.
SENSOR_RESULT determineTimeoutParameters (void)
Measures the timeout params (offset and factor) by doing some comnmunication tests.
Dist500Base (iris::drivers::Sensor &sensor)
Constructor.
UipMessage * doSendAndGetApplReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * doSendAndGetReply (int level, UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack or application level message and receives one or more replies.
UipMessage * doSendAndGetServiceReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a service level message and receives one or more replies.
UipMessage * doSendAndGetStackReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT echoTest (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Performs an echo test (pings the sensor)
SENSOR_RESULT getCaptureState (char *applicationBuffer, int maxLen)
Returns the capture state.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, unsigned short &len, bool stackLevel=false)
Reads a configuration parameter.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, bool stackLevel=false)
Reads a configuration parameter from RAM of the sensor (not from flash).
virtual void getConnectionName (char *buffer)
Returns a description for the connection.
virtual void getLocalConnectionName (char *buffer)
Returns an identifier string for local connection (eg IP:port); Currently returns a fixed dummy string.
virtual void getName (char *nameBuffer, int maxLen)
Returns a description for the sensor (ConnectionName + @ + UipAddress)
SENSOR_RESULT getParameterGroupIds (IdSet &groupIds)
Retrieves a set of existing group ids.
SENSOR_RESULT getParameterGroups (ParameterGroups &groups)
Retrieves a map (ParameterGroups) of group ids to group name.
SENSOR_RESULT getParameterIds (const unsigned short groupId, IdSet &paramIds)
SENSOR_RESULT getParameterInfos (const unsigned short groupId, ParameterInfos &infos, const bool includeNames=false)
SENSOR_RESULT getParameterName (const unsigned short groupId, const unsigned short paramId, std::string &paramName)
getParameterName Returns only the name of the specified parameter
iris::drivers::Sensor & getSensor (void)
Returns the associated Sensor instance (from Driver)
unsigned char getUipAddress (void)
Returns the UIP address (integer between 1-255).
SENSOR_RESULT getWorkingMode (iris::uip::working_mode &mode)
Retrieves the sensor working mode (iris::uip::working_mode).
SENSOR_RESULT listAllSupportedMessages (MessageTypeDefinitionList &buffer)
listAllSupportedMessages lists all messages the sensor can respond to.
SENSOR_RESULT lockImmanentData (void)
lockImmanentData
SENSOR_RESULT pingNeighbour (const unsigned char neighbourAddress, const unsigned short payloadLen, const unsigned short repetitions, const unsigned short timeoutMs, unsigned short &successCount, unsigned short &averageTimeMs)
Asks a sensor to ping one of its neighbours (same FA) for a given number of repetitions.
SENSOR_RESULT pingSensor (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Pings a sensor.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT releaseDevice (void)
Releases ("uncaptures") the sensor.
void resetTimeoutParameters (void)
Resets the timeout params to the default values (offset 0, factor 1.0)
SENSOR_RESULT restoreConfigurationFromFlash (void)
Copies the configuration from flash memory to RAM.
SENSOR_RESULT saveConfigurationToFlash (void)
Copies the configuration from RAM to flash memory.
UipMessage * sendAndGetApplReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * sendAndGetServiceReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
UipMessage * sendAndGetStackReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT sendUipCommand (char type, unsigned char version, char command, unsigned short payloadLen, char *payload, unsigned int timeoutMs, char &replyType, unsigned char &replyVersion, char &replyCommand, unsigned short &replyPayloadLen, char *replyPayloadBuffer)
Sends a "free" UIP command to the sensor and waits for the reply.
SENSOR_RESULT setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel=false)
Sets a configuration parameter in the sensor's RAM (not in the flash).
SENSOR_RESULT setConfigurationParameterIfKnown (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool &paramWasUnknown, bool stackLevel=false)
Like setConfigurationParameter but only if that parameter is known.
void setUipAddress (unsigned char)
setUipAddress Sets a new UIP address for communication with this sensor.
void setUipTimeout (const int timeoutMs)
Sets timeout used for UIP send and get reply methods (whereafter usually a retry is performed).
SENSOR_RESULT setWorkingMode (const iris::uip::working_mode mode)
Sets the sensor working mode.
SENSOR_RESULT unlockImmanentData (void)
unlockImmanentData
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
virtual ~Dist500Base ()
Destructor.
Static Public Member Functions
static void disableAutomaticRetries (void)
disables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
static void enableAutomaticRetries (void)
enables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
Protected Types
typedef std::map< unsigned short, ParameterInfo > GroupParameterInfos
typedef std::map< unsigned short, ParameterValue > GroupParameterValues
typedef std::set< int > NoRetryMessageHashSet
typedef std::bitset< 1024 > ReceptionFlags
Protected Member Functions
SENSOR_RESULT _describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos, ReceptionFlags &receivedParameters, iris::uip::ushort &expectedCount)
SENSOR_RESULT _legacyReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _optimizedReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings, const bool sendEmptyIfDefault, ReceptionFlags &receivedParams, iris::uip::ushort &expectedCount)
This is internally used in optimized sensor configuration readouts.
SENSOR_RESULT _setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel, bool ignoreUnknownParamErrors, bool &paramWasUnknown)
SENSOR_RESULT _writeConfiguration (iris::configuration::Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
bool automaticRetriesSupported (UipMessage *message)
Checks if automatic retries are currently supported for the specified message.
SENSOR_RESULT describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos)
describeAllGroupParametersWithoutNames Gets descriptions (GroupParameterInfos) of parameters within the specified configuration group.
SENSOR_RESULT describeParameterWithoutName (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info)
describeParameterWithoutName Gets type and value range information for the specified parameter.
SENSOR_RESULT getGroupName (const unsigned short groupId, std::string &groupName)
getGroupName Gets the name of the specified configuration group.
float getTimeoutFactor (void) const
Returns the timeout factor.
unsigned long getTimeoutOffset (void) const
Returns the timeout offset.
void initializeNoRetryMessageHashSet (void)
These are the messages that are not automatically repeated in case no reply arrives.
SENSOR_RESULT readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings=true, const bool sendEmptyIfDefault=true)
Used for sensor configuration readout, returns a map with parameter values for the specified configuration group.
void registerNoRetryMessage (unsigned char type, unsigned char version, unsigned char command)
Makes the specified message not be automatically resent if no replay arrives.
SENSOR_RESULT requestKeyPuzzle (unsigned short &puzzleLen, unsigned char *puzzleBuffer)
SENSOR_RESULT unlockImmanentData (const unsigned short keyLen, const unsigned char *key)
unlockImmanentData
Static Protected Member Functions
static void handleSpontaneousWorkingModeMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for U 2.0.
Protected Attributes
SpontaneousHandlers handlers
Handler manger for spontaeous UIP messages (sub-command *)
NoRetryMessageHashSet noRetryMessageHashSet
iris::drivers::Sensor & sensor
Reference to associatee driver's Sensor object.
float timeoutFactor
Factor to applied to standard timeouts.
unsigned long timeoutOffset
Constant offset to be applied to standard timeouts.
unsigned char uipAddress
UIP address of sensor.
int uipTimeout
Timeout in ms used for UIP send and get reply methods.
Static Protected Attributes
static bool automaticRetriesDisabled = false
Friends
class iris::drivers::Sensor
Detailed Description
Implements basic sensor functions like communication, configuration and UIP retry and timeout control.
Key methods are listed in "See also".
See also
setWorkingMode
getConfigurationParameter
readConfiguration
listAllSupportedMessages
setUipTimeout
doSendAndGetReply
Member Typedef Documentation
typedef void(* iris::dist500::Dist500Base::TRANSFER_CONFIGURATION_CALLBACK) (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback for sensor configuration transfers.
Parameters
userData User-defined additional parameter for callback
index Current index of configuration parameter (0..total - 1)
total Total count of configuration parameters
groupId Current parameter group id
paramId Current parameter id
See also
readConfiguration
Constructor & Destructor Documentation
iris::dist500::Dist500Base::Dist500Base (iris::drivers::Sensor & sensor)
Constructor.
Parameters
sensor Associated Sensor instance (from Driver)
References iris::drivers::Sensor::getUipAddress(), handlers, handleSpontaneousWorkingModeMessage(), initializeNoRetryMessageHashSet(), iris::dist500::Dist500Base::SpontaneousHandlers::registerHandler(), resetTimeoutParameters(), and uipAddress.
Member Function Documentation
SENSOR_RESULT iris::dist500::Dist500Base::_legacyGetDeviceInfo (unsigned short group, unsigned short param, char * buffer)
Retrieves a device feature.
Parameters
group Feature group
param Feature id
buffer Buffer to receive feature value
Returns
Operation result
Deprecated:
This functionality is now provided by UipGetFirmwareFeaturesRequest
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetStackReply(), uipAddress, and uipTimeout.
Referenced by iris::dist500::FirmwareController::getSensorInfo().
SENSOR_RESULT iris::dist500::Dist500Base::_readAllGroupParameters (const unsigned short groupId, GroupParameterValues & values, const bool truncateStrings, const bool sendEmptyIfDefault, ReceptionFlags & receivedParams, iris::uip::ushort & expectedCount) protected
This is internally used in optimized sensor configuration readouts.
Parameters
groupId Parameter group id as integer.
values Will not be cleared, so retries may fill gaps
truncateStrings Passed on to UipGetGroupConfigFromRamRequestMessage
sendEmptyIfDefault Passed on to UipGetGroupConfigFromRamRequestMessage
receivedParams Flags that will be set to true for each received parameter (using its parameter id as key)
expectedCount Will be filled with number of parameters as received in the response payload.
Returns
OPERATION_PASSED, OPERATION_WRONG_SUBSEQUENT_REPLY, OPERATION_INCOMPLETE_REPLY or OPERATION_WRONG_REPLY
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_INCOMPLETE_REPLY, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::OPERATION_WRONG_SUBSEQUENT_REPLY, iris::drivers::Sensor::receiveMessage(), sensor, uipAddress, and uipTimeout.
Referenced by readAllGroupParameters().
SENSOR_RESULT iris::dist500::Dist500Base::activateConfiguration (void)
activates a configuration that is already in RAM
See also
restoreConfigurationFromFlash
saveConfigurationToFlash
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), uipAddress, and uipTimeout.
bool iris::dist500::Dist500Base::automaticRetriesSupported (UipMessage * message) protected
Checks if automatic retries are currently supported for the specified message.
They can be disabled via registerNoRetryMessage which is checked by this method. The global disabling via disableAutomaticRetries overrides that and is not checked with this method.
Parameters
message
Returns
See also
registerNoRetryMessage
disableAutomaticRetries
References iris::uip::UipMessage::getTypeHash().
Referenced by doSendAndGetReply().
SENSOR_RESULT iris::dist500::Dist500Base::captureDevice (char * application)
Captures the sensor: Marks the device as captured, which can be queried by getCaptureState.
The sensor will keep functioning normally and its working mode is not changed.
Parameters
application Application display name
Returns
Operation result
See also
releaseDevice
getCaptureState
setWorkingMode
References iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetStackReply(), uipAddress, and uipTimeout.
SENSOR_RESULT iris::dist500::Dist500Base::checkSupportForMessage (const unsigned char command, const unsigned char version, const unsigned char subCommand, bool & isSupported)
checkSupportForMessage Checks if the sensor can respond to the specified message.
See also
listAllSupportedMessages
References iris::uip::flag_not_set, iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), uipAddress, and uipTimeout.
Referenced by iris::dist500::FirmwareController::firmwareFitsHardwareCheck(), and readConfiguration().
SENSOR_RESULT iris::dist500::Dist500Base::describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos & infos) protected
describeAllGroupParametersWithoutNames Gets descriptions (GroupParameterInfos) of parameters within the specified configuration group.
Dist500Base::describeAllGroupParametersWithoutNames.
See also
readAllGroupParameters
Parameters
groupId
infos Infos for each parameter go into this map
Returns
Returns SENSOR_RESULT, which on success is OPERATION_PASSED
References iris::dist500::OPERATION_PASSED.
SENSOR_RESULT iris::dist500::Dist500Base::describeParameter (const unsigned short groupId, const unsigned short paramId, ParameterInfo & info, const bool includeName = false)
describeParameter Returns ParameterInfo for the specified parameter which contains the type and value range.
Parameters
groupId
paramId
info
includeName
Returns
See also
describeParameterWithoutName
getParameterName
References describeParameterWithoutName(), getParameterName(), and iris::dist500::OPERATION_PASSED.
SENSOR_RESULT iris::dist500::Dist500Base::describeParameterWithoutName (const unsigned short groupId, const unsigned short paramId, ParameterInfo & info) protected
describeParameterWithoutName Gets type and value range information for the specified parameter.
See also
describeParameter
getParameterName
getConfigurationParameter
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, uipAddress, and uipTimeout.
Referenced by describeParameter().
SENSOR_RESULT iris::dist500::Dist500Base::determineTimeoutParameters (void)
Measures the timeout params (offset and factor) by doing some comnmunication tests.
Returns
Operation result
References echoTest(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_PASSED, timeoutFactor, and timeoutOffset.
void iris::dist500::Dist500Base::disableAutomaticRetries (void) static
disables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
See also
enableAutomaticRetries
setUipTimeout
UipMessage * iris::dist500::Dist500Base::doSendAndGetApplReply (UipMessage * message, int timeoutMs, int replyCount, bool failOnLessReplies = true)
Sends an application level message and receives one or more replies.
Parameters
message Message to be sent
timeoutMs Receive timeout in milliseconds
replyCount Number of expected reply messages
failOnLessReplies When set, then less than replyCount replies mean failure
Returns
Received message (may be linked with others) or 0 if no reply has occured
See also
doSendAndGetReply
References doSendAndGetReply().
Referenced by sendAndGetApplReply().
UipMessage * iris::dist500::Dist500Base::doSendAndGetReply (int level, UipMessage * message, int timeoutMs, int replyCount, bool failOnLessReplies = true)
Sends a stack or application level message and receives one or more replies.
Parameters
level UIP message level. from highest to lowest: application, service or stack.
message Message to be sent
timeoutMs Receive timeout in milliseconds
replyCount Number of expected reply messages
failOnLessReplies If set, then less than replyCount replies mean failure
Returns
Received message (may be linked with others) or 0 if no reply has occured
See also
doSendAndGetApplReply
doSendAndGetServiceReply
doSendAndGetStackReply
sendUipCommand
References automaticRetriesSupported(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::messages::Message::linkTo(), iris::drivers::Sensor::receiveMessage(), iris::drivers::Sensor::sendMessage(), and sensor.
Referenced by doSendAndGetApplReply(), doSendAndGetServiceReply(), and doSendAndGetStackReply().
UipMessage * iris::dist500::Dist500Base::doSendAndGetServiceReply (UipMessage * message, int timeoutMs, int replyCount, bool failOnLessReplies = true)
Sends a service level message and receives one or more replies.
Parameters
message
timeoutMs
replyCount
failOnLessReplies When set, then less than replyCount replies mean failure
Returns
See also
doSendAndGetReply
References doSendAndGetReply().
UipMessage * iris::dist500::Dist500Base::doSendAndGetStackReply (UipMessage * message, int timeoutMs, int replyCount, bool failOnLessReplies = true)
Sends a stack level message and receives one or more replies.
Parameters
message Message to be sent
timeoutMs Receive timeout in milliseconds
replyCount Number of expected reply messages
failOnLessReplies If set, then less than replyCount replies mean failure
Returns
Received message (may be linked with others) or 0 if no reply has occured
See also
doSendAndGetReply
References doSendAndGetReply().
Referenced by sendAndGetStackReply().
SENSOR_RESULT iris::dist500::Dist500Base::echoTest (const char *const payload, const unsigned short payloadLen, int timeoutMs = MAX_DEFAULT_IO_WAIT)
Performs an echo test (pings the sensor)
Parameters
payload Pointer to payload bytes
payloadLen Number of payload bytes to be used
Communication timeout in ms
Returns
Operation result
See also
pingSensor
Deprecated:
This method only exists for backwards compatibility. Please use pingSensor() instead.
References pingSensor().
Referenced by determineTimeoutParameters().
void iris::dist500::Dist500Base::enableAutomaticRetries (void) static
enables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
See also
disableAutomaticRetries
setUipTimeout
SENSOR_RESULT iris::dist500::Dist500Base::getCaptureState (char * applicationBuffer, int maxLen)
Returns the capture state.
Parameters
applicationBuffer Buffer to receive the capturing app's name
maxLen Buffer capacity
Returns
Operation result
See also
captureDevice
releaseDevice
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetStackReply(), uipAddress, and uipTimeout.
Referenced by iris::dist500::FirmwareController::getSensorInfo().
SENSOR_RESULT iris::dist500::Dist500Base::getConfigurationParameter (unsigned short group, unsigned short param, char * buffer, unsigned short & len, bool stackLevel = false)
Reads a configuration parameter.
Parameters
group Parameter group
param Parameter id
buffer Buffer to receive feature value
len Buffer receiving the actual length in bytes
Returns
Operation result
See also
setConfigurationParameter
References iris::messages::DynamicBuffer::getLength(), iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetStackReply(), uipAddress, and uipTimeout.
Referenced by iris::dist500::FirmwareController::checkSensorsConsistency(), getConfigurationParameter(), iris::dist500::FirmwareController::getSensorInfo(), iris::dist500::FirmwareController::performContainerFirmwareUpdate(), iris::dist500::FirmwareController::updateContainerApplication(), iris::dist500::FirmwareController::updateContainerCommunication(), and iris::dist500::updateSensorConnectionsViaBroadcast().
SENSOR_RESULT iris::dist500::Dist500Base::getConfigurationParameter (unsigned short group, unsigned short param, char * buffer, bool stackLevel = false)
Reads a configuration parameter from RAM of the sensor (not from flash).
Parameters
group Parameter group
param Parameter id
buffer Buffer to receive feature value
Returns
Operation result
See also
setConfigurationParameter
setConfigurationParameterIfKnown
References getConfigurationParameter().
void iris::dist500::Dist500Base::getConnectionName (char * buffer) virtual
Returns a description for the connection.
Parameters
buffer Buffer to receive name
maxLen Buffer capacity
See also
getName
getLocalConnectionName
References iris::drivers::Sensor::getAddr(), and sensor.
Referenced by getName().
SENSOR_RESULT iris::dist500::Dist500Base::getGroupName (const unsigned short groupId, std::string & groupName) protected
getGroupName Gets the name of the specified configuration group.
Parameters
groupId
groupName
Returns
See also
readAllGroupParameters
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, uipAddress, and uipTimeout.
Referenced by getParameterGroups().
void iris::dist500::Dist500Base::getName (char * nameBuffer, int maxLen) virtual
Returns a description for the sensor (ConnectionName + @ + UipAddress)
Parameters
buffer Buffer to receive name
maxLen Buffer capacity
See also
getConnectionName
getLocalConnectionName
References getConnectionName(), and uipAddress.
SENSOR_RESULT iris::dist500::Dist500Base::getParameterGroupIds (IdSet & groupIds)
Retrieves a set of existing group ids.
Continue sensor configuration readout via readAllGroupParameters.
Parameters
groupIds output parameter
See also
getGroupName
getConfigurationParameter
readAllGroupParameters
References iris::messages::DynamicBuffer::getLength(), iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, uipAddress, and uipTimeout.
Referenced by getParameterGroups().
SENSOR_RESULT iris::dist500::Dist500Base::getParameterGroups (ParameterGroups & groups)
Retrieves a map (ParameterGroups) of group ids to group name.
Convenience wrapper of getParameterGroupIds and getGroupName.
Parameters
groups output parameter
See also
References getGroupName(), getParameterGroupIds(), and iris::dist500::OPERATION_PASSED.
SENSOR_RESULT iris::dist500::Dist500Base::getParameterName (const unsigned short groupId, const unsigned short paramId, std::string & paramName)
getParameterName Returns only the name of the specified parameter
Parameters
groupId
paramId
paramName output parameter
See also
describeParameter
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, uipAddress, and uipTimeout.
Referenced by describeParameter().
float iris::dist500::Dist500Base::getTimeoutFactor (void) const protected
Returns the timeout factor.
Returns
Timeout factor
References timeoutFactor.
unsigned long iris::dist500::Dist500Base::getTimeoutOffset (void) const protected
Returns the timeout offset.
Returns
Timeout offset
References timeoutOffset.
unsigned char iris::dist500::Dist500Base::getUipAddress (void)
Returns the UIP address (integer between 1-255).
The UIP address is the number after the hash sign in a URL.
See also
setUipAddress
getConnectionName
getLocalConnectionName
getName
References uipAddress.
SENSOR_RESULT iris::dist500::Dist500Base::getWorkingMode (iris::uip::working_mode & mode)
Retrieves the sensor working mode (iris::uip::working_mode).
Parameters
mode Reference to sensor working mode variable receiving the data
See also
setWorkingMode
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), uipAddress, and uipTimeout.
void iris::dist500::Dist500Base::handleSpontaneousWorkingModeMessage (Dist500Base * base, UipMessage * message) static protected
Callback function for spontaneous messages (sub-command *), here only for U 2.0.
If the sensor reports its working mode, it is dispatched via these.
Parameters
base Dist500Base instance (surrogate for this pointer)
message Spontaneously received message
See also
getWorkingMode
setWorkingMode
References iris::dist500::WorkingModeStatusSource::pushWorkingModeStatusToSinks().
Referenced by Dist500Base().
void iris::dist500::Dist500Base::initializeNoRetryMessageHashSet (void) protected
These are the messages that are not automatically repeated in case no reply arrives.
Reasons are given in source code after each call to registerNoRetryMessage. Typical reasons are when a message has side-effects and can not be retried without knowledge of the user.
See also
registerNoRetryMessage
References registerNoRetryMessage().
Referenced by Dist500Base().
SENSOR_RESULT iris::dist500::Dist500Base::listAllSupportedMessages (MessageTypeDefinitionList & buffer)
listAllSupportedMessages lists all messages the sensor can respond to.
See also
checkSupportForMessage
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), uipAddress, and uipTimeout.
SENSOR_RESULT iris::dist500::Dist500Base::lockImmanentData (void)
lockImmanentData
See also
unlockImmanentData
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), uipAddress, and uipTimeout.
SENSOR_RESULT iris::dist500::Dist500Base::pingNeighbour (const unsigned char neighbourAddress, const unsigned short payloadLen, const unsigned short repetitions, const unsigned short timeoutMs, unsigned short & successCount, unsigned short & averageTimeMs)
Asks a sensor to ping one of its neighbours (same FA) for a given number of repetitions.
Parameters
neighbourAddress UIP address of neighbour
payloadLen Payload size of ping message
repetitions Number of ping repetitions
timeoutMs Communication timeout in milliseconds (between sensors)
successCount Returns the number of successful pings
averageTimeMs Average communication time per ping
Returns
Operation result
See also
pingSensor
References iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetStackReply(), and uipAddress.
SENSOR_RESULT iris::dist500::Dist500Base::pingSensor (const char *const payload, const unsigned short payloadLen, int timeoutMs = MAX_DEFAULT_IO_WAIT)
Pings a sensor.
No repetitions if there is no reply, so the roundtrip time may be measured and compared.
Parameters
payload Pointer to payload bytes
payloadLen Number of payload bytes to be used
Communication timeout in ms
Returns
Operation result
See also
pingNeighbour
References iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetStackReply(), and uipAddress.
Referenced by echoTest(), and iris::dist500::FirmwareController::performContainerFirmwareUpdate().
SENSOR_RESULT iris::dist500::Dist500Base::readAllGroupParameters (const unsigned short groupId, GroupParameterValues & values, const bool truncateStrings = true, const bool sendEmptyIfDefault = true) protected
Used for sensor configuration readout, returns a map with parameter values for the specified configuration group.
Parameters
values output map of parameter id to parameter value
See also
getGroupName
getParameterGroupIds
getParameterGroups
getConfigurationParameter
References _readAllGroupParameters(), and iris::dist500::OPERATION_PASSED.
SENSOR_RESULT iris::dist500::Dist500Base::readConfiguration (iris::configuration::Dist500Configuration & config, TRANSFER_CONFIGURATION_CALLBACK callback = 0, void * userData = 0)
Reads the sensor configuration RAM shadow.
Parameters
config Reference to sensor configuration receiving the data
callback Callback for sensor configuration transfer
userData User-defined additional parameter for callback
Returns
Operation result
See also
iris::dist500::Dist500Base::TRANSFER_CONFIGURATION_CALLBACK
Note
Sensor configuration contains only parameters known both to sensor and PC.
Referenced by iris::dist500::FirmwareController::configureSensorGroup(), and iris::dist500::FirmwareController::performContainerParameterUpdate().
SENSOR_RESULT iris::dist500::Dist500Base::readConfiguration (iris::configuration::Dist500Configuration & config, ConfigurationMismatches & mismatches, TRANSFER_CONFIGURATION_CALLBACK callback = 0, void * userData = 0)
Reads the sensor configuration RAM shadow.
Parameters
config Reference to sensor configuration receiving the data
mismatches Reference to sensor configuration mismatches receiving the data
callback Callback for sensor configuration transfer
userData User-defined additional parameter for callback
Returns
Operation result
Note
Sensor configuration contains only parameters known both to sensor and PC. Sensor configuration mismatches contain all other parameters
References checkSupportForMessage(), and iris::dist500::OPERATION_PASSED.
void iris::dist500::Dist500Base::registerNoRetryMessage (unsigned char type, unsigned char version, unsigned char command) protected
Makes the specified message not be automatically resent if no replay arrives.
Is called for some messages in initializeNoRetryMessageHashSet().
Parameters
type
version
command
See also
automaticRetriesSupported
enableAutomaticRetries
disableAutomaticRetries
setUipTimeout
Referenced by initializeNoRetryMessageHashSet().
SENSOR_RESULT iris::dist500::Dist500Base::releaseDevice (void)
Releases ("uncaptures") the sensor.
Has no effect on the working mode.
Returns
Operation result
See also
captureDevice
getCaptureState
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetStackReply(), uipAddress, and uipTimeout.
SENSOR_RESULT iris::dist500::Dist500Base::restoreConfigurationFromFlash (void)
Copies the configuration from flash memory to RAM.
See also
activateConfiguration
saveConfigurationToFlash
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), uipAddress, and uipTimeout.
Referenced by iris::dist500::FirmwareController::configureSensorGroup(), and iris::dist500::FirmwareController::performContainerParameterUpdate().
SENSOR_RESULT iris::dist500::Dist500Base::saveConfigurationToFlash (void)
Copies the configuration from RAM to flash memory.
See also
restoreConfigurationFromFlash
activateConfiguration
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), and uipAddress.
Referenced by iris::dist500::FirmwareController::configureSensorGroup(), and iris::dist500::FirmwareController::performContainerParameterUpdate().
UipMessage * iris::dist500::Dist500Base::sendAndGetApplReply (UipMessage * message, int timeoutMs = MAX_DEFAULT_IO_WAIT, int replyCount = 1, bool failOnLessReplies = true)
Sends an application level message and receives one or more replies.
Parameters
message Message to be sent
timeoutMs Receive timeout in milliseconds
replyCount Number of expected reply messages
failOnLessReplies When set, then less than replyCount replies mean failure
Returns
Received message (may be linked with others) or 0 if no reply has occured
References doSendAndGetApplReply(), iris::uip::UipMessage::getReceiver(), and iris::uip::UipMessage::getSender().
Referenced by activateConfiguration(), iris::dist500::FpgaController::activateMovie(), iris::dist500::CounterController::checkCategoryDefinitionAcceptance(), checkSupportForMessage(), iris::dist500::InstallationModeController::continueInstallationMode(), iris::dist500::Dist500::disableExposureControl(), iris::dist500::DoorController::disableHallSensor(), iris::dist500::InstallationModeController::disableInstallationMode(), iris::dist500::InstallationModeController::disableTestrideMode(), iris::dist500::Dist500::enableExposureControl(), iris::dist500::DoorController::enableHallSensor(), iris::dist500::InstallationModeController::enableInstallationMode(), iris::dist500::InstallationModeController::enableTestrideMode(), iris::dist500::FlashController::eraseFirmware(), iris::dist500::FlashController::eraseMemory(), iris::dist500::CounterController::getCountCategories(), iris::dist500::CounterController::getCountResults(), iris::dist500::DoorController::getDoorState(), iris::dist500::Dist500::getFirmwareFeatures(), iris::dist500::FpgaController::getFpgaRegister(), iris::dist500::CounterController::getFunctionAreaStatuses(), iris::dist500::DoorController::getHallSensorFunction(), iris::dist500::DoorController::getHallSensorState(), iris::dist500::CounterController::getKnownCategoryTypes(), iris::dist500::Dist500::getSensorRevisionCode(), iris::dist500::CounterController::getSensorStatuses(), iris::dist500::Dist500::getStatusLedMode(), getWorkingMode(), listAllSupportedMessages(), lockImmanentData(), iris::dist500::FpgaController::prepareMovieUpload(), iris::dist500::FlashController::readFirmware(), iris::dist500::FlashController::readMemory(), iris::dist500::CounterController::resetCounts(), iris::dist500::Dist500::resetDsp(), iris::dist500::CounterController::resetSensorStatuses(), restoreConfigurationFromFlash(), saveConfigurationToFlash(), sendUipCommand(), iris::dist500::CounterController::setCountResults(), iris::dist500::DoorController::setDoorState(), iris::dist500::FpgaController::setFpgaRegister(), iris::dist500::DoorController::setHallSensorFunction(), iris::dist500::DoorController::setHallSensorState(), iris::dist500::Dist500::setStatusLedMode(), setWorkingMode(), iris::dist500::CounterController::startCounting(), iris::dist500::CounterController::stopCounting(), iris::dist500::FlashController::switchFirmware(), unlockImmanentData(), iris::dist500::FpgaController::uploadMoviePicture(), iris::dist500::FlashController::writeFirmware(), and iris::dist500::FlashController::writeMemory().
UipMessage * iris::dist500::Dist500Base::sendAndGetStackReply (UipMessage * message, int timeoutMs = MAX_DEFAULT_IO_WAIT, int replyCount = 1, bool failOnLessReplies = true)
Sends a stack level message and receives one or more replies.
Parameters
message Message to be sent
timeoutMs Receive timeout in milliseconds
replyCount Number of expected reply messages
failOnLessReplies When set, then less than replyCount replies mean failure
Returns
Received message (may be linked with others) or 0 if no reply has occured
References doSendAndGetStackReply(), iris::uip::UipMessage::getReceiver(), and iris::uip::UipMessage::getSender().
Referenced by _legacyGetDeviceInfo(), captureDevice(), getCaptureState(), getConfigurationParameter(), pingNeighbour(), pingSensor(), and releaseDevice().
SENSOR_RESULT iris::dist500::Dist500Base::sendUipCommand (char type, unsigned char version, char command, unsigned short payloadLen, char * payload, unsigned int timeoutMs, char & replyType, unsigned char & replyVersion, char & replyCommand, unsigned short & replyPayloadLen, char * replyPayloadBuffer)
Sends a "free" UIP command to the sensor and waits for the reply.
This is the lowest level method for sending messages.
See also
doSendAndGetReply
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, sendAndGetApplReply(), and uipAddress.
SENSOR_RESULT iris::dist500::Dist500Base::setConfigurationParameter (unsigned short group, unsigned short param, const char * buffer, unsigned short len, bool stackLevel = false)
Sets a configuration parameter in the sensor's RAM (not in the flash).
See also
getConfigurationParameter
setConfigurationParameterIfKnown
SENSOR_RESULT iris::dist500::Dist500Base::setConfigurationParameterIfKnown (unsigned short group, unsigned short param, const char * buffer, unsigned short len, bool & paramWasUnknown, bool stackLevel = false)
Like setConfigurationParameter but only if that parameter is known.
See also
setConfigurationParameter
getConfigurationParameter
void iris::dist500::Dist500Base::setUipAddress (unsigned char address)
setUipAddress Sets a new UIP address for communication with this sensor.
The UIP address is the number after the hash sign in a URL.
Note
If the UIP changes, it must be updated, otherwise messages will not be received (discarded) or sent to a wrong address.
The UIP address can change on grouping or ungrouping of sensors. Direct configuration of the UIP is another possibility.
See also
getUipAddress
getConnectionName
getLocalConnectionName
getName
References sensor, and uipAddress.
Referenced by iris::dist500::updateSensorConnectionsViaBroadcast().
void iris::dist500::Dist500Base::setUipTimeout (const int timeoutMs)
Sets timeout used for UIP send and get reply methods (whereafter usually a retry is performed).
Can be useful on slow or crowded networks. Some long operations like EraseFirmware use a different timeout value that is not affected.
Parameters
timeoutMs Timeout in milliseconds
References uipTimeout.
SENSOR_RESULT iris::dist500::Dist500Base::setWorkingMode (const iris::uip::working_mode mode)
Sets the sensor working mode.
Parameters
mode sensor working mode to be set
See also
getWorkingMode
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::uip::normal_mode, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), uipAddress, and uipTimeout.
Referenced by iris::dist500::FirmwareController::performContainerFirmwareUpdate().
SENSOR_RESULT iris::dist500::Dist500Base::unlockImmanentData (void)
unlockImmanentData
See also
lockImmanentData
References iris::dist500::OPERATION_PASSED.
SENSOR_RESULT iris::dist500::Dist500Base::unlockImmanentData (const unsigned short keyLen, const unsigned char * key) protected
unlockImmanentData
See also
lockImmanentData
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, sendAndGetApplReply(), uipAddress, and uipTimeout.
SENSOR_RESULT iris::dist500::Dist500Base::writeConfiguration (iris::configuration::Dist500Configuration & config, TRANSFER_CONFIGURATION_CALLBACK callback = 0, void * userData = 0)
Writes the sensor configuration RAM shadow.
Parameters
config Reference to sensor configuration receiving the data
callback Callback for sensor configuration transfer
userData User-defined additional parameter for callback
Returns
Operation result
Note
Sensor configuration contains only parameters known both to sensor and PC.
Referenced by iris::dist500::FirmwareController::configureSensorGroup(), and iris::dist500::FirmwareController::performContainerParameterUpdate().
SENSOR_RESULT iris::dist500::Dist500Base::writeConfiguration (iris::configuration::Dist500Configuration & config, ConfigurationMismatches & mismatches, TRANSFER_CONFIGURATION_CALLBACK callback = 0, void * userData = 0)
Writes the sensor configuration RAM shadow.
Parameters
config Reference to sensor configuration receiving the data
mismatches Reference to sensor configuration mismatches receiving the data
callback Callback for sensor configuration transfer
userData User-defined additional parameter for callback
Returns
Operation result
Note
Sensor configuration contains only parameters known both to sensor and PC. Sensor configuration mismatches contain all other parameters
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/Dist500Base.h
SensorAPI/implementation/iris/dist500/Dist500Base.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !