IRMA MATRIX SDK: iris::messages::DynamicBuffer Class Reference
iris::messages::DynamicBuffer Class Reference
Encapsulates a binary read/write buffer that can grow dynamically.
#include <DynamicBuffer.h>
Public Member Functions
void clear (void)
Clears the buffer.
DynamicBuffer (unsigned short maxLength, char *buffer=NULL)
Constructor.
char * getBuffer (void)
Returns the internal buffer pointer.
unsigned short getLength (void)
Returns the current buffer length.
unsigned short getMaxLength (void)
Returns the length limitation.
unsigned short getPosition (void)
Returns the current read/write position.
bool movePosition (signed short movement)
Moves the read/write pointer relative to its current position.
virtual void printDebugInfo (std::ostream &ostream)
Prints a debug hex-dump of the buffer to an output stream.
virtual void printDebugInfoPart (std::ostream &ostream, const unsigned short offset, const unsigned short length)
Prints a debug hex-dump of a part of the buffer to an output stream.
bool readBlock (void *data, const unsigned short size)
Reads a data block from the current position.
bool readSByte (signed char &byte)
Reads a signed byte from the current position.
bool readSLong (signed long &lng)
Reads a signed long (32 bits) from the current position.
bool readSLong64 (signed long long &lng64)
Reads a signed long long (64 bits) from the current position.
bool readString (char *string)
Reads a string from the current position.
bool readString (char *string, const unsigned short size)
Reads a string from the current position using a fixed length.
bool readSWord (signed short &word)
Reads a signed word (16 bits) from the current position.
bool readUByte (unsigned char &byte)
Reads an unsigned byte from the current position.
bool readULong (unsigned long &lng)
Reads an unsigned long (32 bits) from the current position.
bool readULong64 (unsigned long long &lng64)
Reads an unsigned long long (64 bits) from the current position.
bool readUWord (unsigned short &word)
Reads an unsigned word (16 bits) from the current position.
void reset (void)
Resets the read/write pointer to zero.
bool setLength (unsigned short newLength)
Sets the buffer length.
bool setPosition (unsigned short newPosition)
Sets the absolute position of the read/write pointer.
bool writeBlock (const void *data, const unsigned short size)
Writes a block of bytes at the current position.
bool writeSByte (const signed char byte)
Writes a signed byte at the current position.
bool writeSLong (const signed long lng)
Writes a signed long (32 bits) at the current position.
bool writeSLong64 (const signed long long lng64)
Writes a signed long long (64 bits) at the current position.
bool writeString (const char *string)
Writes a string at the current position.
bool writeString (const char *string, const unsigned short size)
Writes a string at the current position using a fixed size.
bool writeSWord (const signed short word)
Writes a signed word (16 bits) at the current position.
bool writeUByte (const unsigned char byte)
Writes an unsigned byte at the current position.
bool writeULong (const unsigned long lng)
Writes an unsigned long (32 bits) at the current position.
bool writeULong64 (const unsigned long long lng64)
Writes an unsigned long long (64 bits) at the current position.
bool writeUWord (const unsigned short word)
Writes an unsigned word (16 bits) at the current position.
virtual ~DynamicBuffer ()
Destructor.
Protected Attributes
char * buffer
Pointer to buffer memory.
unsigned short length
Current size.
unsigned short maxLength
Maximum size.
bool ownAllocation
Flag indicating if buffer memory has been allocated internally or externally.
unsigned short position
Current read/write position.
Detailed Description
Encapsulates a binary read/write buffer that can grow dynamically.
Constructor & Destructor Documentation
iris::messages::DynamicBuffer::DynamicBuffer (unsigned short maxLength, char * buffer = NULL)
Constructor.
Parameters
maxLength Maximum length
buffer Optional pointer to external buffer memory
Member Function Documentation
char * iris::messages::DynamicBuffer::getBuffer (void)
Returns the internal buffer pointer.
Returns
Buffer
Referenced by iris::uip::UipMessage::getPayload().
unsigned short iris::messages::DynamicBuffer::getLength (void)
Returns the current buffer length.
Returns
Length
Referenced by iris::dist500::Dist500Base::getConfigurationParameter(), iris::dist500::Dist500::getFirmwareFeatures(), iris::dist500::Dist500Base::getParameterGroupIds(), and iris::uip::UipMessage::getPayloadLen().
unsigned short iris::messages::DynamicBuffer::getMaxLength (void)
Returns the length limitation.
Returns
Maximum length
unsigned short iris::messages::DynamicBuffer::getPosition (void)
Returns the current read/write position.
Returns
Position
bool iris::messages::DynamicBuffer::movePosition (signed short movement)
Moves the read/write pointer relative to its current position.
Parameters
movement Relative movement
Returns
true if successful, false otherwise
void iris::messages::DynamicBuffer::printDebugInfo (std::ostream & ostream) virtual
Prints a debug hex-dump of the buffer to an output stream.
Parameters
ostream Output stream to receive the hex dump
Reimplemented in iris::uip::UipMessage.
Referenced by iris::messages::operator<<().
void iris::messages::DynamicBuffer::printDebugInfoPart (std::ostream & ostream, const unsigned short offset, const unsigned short length) virtual
Prints a debug hex-dump of a part of the buffer to an output stream.
Parameters
ostream Output stream to receive the hex dump
offset Starting offset
length Number of bytes
bool iris::messages::DynamicBuffer::readBlock (void * data, const unsigned short size)
Reads a data block from the current position.
Parameters
data Block buffer
size Number of bytes
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readSByte (signed char & byte)
Reads a signed byte from the current position.
Parameters
byte Byte buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readSLong (signed long & lng)
Reads a signed long (32 bits) from the current position.
Parameters
lng Long buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readSLong64 (signed long long & lng64)
Reads a signed long long (64 bits) from the current position.
Parameters
lng64 Long long buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readString (char * string)
Reads a string from the current position.
Parameters
string String buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readString (char * string, const unsigned short size)
Reads a string from the current position using a fixed length.
Parameters
string String buffer
size Number of bytes
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readSWord (signed short & word)
Reads a signed word (16 bits) from the current position.
Parameters
word Word buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readUByte (unsigned char & byte)
Reads an unsigned byte from the current position.
Parameters
byte Byte buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readULong (unsigned long & lng)
Reads an unsigned long (32 bits) from the current position.
Parameters
lng Long buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readULong64 (unsigned long long & lng64)
Reads an unsigned long long (64 bits) from the current position.
Parameters
lng64 Long long buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::readUWord (unsigned short & word)
Reads an unsigned word (16 bits) from the current position.
Parameters
word Word buffer
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::setLength (unsigned short newLength)
Sets the buffer length.
Parameters
newLength New length (must not exceed maximum length)
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::setPosition (unsigned short newPosition)
Sets the absolute position of the read/write pointer.
Parameters
newPosition Desired position
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeBlock (const void * data, const unsigned short size)
Writes a block of bytes at the current position.
Parameters
data Data to be written
size Length of data in bytes
Returns
true if successful, false otherwise
Referenced by iris::uip::UipMessage::UipMessage().
bool iris::messages::DynamicBuffer::writeSByte (const signed char byte)
Writes a signed byte at the current position.
Parameters
byte Byte to be written
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeSLong (const signed long lng)
Writes a signed long (32 bits) at the current position.
Parameters
lng Long to be written
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeSLong64 (const signed long long lng64)
Writes a signed long long (64 bits) at the current position.
Parameters
lng64 Long long to be written
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeString (const char * string)
Writes a string at the current position.
Parameters
string String to be written
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeString (const char * string, const unsigned short size)
Writes a string at the current position using a fixed size.
Parameters
string String to be written
size Destination size in bytes
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeSWord (const signed short word)
Writes a signed word (16 bits) at the current position.
Parameters
word Word to be written
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeUByte (const unsigned char byte)
Writes an unsigned byte at the current position.
Parameters
byte Byte to be written
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeULong (const unsigned long lng)
Writes an unsigned long (32 bits) at the current position.
Parameters
lng Long to be written
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeULong64 (const unsigned long long lng64)
Writes an unsigned long long (64 bits) at the current position.
Parameters
lng64 Long long to be written
Returns
true if successful, false otherwise
bool iris::messages::DynamicBuffer::writeUWord (const unsigned short word)
Writes an unsigned word (16 bits) at the current position.
Parameters
word Word to be written
Returns
true if successful, false otherwise
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/messages/DynamicBuffer.h
SensorAPI/implementation/iris/messages/DynamicBuffer.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !