IRMA MATRIX SDK: iris::dist500::CountResult Class Reference
iris::dist500::CountResult Class Reference
Encapsulates a count result.
#include <CountResult.h>
Public Member Functions
CountResult (unsigned long pictureNumber, unsigned long long timestamp, unsigned short category, unsigned short boarding, unsigned short alighting)
Constructor.
CountResult ()
No-arg constructor (needed for Qt signalling)
unsigned short getAlighting (void)
Returns the number of alighting passengers.
unsigned short getBoarding (void)
Returns the number of boarding passengers.
unsigned short getCategory (void)
Returns the category ID.
std::string getComment (void) const
unsigned int getCountIndex (void) const
unsigned int getIntervalIndex (void) const
bool isSingleEvent (void)
void markAsRegularCount (void)
void markAsSingleEvent (void)
void setAlighting (const unsigned short alighting)
void setBoarding (const unsigned short boarding)
void setCategory (const unsigned short category)
void setCommand (const std::string &comm)
void setCountIndex (const unsigned int idx)
void setIntervalIndex (const unsigned int idx)
Public Member Functions inherited from iris::dist500::PictureBoundData
unsigned long getPictureNumber (void)
Returns the picture number.
unsigned char getSensorNo (void) const
unsigned long long getTimestamp (void)
Returns the timestamp.
PictureBoundData (unsigned long pictureNumber, unsigned long long timestamp)
Constructor.
void setPictureNumber (unsigned long pictureNumber)
Changes the picture number.
void setSensorNo (const unsigned char no)
void setTimestamp (unsigned long long timestamp)
Changes the timestamp.
Protected Attributes
unsigned short alighting
Holds the number of alighting passengers.
unsigned short boarding
Holds the number of boarding passengers.
unsigned short category
Holds the category ID.
std::string comment
unsigned int countIndex
unsigned int intervalIndex
bool singleEvent
Protected Attributes inherited from iris::dist500::PictureBoundData
unsigned long pictureNumber
Holds the picture number (created by sensor)
unsigned char sensorNo
unsigned long long timestamp
Holds the timestamp (created by sensor)
Detailed Description
Encapsulates a count result.
Constructor & Destructor Documentation
iris::dist500::CountResult::CountResult (unsigned long pictureNumber, unsigned long long timestamp, unsigned short category, unsigned short boarding, unsigned short alighting)
Constructor.
CountResult::CountResult Constructor with parameters.
Parameters
pictureNumber Picture number (created by sensor)
timestamp Timestamp (created by sensor)
category Caegory ID
boarding Number of boarding passengers
alighting Number of alighting passengers
pictureNumber running index of the picture
timestamp an unsigned timestamp
category the category that was counted
boarding people who entered the vehicle
alighting people who left the vehicle
iris::dist500::CountResult::CountResult ()
No-arg constructor (needed for Qt signalling)
CountResult::CountResult.
Member Function Documentation
unsigned short iris::dist500::CountResult::getAlighting (void)
Returns the number of alighting passengers.
Returns
Alighting count
References alighting.
Referenced by iris::uff::UffRecorder::processNewCountResult(), and iris::uff::UffDecoder::repushData().
unsigned short iris::dist500::CountResult::getBoarding (void)
Returns the number of boarding passengers.
Returns
Boarding count
References boarding.
Referenced by iris::uff::UffRecorder::processNewCountResult(), and iris::uff::UffDecoder::repushData().
unsigned short iris::dist500::CountResult::getCategory (void)
Returns the category ID.
Returns
Category ID
References category.
Referenced by iris::uff::UffRecorder::processNewCountResult(), and iris::uff::UffDecoder::repushData().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/CountResult.h
SensorAPI/implementation/iris/dist500/CountResult.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !