IRMA MATRIX SDK: iris::dist500::FirmwareController Class Reference
iris::dist500::FirmwareController Class Reference
Implements DIST500 functions related to firmware and configuration data.
#include <FirmwareController.h>
Classes
struct _ParameterUpdateInformation
Typedef for a parameter update result.
struct _UpdateInformation
Typedef for a container update information.
class ConfigurationInterceptor
struct ContainerUpdateUserData
Typedef for container update data.
struct FirmwareReleaseInfo
Typedef for firmware release information.
struct SensorInformation
struct t_FirmwareInfo
struct t_FirmwareInfoWithCRC
Public Types
enum CONTAINER_PARAMETER_RESULT {
CONTAINER_WRONG_PARAMETER_VALUE, CONTAINER_UNKNOWN_PARAMETER, CONTAINER_UNKNOWN_SENSOR_PARAMETER, CONTAINER_PARAMETER_NOT_WRITE,
CONTAINER_PARAMETER_WRONG_UPDATE_STATE
}
Container paramter update result codes.
enum CONTAINER_UPDATE_RESULT {
CONTAINER_UPDATE_PASSED = 0, CONTAINER_UPDATE_FAILED, CONTAINER_OPEN_FILE_FAILED, CONTAINER_SET_WORKING_MODE_FAILED,
CONTAINER_GROUP_INCOMPLETE, CONTAINER_APPLICATION_UPDATE_FAILED, CONTAINER_APPLICATION_VERIFY_FAILED, CONTAINER_COMMUNICATION_UPDATE_FAILED,
CONTAINER_COMMUNICATION_VERIFY_FAILED, CONTAINER_FPGA_UPDATE_FAILED, CONTAINER_FIRST_FPGA_UPDATE_FAILED, CONTAINER_SECOND_FPGA_UPDATE_FAILED,
CONTAINER_FIRST_FPGA_VERIFY_FAILED, CONTAINER_SECOND_FPGA_VERIFY_FAILED, CONTAINER_RESTART_FAILED, CONTAINER_READ_CONFIGURATION_FAILED,
CONTAINER_CHANGE_CONFIGURATION_FAILED, CONTAINER_GET_UPDATE_PARAMETER_FAILED, CONTAINER_WRITE_CONFIG_FAILED, CONTAINER_SAVE_CONFIG_FAILED,
UNSUPPORTED_CONTAINER_FILE, CONTAINER_READ_FPGA_IMAGE_FAILED, CONTAINER_FPGA_IMAGE_MISMATCH, CONTAINER_RESTORE_CONFIGURATION_FROM_FLASH_FAILED,
CONTAINER_GET_PARAMETER_FAILED
}
Container file update result codes.
typedef iris::dist500::Dist500List Dist500List
Dist500List.
typedef std::list< FirmwareController * > FirmwareControllerList
Typedef for a list of FirmwareController instances.
enum FirmwareFitHardwareResult {
FIRWARE_CHECK_PASSED, FIRWARE_CHECK_FAILED, NO_VALID_FILE_EXTENSION, CANNOT_OPEN_CONTAINER,
NO_APPLICATION_FOUND, CANNOT_DECODE_HEXFILE, HEXFILE_ADDRESS_RANGE_FAULTY, ALLOC_MEMORY_FAILED,
NO_IRIS_AUTHENTICATION, NO_LDR_FILE_FOUND, CANNOT_READ_FIRMWARE_VERSION, CHECK_MESSAGE_SUPPORT_FAILED,
GET_REVISION_CODE_FAILED, UNKNOWN_REVISION_CODE, FIRMWARE_NOT_MATCH_TO_HARDWARE
}
Result of the query if the firmware matches the Hardware.
typedef std::map< iris::dist500::Dist500 *, FirmwareFitHardwareResult > FirmwareFitHardwareResultMap
Maps sensor instances to firmware fit hardware result.
typedef std::list< SensorFirmware > FirmwareSkippedList
typedef unsigned char MacAddress[6]
Type for a MAC address (6 octets)
typedef struct iris::dist500::FirmwareController::_ParameterUpdateInformation ParameterUpdateInformation
Typedef for a parameter update result.
typedef std::list< ParameterUpdateInformation > ParameterUpdateInformationList
enum SensorFirmware { APPLICATION_FIRMWARE, COMMUNICATION_FIRMWARE, FPGA1_FIRMWARE, FPGA2_FIRMWARE }
Firmware information for skip list.
typedef struct iris::dist500::FirmwareController::_UpdateInformation UpdateInformation
Typedef for a container update information.
typedef std::map< iris::dist500::Dist500 *, UpdateInformation > UpdateResultMap
Maps sensor instances to container update information.
Public Types inherited from iris::dist500::Dist500Base
typedef std::set< unsigned short > IdSet
typedef std::list< iris::uip::messageTypeDef > MessageTypeDefinitionList
typedef std::map< unsigned short, std::string > ParameterGroups
typedef std::map< unsigned short, ParameterInfo > ParameterInfos
typedef void(* TRANSFER_CONFIGURATION_CALLBACK) (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback for sensor configuration transfers.
Public Member Functions
virtual SENSOR_RESULT configureSensorGroup (const FirmwareControllerList &slaves, const iris::configuration::CommunicationGroup::IpAddress &ipAddr, const iris::configuration::CommunicationGroup::IpAddress &netMask, const iris::configuration::CommunicationGroup::IpAddress &gwAddr, const unsigned short port, const iris::configuration::CommunicationGroup::IpAddress &sntp1Addr, const iris::configuration::CommunicationGroup::IpAddress &sntp2Addr, ConfigurationInterceptor &interceptor)
Configures a sensor as master and optionally one or more sensors as slaves to this master;.
virtual SENSOR_RESULT configureStandalone (const iris::configuration::CommunicationGroup::IpAddress &ipAddr, const iris::configuration::CommunicationGroup::IpAddress &netMask, const iris::configuration::CommunicationGroup::IpAddress &gwAddr, const unsigned short port, const iris::configuration::CommunicationGroup::IpAddress &sntp1Addr, const iris::configuration::CommunicationGroup::IpAddress &sntp2Addr, ConfigurationInterceptor &interceptor)
Configures one sensor as single sensor.
FirmwareController (iris::drivers::Sensor &sensor)
Constructor.
FirmwareFitHardwareResult firmwareFitsHardware (const std::string &hexFile, void *userData=0)
Checks if the given firmware matches the hardware.
bool firmwareFitsHardware (const std::string &hexFile, Dist500List &remainingGroupSensors, FirmwareFitHardwareResultMap &resultMap, void *userData=0)
Checks if the given firmware matches the hardware.
unsigned short getGroupIndex (void)
Returns the group index.
SensorGroup * getSensorGroup (void)
Returns the SensorGroup instance.
SensorInfo getSensorInfo (bool forceRefresh=false)
Retrieves information about the sensor.
bool hasSensorInfo (void) const
Checks whether a cached sensor info exists.
void invalidateSensorInfo (void)
Clears the sensor information cache.
virtual SENSOR_RESULT loadFpgaImage (const std::string &bitfileName, bool primary, void *userData, UPDATE_CALLBACK updateCallback)
Loads the primary or secondary FPGA bitfile (firmware)
virtual SENSOR_RESULT loadFpgaImage (const unsigned char *fileContents, unsigned int fileSize, bool primary, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performApplicationFirmwareUpdate (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback)
Updates the application firmware part from the given .LDR file.
virtual SENSOR_RESULT performApplicationFirmwareUpdate (char *hexfileContents, unsigned long hexfileSize, const std::string &hexfileName, const std::string &firmwareTimestamp, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performApplicationFirmwareVerification (const std::string &hexfileName, void *userData, UPDATE_CALLBACK verificationCallback)
virtual SENSOR_RESULT performApplicationFirmwareVerification (char *hexfileContents, unsigned long hexfileSize, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performBootloaderFirmwareUpdate (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback)
Updates the bootloader firmware part from the given .LDR file.
virtual SENSOR_RESULT performBootloaderFirmwareUpdate (char *hexfileContents, unsigned long hexfileSize, const std::string &hexfileName, const std::string &firmwareTimestamp, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performBootloaderFirmwareVerification (const std::string &hexfileName, void *userData, UPDATE_CALLBACK verificationCallback)
virtual SENSOR_RESULT performBootloaderFirmwareVerification (char *hexfileContents, unsigned long hexfileSize, void *userData, UPDATE_CALLBACK updateCallback)
bool performContainerUpdate (const std::string &containerFilename, UpdateResultMap &resultMap, bool checkSensorConsistency=true, void *userData=0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback=0)
Updates firmware and parameter from the given .D5FC file.
bool performContainerUpdate (const std::string &containerFilename, Dist500List &remainingGroupSensors, UpdateResultMap &resultMap, bool checkSensorConsistency=true, void *userData=0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback=0)
Updates firmware and parameter from the given .D5FC file.
bool performContainerUpdateDefaults (const std::string &containerFilename, Dist500List &remainingGroupSensors, UpdateResultMap &resultMap, bool checkSensorConsistency, bool defaultValues, void *userData=0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback=0)
Updates firmware and parameter from the given .D5FC file.
virtual SENSOR_RESULT performFpgaImageVerification (const std::string &bitfileName, bool primary, void *userData, UPDATE_CALLBACK updateCallback)
virtual SENSOR_RESULT performFpgaImageVerification (const unsigned char *fileContents, unsigned int fileSize, bool primary, void *userData, UPDATE_CALLBACK updateCallback)
void setGroupIndex (unsigned short gi)
Sets the sensor index within a group.
void setSensorGroup (SensorGroup *sg)
Sets the associated SensorGroip.
virtual SENSOR_RESULT writeApplicationFirmwareInfoBlock (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback)
Updates the application firmware info block according to the given .LDR file.
virtual SENSOR_RESULT writeBootloaderFirmwareInfoBlock (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback)
Updates the bootloader firmware info block according to the given .LDR file.
virtual ~FirmwareController ()
Destructor.
Public Member Functions inherited from iris::dist500::FlashController
SENSOR_RESULT eraseFirmware (iris::uip::firmware_type firmwareType)
eraseFirmware Erases a backup firmware in the sensor.
SENSOR_RESULT eraseMemory (unsigned long address)
Erases a Flash sector.
FlashController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT readFirmware (uip::ushort messageCount, iris::uip::firmware_type firmwareType, iris::uip::backup_type backupType, uip::ulong byteOffset, iris::uip::uchar *buffer, uip::ushort numberOfBytes)
readFirmware Reads the specified firmwareType
SENSOR_RESULT readMemory (unsigned long address, char *buffer, unsigned short byteCount)
Reads data from the flash.
SENSOR_RESULT switchFirmware (iris::uip::ulonglong uniqueRequestId, iris::uip::uchar firmwareFlagsCount, const iris::uip::firmware_type *firmwareTypeFlags)
switchFirmware Switches the specified type(s) of firmware.
SENSOR_RESULT writeFirmware (uip::ushort messageCount, iris::uip::firmware_type firmwareType, uip::ulong byteOffset, iris::uip::uchar *buffer, uip::ushort numberOfBytes)
writeFirmware Writes the specified firmwareType.
SENSOR_RESULT writeMemory (unsigned long address, char *buffer, unsigned short byteCount, bool verify=false)
Writes data into the Flash.
virtual ~FlashController ()
Destructor.
Public Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _legacyGetDeviceInfo (unsigned short group, unsigned short param, char *buffer)
Retrieves a device feature.
SENSOR_RESULT activateConfiguration (void)
activates a configuration that is already in RAM
SENSOR_RESULT captureDevice (char *application)
Captures the sensor: Marks the device as captured, which can be queried by getCaptureState.
SENSOR_RESULT checkSupportForMessage (const unsigned char command, const unsigned char version, const unsigned char subCommand, bool &isSupported)
checkSupportForMessage Checks if the sensor can respond to the specified message.
SENSOR_RESULT describeParameter (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info, const bool includeName=false)
describeParameter Returns ParameterInfo for the specified parameter which contains the type and value range.
SENSOR_RESULT determineTimeoutParameters (void)
Measures the timeout params (offset and factor) by doing some comnmunication tests.
Dist500Base (iris::drivers::Sensor &sensor)
Constructor.
UipMessage * doSendAndGetApplReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * doSendAndGetReply (int level, UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack or application level message and receives one or more replies.
UipMessage * doSendAndGetServiceReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a service level message and receives one or more replies.
UipMessage * doSendAndGetStackReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT echoTest (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Performs an echo test (pings the sensor)
SENSOR_RESULT getCaptureState (char *applicationBuffer, int maxLen)
Returns the capture state.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, unsigned short &len, bool stackLevel=false)
Reads a configuration parameter.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, bool stackLevel=false)
Reads a configuration parameter from RAM of the sensor (not from flash).
virtual void getConnectionName (char *buffer)
Returns a description for the connection.
virtual void getLocalConnectionName (char *buffer)
Returns an identifier string for local connection (eg IP:port); Currently returns a fixed dummy string.
virtual void getName (char *nameBuffer, int maxLen)
Returns a description for the sensor (ConnectionName + @ + UipAddress)
SENSOR_RESULT getParameterGroupIds (IdSet &groupIds)
Retrieves a set of existing group ids.
SENSOR_RESULT getParameterGroups (ParameterGroups &groups)
Retrieves a map (ParameterGroups) of group ids to group name.
SENSOR_RESULT getParameterIds (const unsigned short groupId, IdSet &paramIds)
SENSOR_RESULT getParameterInfos (const unsigned short groupId, ParameterInfos &infos, const bool includeNames=false)
SENSOR_RESULT getParameterName (const unsigned short groupId, const unsigned short paramId, std::string &paramName)
getParameterName Returns only the name of the specified parameter
iris::drivers::Sensor & getSensor (void)
Returns the associated Sensor instance (from Driver)
unsigned char getUipAddress (void)
Returns the UIP address (integer between 1-255).
SENSOR_RESULT getWorkingMode (iris::uip::working_mode &mode)
Retrieves the sensor working mode (iris::uip::working_mode).
SENSOR_RESULT listAllSupportedMessages (MessageTypeDefinitionList &buffer)
listAllSupportedMessages lists all messages the sensor can respond to.
SENSOR_RESULT lockImmanentData (void)
lockImmanentData
SENSOR_RESULT pingNeighbour (const unsigned char neighbourAddress, const unsigned short payloadLen, const unsigned short repetitions, const unsigned short timeoutMs, unsigned short &successCount, unsigned short &averageTimeMs)
Asks a sensor to ping one of its neighbours (same FA) for a given number of repetitions.
SENSOR_RESULT pingSensor (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Pings a sensor.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT releaseDevice (void)
Releases ("uncaptures") the sensor.
void resetTimeoutParameters (void)
Resets the timeout params to the default values (offset 0, factor 1.0)
SENSOR_RESULT restoreConfigurationFromFlash (void)
Copies the configuration from flash memory to RAM.
SENSOR_RESULT saveConfigurationToFlash (void)
Copies the configuration from RAM to flash memory.
UipMessage * sendAndGetApplReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * sendAndGetServiceReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
UipMessage * sendAndGetStackReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT sendUipCommand (char type, unsigned char version, char command, unsigned short payloadLen, char *payload, unsigned int timeoutMs, char &replyType, unsigned char &replyVersion, char &replyCommand, unsigned short &replyPayloadLen, char *replyPayloadBuffer)
Sends a "free" UIP command to the sensor and waits for the reply.
SENSOR_RESULT setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel=false)
Sets a configuration parameter in the sensor's RAM (not in the flash).
SENSOR_RESULT setConfigurationParameterIfKnown (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool &paramWasUnknown, bool stackLevel=false)
Like setConfigurationParameter but only if that parameter is known.
void setUipAddress (unsigned char)
setUipAddress Sets a new UIP address for communication with this sensor.
void setUipTimeout (const int timeoutMs)
Sets timeout used for UIP send and get reply methods (whereafter usually a retry is performed).
SENSOR_RESULT setWorkingMode (const iris::uip::working_mode mode)
Sets the sensor working mode.
SENSOR_RESULT unlockImmanentData (void)
unlockImmanentData
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
virtual ~Dist500Base ()
Destructor.
Static Public Member Functions
static bool firmwareFitsHardwareForSensors (const std::string &hexFile, Dist500List &sensorList, FirmwareFitHardwareResultMap &resultMap, void *userData=0)
Checks if the given firmware matches the hardware.
static bool getIrisOnlyUpdateAuthorized (void)
static bool performContainerUpdateForSensors (const std::string &containerFilename, Dist500List &sensorList, UpdateResultMap &resultMap, bool checkSensorConsistency=true, void *userData=0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback=0)
Updates firmware and parameter from the given .D5FC file.
static void setIrisOnlyUpdateAuthorized (bool authorized)
Static Public Member Functions inherited from iris::dist500::Dist500Base
static void disableAutomaticRetries (void)
disables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
static void enableAutomaticRetries (void)
enables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
Static Public Attributes
static const unsigned long ConfigurationDataFlashAddress = FlashStartAddress + 0x100000
static const unsigned long FIRMWARE_INFO_SIZE = 0x14C
static const unsigned long FIRMWARE_INFO_WITH_CRC_SIZE = 0x150
static const unsigned long FlashBankSize = 0x200000
static const unsigned long FlashSectorSize = 0x20000
static const unsigned long FlashStartAddress = 0x20000000
static const unsigned long START_FIRMWARE_INFO_APPL = 0x001FFEB0
static const unsigned long START_FIRMWARE_INFO_BOOT = 0x000FFEB0
Protected Types
typedef std::list< int32_t > ListFpgaFilesContainerIndex
typedef std::map< Dist500 *, SensorInformation > SensorInformationMap
Protected Types inherited from iris::dist500::Dist500Base
typedef std::map< unsigned short, ParameterInfo > GroupParameterInfos
typedef std::map< unsigned short, ParameterValue > GroupParameterValues
typedef std::set< int > NoRetryMessageHashSet
typedef std::bitset< 1024 > ReceptionFlags
Protected Member Functions
SENSOR_RESULT findBootloaderWatermark (bool &hasWatermark)
void hexFileCallback (const unsigned long address, const unsigned char *const data, const unsigned char len)
Callback (sensor-specific) for hex file decoding.
SENSOR_RESULT performFirmwarePartUpdate (const std::string &hexfileName, void *userData, UPDATE_CALLBACK updateCallback, bool application, bool onlyWriteInfo=false)
Updates a firmware part from the given .LDR file.
SENSOR_RESULT performFirmwarePartUpdate (char *hexfileContents, const unsigned long hexfileSize, const std::string firmwareFilename, const std::string &firmwareTimestamp, void *userData, UPDATE_CALLBACK updateCallback, bool application, bool onlyWriteInfo=false)
SENSOR_RESULT performFirmwarePartUpdate (iris::hexfiles::HexFileStreamReader &hex, const std::string &hexfileName, const std::string &firmwareTimestamp, void *userData, UPDATE_CALLBACK updateCallback, bool application, bool onlyWriteInfo=false)
SENSOR_RESULT performFirmwarePartVerification (hexfiles::HexFileStreamReader &hex, void *userData, UPDATE_CALLBACK verificationCallback, bool application)
Protected Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos, ReceptionFlags &receivedParameters, iris::uip::ushort &expectedCount)
SENSOR_RESULT _legacyReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _optimizedReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings, const bool sendEmptyIfDefault, ReceptionFlags &receivedParams, iris::uip::ushort &expectedCount)
This is internally used in optimized sensor configuration readouts.
SENSOR_RESULT _setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel, bool ignoreUnknownParamErrors, bool &paramWasUnknown)
SENSOR_RESULT _writeConfiguration (iris::configuration::Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
bool automaticRetriesSupported (UipMessage *message)
Checks if automatic retries are currently supported for the specified message.
SENSOR_RESULT describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos)
describeAllGroupParametersWithoutNames Gets descriptions (GroupParameterInfos) of parameters within the specified configuration group.
SENSOR_RESULT describeParameterWithoutName (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info)
describeParameterWithoutName Gets type and value range information for the specified parameter.
SENSOR_RESULT getGroupName (const unsigned short groupId, std::string &groupName)
getGroupName Gets the name of the specified configuration group.
float getTimeoutFactor (void) const
Returns the timeout factor.
unsigned long getTimeoutOffset (void) const
Returns the timeout offset.
void initializeNoRetryMessageHashSet (void)
These are the messages that are not automatically repeated in case no reply arrives.
SENSOR_RESULT readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings=true, const bool sendEmptyIfDefault=true)
Used for sensor configuration readout, returns a map with parameter values for the specified configuration group.
void registerNoRetryMessage (unsigned char type, unsigned char version, unsigned char command)
Makes the specified message not be automatically resent if no replay arrives.
SENSOR_RESULT requestKeyPuzzle (unsigned short &puzzleLen, unsigned char *puzzleBuffer)
SENSOR_RESULT unlockImmanentData (const unsigned short keyLen, const unsigned char *key)
unlockImmanentData
Static Protected Member Functions
static void _hexFileCallback (void *userData, const unsigned long address, const unsigned char *const data, const unsigned char len)
Static (global) callback for hex file decoding.
static bool checkSensorsConsistency (Dist500List &sensorList, UpdateResultMap &resultMap)
Check if all sensors of a group exist.
static void configurationContainerCallback (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback function for configuration parameter update.
static SENSOR_RESULT findFirmwareInfoWatermark (bool &hasWatermark, char *&infoStart)
Checks is a firmware info watermark in the give firmware.
static bool firmwareFitsHardwareCheck (iris::hexfiles::HexFileStreamReader &hexReader, const std::string &hexfileName, Dist500 *sensor, FirmwareFitHardwareResult &fitResult, void *userData)
Performs the check for one sensor.
static void getDefaultSensorSerialPrefix (std::map< uint8_t, uint32_t > &prefixMap)
getDefaultSensorSerialPrefix
static void hexFileReleaseInfoCallback (void *userData, const unsigned long address, const unsigned char *const data, const unsigned char len)
Static (global) callback for hex file decoding.
static bool performContainerFirmwareUpdate (const std::string &containerFilename, Dist500List &sensorList, UpdateResultMap &resultMap, bool checkSensorConsistency, bool defaultValues, void *userData, CONTAINER_UPDATE_CALLBACK containerUpdateCallback)
Performs the container firmware update from the given .D5FC file.
static bool performContainerParameterUpdate (Dist500 &sensor, iris::legacy::Dist500FirmwareContainerDecoder &decoder, iris::configuration::Dist500Configuration &config, iris::dist500::Dist500Base::ConfigurationMismatches &mismatches, bool defaultValues, UpdateResultMap &resultMap, void *userData)
Performs configuration parameter update from container file.
static bool performFirmwareFitsHardwareCheck (const std::string &hexFile, Dist500List &sensorList, FirmwareFitHardwareResultMap &resultMap, void *userData)
Performs the checks if the given firmware matches the hardware.
static void resetToDefaultOperation (iris::configuration::Dist500Configuration &config)
Resets all sensor configuration data with certain exceptions needed to enable default operation of sensor.
static bool updateContainerApplication (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, bool &skipped, void *userData)
Performs a application firmware update from container file.
static void updateContainerCallback (void *userData, unsigned int step, unsigned int totalSteps, double stepPercentage, double totalPercentage)
Callback function container update.
static bool updateContainerCommunication (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, bool &skipped, void *userData)
Performs a communication firmware update from container file.
static bool updateContainerFpga (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, bool primary, bool skipFpgaRelease, bool &skipped, void *userData)
Performs a FPGA firmware update from container file.
static bool verifyContainerApplication (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, void *userData)
Performs a application firmware verifcation from container file.
static bool verifyContainerCommunication (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, void *userData)
Performs a communication firmware verifcation from container file.
static bool verifyContainerFpga (Dist500 &d5, struct iris::legacy::_EMBEDDED_FILE &file, bool primary, bool skipFpgaRelease, void *userData)
Performs a FPGA firmware verifcation from container file.
static void waitForSensors (Dist500List &sensors, ContainerUpdateUserData &containerUpdateUserData, unsigned int timeMs, unsigned int intervals)
waitForSensors Waits for sensors and invokes callback for progress bar update
Static Protected Member Functions inherited from iris::dist500::Dist500Base
static void handleSpontaneousWorkingModeMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for U 2.0.
Protected Attributes
bool determineHexFileAddressRange
Indicated whether addresses are to be evaluated (true) or if data is to be copied to firmware buffer (false)
char * firmware
Buffer for firmware, only used temporarily (otherwise 0)
unsigned long firmwareDecodedSize
firmwareDecodedSize Stores length of binary data that was decoded from the Intel HEX file
unsigned short groupIndex
Contraing the sensor index within the group.
unsigned long maxHexFileAddress
Holds the maximum address in a hex file.
unsigned long minHexFileAddress
Holds the minimum address in a hex file.
SensorGroup * sensorGroup
Refres to the SensorGtroup, if any.
SensorInfo * sensorInfo
May hold a SensorInfo instance for caching (0 if unused)
Protected Attributes inherited from iris::dist500::Dist500Base
SpontaneousHandlers handlers
Handler manger for spontaeous UIP messages (sub-command *)
NoRetryMessageHashSet noRetryMessageHashSet
iris::drivers::Sensor & sensor
Reference to associatee driver's Sensor object.
float timeoutFactor
Factor to applied to standard timeouts.
unsigned long timeoutOffset
Constant offset to be applied to standard timeouts.
unsigned char uipAddress
UIP address of sensor.
int uipTimeout
Timeout in ms used for UIP send and get reply methods.
Static Protected Attributes
static bool determineHexFileReleaseInfoAddressRange
Indicated whether addresses are to be evaluated (true) or if data is to be copied to firmware buffer (false)
static bool irisOnlyUpdateAuthorized
static const unsigned int MAX_FPGA_BITFILE_SIZE = MAX_FPGA_IMAGE_SIZE + 1024
static const unsigned int MAX_FPGA_IMAGE_SIZE = 128 * 1024
static unsigned long maxHexFileReleaseInfoAddress
Holds the maximum address in a hex file.
static unsigned long minHexFileReleaseInfoAddress
Holds the minimum address in a hex file.
static char * releaseInfoFirmware
Buffer for firmware.
Static Protected Attributes inherited from iris::dist500::Dist500Base
static bool automaticRetriesDisabled = false
Detailed Description
Implements DIST500 functions related to firmware and configuration data.
Member Enumeration Documentation
enum iris::dist500::FirmwareController::CONTAINER_PARAMETER_RESULT
Container paramter update result codes.
Enumerator
CONTAINER_WRONG_PARAMETER_VALUE
Parameter value not valid in the container file.
Parameter has the default value
CONTAINER_UNKNOWN_PARAMETER
The Parameter is unknown.
CONTAINER_UNKNOWN_SENSOR_PARAMETER
The Parameter is unknown for the sensor.
CONTAINER_PARAMETER_NOT_WRITE
Parameter could not be written.
CONTAINER_PARAMETER_WRONG_UPDATE_STATE
Parameter has the wrong update state and could not been updated.
enum iris::dist500::FirmwareController::CONTAINER_UPDATE_RESULT
Container file update result codes.
Enumerator
CONTAINER_UPDATE_PASSED
Update OK.
CONTAINER_UPDATE_FAILED
General failure.
CONTAINER_OPEN_FILE_FAILED
Cannot open container file.
CONTAINER_SET_WORKING_MODE_FAILED
Set working mode failed.
CONTAINER_GROUP_INCOMPLETE
Incomplete sensor group.
CONTAINER_APPLICATION_UPDATE_FAILED
Application firmware update has failed.
CONTAINER_APPLICATION_VERIFY_FAILED
Application firmware verification has failed.
CONTAINER_COMMUNICATION_UPDATE_FAILED
Communication firmware update has failed.
CONTAINER_COMMUNICATION_VERIFY_FAILED
Communication firmware verification has failed.
CONTAINER_FPGA_UPDATE_FAILED
FPGA firmware update has failed.
CONTAINER_FIRST_FPGA_UPDATE_FAILED
First FPGA firmware update has failed.
CONTAINER_SECOND_FPGA_UPDATE_FAILED
Second FPGA firmware update has failed.
CONTAINER_FIRST_FPGA_VERIFY_FAILED
First FPGA firmware verification has failed.
CONTAINER_SECOND_FPGA_VERIFY_FAILED
Second FPGA firmware verification has failed.
CONTAINER_RESTART_FAILED
Sensor restart has failed.
CONTAINER_READ_CONFIGURATION_FAILED
Reading the configuration data has failed.
CONTAINER_CHANGE_CONFIGURATION_FAILED
Changing the configuration data has failed.
CONTAINER_GET_UPDATE_PARAMETER_FAILED
Getting update parameter from container file failed.
CONTAINER_WRITE_CONFIG_FAILED
Writing configuration data failed.
CONTAINER_SAVE_CONFIG_FAILED
Saving the configuration data failed.
UNSUPPORTED_CONTAINER_FILE
The container file has unsupported data contents.
CONTAINER_READ_FPGA_IMAGE_FAILED
One or more fpga image could not be read.
CONTAINER_FPGA_IMAGE_MISMATCH
The container file has a wrong number of fpga images.
CONTAINER_RESTORE_CONFIGURATION_FROM_FLASH_FAILED
Restore the configuration data from flash has failed.
enum iris::dist500::FirmwareController::FirmwareFitHardwareResult
Result of the query if the firmware matches the Hardware.
Enumerator
FIRWARE_CHECK_PASSED
Firmware fits the hardware.
FIRWARE_CHECK_FAILED
General check failure.
NO_VALID_FILE_EXTENSION
No valid file extension found.
CANNOT_OPEN_CONTAINER
Open the container file failed.
NO_APPLICATION_FOUND
No application file found in the container file.
CANNOT_DECODE_HEXFILE
Decode the firmware file failed.
HEXFILE_ADDRESS_RANGE_FAULTY
Address range of the firmware file is wrong.
ALLOC_MEMORY_FAILED
Allocate memory for firmware file failed.
NO_IRIS_AUTHENTICATION
Operation is failed because no iris authentication is present.
NO_LDR_FILE_FOUND
No firmware file was found.
CANNOT_READ_FIRMWARE_VERSION
Firmware version can not be read from the file name.
CHECK_MESSAGE_SUPPORT_FAILED
Message verification failed.
GET_REVISION_CODE_FAILED
Read revision code from sensor failed.
UNKNOWN_REVISION_CODE
Revision code of the sensor is unknown.
FIRMWARE_NOT_MATCH_TO_HARDWARE
Firmware does not match the hardware.
Constructor & Destructor Documentation
iris::dist500::FirmwareController::FirmwareController (iris::drivers::Sensor & sensor)
Constructor.
Parameters
sensor
Member Function Documentation
void iris::dist500::FirmwareController::_hexFileCallback (void * userData, const unsigned long address, const unsigned char *const data, const unsigned char len) static protected
Static (global) callback for hex file decoding.
Parameters
userData User-defined additional parameter
address Address of line data
data Pointer to line data
len Number of bytes in line
References hexFileCallback().
bool iris::dist500::FirmwareController::checkSensorsConsistency (Dist500List & sensorList, UpdateResultMap & resultMap) static protected
Check if all sensors of a group exist.
Parameters
sensorList List of sensors to check
resultMap Map receiving the update result for every sensor
Returns
Operation result true = all sensors are consistent, false = at least one group inconsistent
References CONTAINER_GROUP_INCOMPLETE, CONTAINER_READ_CONFIGURATION_FAILED, iris::dist500::Dist500Base::getConfigurationParameter(), iris::dist500::OPERATION_PASSED, and iris::dist500::Dist500Base::sensor.
Referenced by performContainerFirmwareUpdate().
void iris::dist500::FirmwareController::configurationContainerCallback (void * userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId) static protected
Callback function for configuration parameter update.
Parameters
userData User-defined additional parameter
index Index of current paramter
total Total parameters
groupId Parameter group id
paramId Parameter id
References updateContainerCallback().
Referenced by performContainerParameterUpdate().
SENSOR_RESULT iris::dist500::FirmwareController::configureSensorGroup (const FirmwareControllerList & slaves, const iris::configuration::CommunicationGroup::IpAddress & ipAddr, const iris::configuration::CommunicationGroup::IpAddress & netMask, const iris::configuration::CommunicationGroup::IpAddress & gwAddr, const unsigned short port, const iris::configuration::CommunicationGroup::IpAddress & sntp1Addr, const iris::configuration::CommunicationGroup::IpAddress & sntp2Addr, ConfigurationInterceptor & interceptor) virtual
Configures a sensor as master and optionally one or more sensors as slaves to this master;.
Parameters
slaves (Possibly empty) list of slaves
ipAddr IP address of the master sensor
netMask Network mask of the master sensor
gwAddr Getway address of the master sensor
port UIP IP port address. This parameter currently has no effect. The port address is fixed.
sntp1Addr Preferred SNTP server address
sntp2Addr Alternative SNTP server address
interceptor Class to configure additional parameters of the group such as function area address.
Returns
Operation result
References iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::readConfiguration(), iris::dist500::Dist500Base::restoreConfigurationFromFlash(), iris::dist500::Dist500Base::saveConfigurationToFlash(), and iris::dist500::Dist500Base::writeConfiguration().
Referenced by configureStandalone().
SENSOR_RESULT iris::dist500::FirmwareController::configureStandalone (const iris::configuration::CommunicationGroup::IpAddress & ipAddr, const iris::configuration::CommunicationGroup::IpAddress & netMask, const iris::configuration::CommunicationGroup::IpAddress & gwAddr, const unsigned short port, const iris::configuration::CommunicationGroup::IpAddress & sntp1Addr, const iris::configuration::CommunicationGroup::IpAddress & sntp2Addr, ConfigurationInterceptor & interceptor) virtual
Configures one sensor as single sensor.
Parameters
ipAddr IP address of the master sensor
netMask Network mask of the master sensor
gwAddr Getway address of the master sensor
port UIP IP port address. This parameter currently has no effect. The port address is fixed.
sntp1Addr Preferred SNTP server address
sntp2Addr Alternative SNTP server address
interceptor Class to configure additional parameters such as function area address.
Returns
References configureSensorGroup().
SENSOR_RESULT iris::dist500::FirmwareController::findFirmwareInfoWatermark (bool & hasWatermark, char *& infoStart) static protected
Checks is a firmware info watermark in the give firmware.
Parameters
hasWatermark Reference to the result of the check.
infoStart Address pointer to the start of the founded firmware release info block
Returns
Operation result
References maxHexFileReleaseInfoAddress, iris::dist500::OPERATION_PASSED, and releaseInfoFirmware.
Referenced by firmwareFitsHardwareCheck().
FirmwareController::FirmwareFitHardwareResult iris::dist500::FirmwareController::firmwareFitsHardware (const std::string & hexFile, void * userData = 0)
Checks if the given firmware matches the hardware.
Parameters
hexFile Path to the firmware hex file.
userData User-defined additional parameter
Returns
Result of the query if the firmware matches the hardware.
References FIRWARE_CHECK_FAILED, and performFirmwareFitsHardwareCheck().
bool iris::dist500::FirmwareController::firmwareFitsHardware (const std::string & hexFile, Dist500List & remainingGroupSensors, FirmwareFitHardwareResultMap & resultMap, void * userData = 0)
Checks if the given firmware matches the hardware.
Parameters
hexFile Path to the firmware hex file.
remainingGroupSensors List of slave sensors
resultMap Map receiving the check result for every sensor
userData User-defined additional parameter
Returns
Operation result true = Check for all sensors passed, false = Check for at least one sensor failed
References performFirmwareFitsHardwareCheck(), and iris::dist500::Dist500Base::sensor.
bool iris::dist500::FirmwareController::firmwareFitsHardwareCheck (iris::hexfiles::HexFileStreamReader & hexReader, const std::string & hexfileName, Dist500 * sensor, FirmwareFitHardwareResult & fitResult, void * userData) static protected
Performs the check for one sensor.
Parameters
hexReader Reference of HexFileStreamReader
hexfileName Firmware filename
sensor Sensor instance
fitResult Check result
userData User-defined additional parameter
Returns
Operation result true = Check passed, false = Check failed
References ALLOC_MEMORY_FAILED, CANNOT_DECODE_HEXFILE, CANNOT_READ_FIRMWARE_VERSION, CHECK_MESSAGE_SUPPORT_FAILED, iris::dist500::Dist500Base::checkSupportForMessage(), iris::hexfiles::HexFileReader::decodeFile(), determineHexFileReleaseInfoAddressRange, findFirmwareInfoWatermark(), FIRMWARE_NOT_MATCH_TO_HARDWARE, FIRWARE_CHECK_FAILED, FIRWARE_CHECK_PASSED, GET_REVISION_CODE_FAILED, iris::dist500::Dist500::getSensorRevisionCode(), HEXFILE_ADDRESS_RANGE_FAULTY, hexFileReleaseInfoCallback(), maxHexFileReleaseInfoAddress, minHexFileReleaseInfoAddress, NO_IRIS_AUTHENTICATION, iris::dist500::OPERATION_PASSED, releaseInfoFirmware, UNKNOWN_REVISION_CODE, and iris::dist500::FirmwareController::FirmwareReleaseInfo::Version.
Referenced by performFirmwareFitsHardwareCheck().
bool iris::dist500::FirmwareController::firmwareFitsHardwareForSensors (const std::string & hexFile, Dist500List & sensorList, FirmwareFitHardwareResultMap & resultMap, void * userData = 0) static
Checks if the given firmware matches the hardware.
Parameters
hexFile Path to the firmware hex file.
sensorList List of sensors
resultMap Map receiving the check result for every sensor
userData User-defined additional parameter
Returns
Operation result true = Check for all sensors passed, false = Check for at least one sensor failed
References performFirmwareFitsHardwareCheck().
void iris::dist500::FirmwareController::getDefaultSensorSerialPrefix (std::map< uint8_t, uint32_t > & prefixMap) static protected
getDefaultSensorSerialPrefix
Parameters
prefixMap
Referenced by performContainerFirmwareUpdate().
unsigned short iris::dist500::FirmwareController::getGroupIndex (void)
Returns the group index.
Returns
Sensor index within group
References groupIndex.
SensorGroup * iris::dist500::FirmwareController::getSensorGroup (void)
Returns the SensorGroup instance.
Returns
Associated SensorGroup
References sensorGroup.
SensorInfo iris::dist500::FirmwareController::getSensorInfo (bool forceRefresh = false) virtual
Retrieves information about the sensor.
Parameters
forceRefresh
Returns
SensorInfo instance with relevant data
Implements iris::dist500::SensorInfoProvider.
References iris::dist500::Dist500Base::_legacyGetDeviceInfo(), iris::dist500::Dist500Base::getCaptureState(), iris::dist500::Dist500Base::getConfigurationParameter(), iris::drivers::Sensor::getDriver(), iris::drivers::Driver::getName(), iris::drivers::Sensor::getUrl(), iris::drivers::Driver::getVersion(), groupIndex, invalidateSensorInfo(), iris::dist500::OPERATION_PASSED, iris::dist500::Dist500Base::sensor, and sensorInfo.
Referenced by performContainerFirmwareUpdate().
bool iris::dist500::FirmwareController::hasSensorInfo (void) const virtual
Checks whether a cached sensor info exists.
Returns
true if info is available in cache, false otherwise
Implements iris::dist500::SensorInfoProvider.
References sensorInfo.
void iris::dist500::FirmwareController::hexFileCallback (const unsigned long address, const unsigned char *const data, const unsigned char len) protected
Callback (sensor-specific) for hex file decoding.
Parameters
address Address of line data
data Pointer to line data
len Number of bytes in line*
References determineHexFileAddressRange, firmware, and firmwareDecodedSize.
Referenced by _hexFileCallback().
void iris::dist500::FirmwareController::hexFileReleaseInfoCallback (void * userData, const unsigned long address, const unsigned char *const data, const unsigned char len) static protected
Static (global) callback for hex file decoding.
Parameters
userData User-defined additional parameter
address Address of line data
data Pointer to line data
len Number of bytes in line
References determineHexFileReleaseInfoAddressRange, maxHexFileReleaseInfoAddress, minHexFileReleaseInfoAddress, and releaseInfoFirmware.
Referenced by firmwareFitsHardwareCheck().
SENSOR_RESULT iris::dist500::FirmwareController::loadFpgaImage (const std::string & bitfileName, bool primary, void * userData, UPDATE_CALLBACK updateCallback) virtual
Loads the primary or secondary FPGA bitfile (firmware)
Parameters
bitfileName Filename of the .BIT file containing the firmware
primary true if primary image is to be loaded, false for secondary image
userData User-defined additional parameter for callback
updateCallback Callback function for progress updates
Returns
Operation result
References iris::dist500::OPERATION_FAILED.
Referenced by updateContainerFpga().
SENSOR_RESULT iris::dist500::FirmwareController::performApplicationFirmwareUpdate (const std::string & hexfileName, void * userData, UPDATE_CALLBACK updateCallback) virtual
Updates the application firmware part from the given .LDR file.
Parameters
hexfileName Filename of the .LDR file containing the firmware
userData User-defined additional parameter for callback
updateCallback Callback function for progress updates
Returns
Operation result
References performFirmwarePartUpdate().
Referenced by updateContainerApplication().
SENSOR_RESULT iris::dist500::FirmwareController::performBootloaderFirmwareUpdate (const std::string & hexfileName, void * userData, UPDATE_CALLBACK updateCallback) virtual
Updates the bootloader firmware part from the given .LDR file.
Parameters
hexfileName Filename of the .LDR file containing the firmware
userData User-defined additional parameter for callback
updateCallback Callback function for progress updates
Returns
Operation result
References performFirmwarePartUpdate().
Referenced by updateContainerCommunication().
bool iris::dist500::FirmwareController::performContainerFirmwareUpdate (const std::string & containerFilename, Dist500List & sensorList, UpdateResultMap & resultMap, bool checkSensorConsistency, bool defaultValues, void * userData, CONTAINER_UPDATE_CALLBACK containerUpdateCallback) static protected
Performs the container firmware update from the given .D5FC file.
performContainerFirmwareUpdate performs a container firmware update
Parameters
containerFilename Filename of the .D5FC file containing the firmware and parameter
sensorList List of sensors to be updated
resultMap Map receiving the update result for every sensor
defaultValues Default values Flag true = Before the parameter update, all parameters get their default value, false = no default values
userData User-defined additional parameter
containerUpdateCallback Callback function for progress updates
Returns
Operation result true = Update for all sensors passed, false = Update for at least one sensor failed
false if something is wrong with the container file
References checkSensorsConsistency(), iris::uip::config_and_update_mode, iris::dist500::CONFIG_STEPS, iris::dist500::FirmwareController::ContainerUpdateUserData::configurationAvailable, CONTAINER_APPLICATION_UPDATE_FAILED, CONTAINER_APPLICATION_VERIFY_FAILED, CONTAINER_COMMUNICATION_UPDATE_FAILED, CONTAINER_COMMUNICATION_VERIFY_FAILED, CONTAINER_FIRST_FPGA_UPDATE_FAILED, CONTAINER_FIRST_FPGA_VERIFY_FAILED, CONTAINER_FPGA_IMAGE_MISMATCH, CONTAINER_FPGA_UPDATE_FAILED, CONTAINER_READ_FPGA_IMAGE_FAILED, CONTAINER_RESTART_FAILED, CONTAINER_SECOND_FPGA_UPDATE_FAILED, CONTAINER_SECOND_FPGA_VERIFY_FAILED, CONTAINER_SET_WORKING_MODE_FAILED, CONTAINER_UPDATE_FAILED, CONTAINER_UPDATE_PASSED, iris::dist500::FirmwareController::ContainerUpdateUserData::containerStep, iris::dist500::FirmwareController::ContainerUpdateUserData::containerTotalSteps, iris::dist500::FirmwareController::ContainerUpdateUserData::containerUpdateCallback, iris::dist500::FirmwareController::ContainerUpdateUserData::defaultValues, iris::dist500::FirmwareController::_UpdateInformation::firmwareSkippedList, iris::dist500::FirmwareController::ContainerUpdateUserData::firmwareUpdateSteps, iris::dist500::Dist500Base::getConfigurationParameter(), getDefaultSensorSerialPrefix(), iris::dist500::SensorInfo::getDriverName(), getSensorInfo(), iris::dist500::SensorInfo::getSerial(), iris::dist500::OPERATION_PASSED, iris::dist500::FirmwareController::_UpdateInformation::parameterUpdateInformation, performContainerParameterUpdate(), iris::dist500::Dist500Base::pingSensor(), iris::dist500::Dist500::resetDsp(), iris::dist500::RESTART_STEP, iris::dist500::Dist500Base::sensor, iris::dist500::FirmwareController::ContainerUpdateUserData::sensor, iris::dist500::Dist500Base::setWorkingMode(), UNSUPPORTED_CONTAINER_FILE, updateContainerApplication(), updateContainerCallback(), updateContainerCommunication(), updateContainerFpga(), iris::dist500::FirmwareController::_UpdateInformation::updateResultCode, iris::dist500::FirmwareController::ContainerUpdateUserData::updateState, iris::dist500::FirmwareController::ContainerUpdateUserData::userData, verifyContainerApplication(), verifyContainerCommunication(), verifyContainerFpga(), and waitForSensors().
Referenced by performContainerUpdateDefaults(), and performContainerUpdateForSensors().
bool iris::dist500::FirmwareController::performContainerParameterUpdate (Dist500 & sensor, iris::legacy::Dist500FirmwareContainerDecoder & decoder, iris::configuration::Dist500Configuration & config, iris::dist500::Dist500Base::ConfigurationMismatches & mismatches, bool defaultValues, UpdateResultMap & resultMap, void * userData) static protected
Performs configuration parameter update from container file.
Parameters
sensor Sensor reference
decoder Firmware container decoder reference
config Reference to sensor configuration data
mismatches Reference to sensor configuration mismatches
defaultValues Default values Flag true = Before the parameter update, all parameters get their default value, false = no default values
resultMap Map receiving the update result for every sensor
userData User-defined additional parameter
Returns
Operation result true = verify succesful, false = verify failed
References configurationContainerCallback(), CONTAINER_CHANGE_CONFIGURATION_FAILED, CONTAINER_GET_UPDATE_PARAMETER_FAILED, CONTAINER_PARAMETER_NOT_WRITE, CONTAINER_PARAMETER_WRONG_UPDATE_STATE, CONTAINER_READ_CONFIGURATION_FAILED, CONTAINER_RESTORE_CONFIGURATION_FROM_FLASH_FAILED, CONTAINER_SAVE_CONFIG_FAILED, CONTAINER_UNKNOWN_PARAMETER, CONTAINER_UNKNOWN_SENSOR_PARAMETER, CONTAINER_WRITE_CONFIG_FAILED, CONTAINER_WRONG_PARAMETER_VALUE, iris::dist500::FirmwareController::_ParameterUpdateInformation::groupId, iris::dist500::OPERATION_PASSED, iris::dist500::FirmwareController::_ParameterUpdateInformation::parameterResult, iris::dist500::FirmwareController::_ParameterUpdateInformation::paramId, iris::dist500::Dist500Base::readConfiguration(), resetToDefaultOperation(), iris::dist500::Dist500Base::restoreConfigurationFromFlash(), iris::dist500::Dist500Base::saveConfigurationToFlash(), iris::dist500::Dist500Base::sensor, updateContainerCallback(), and iris::dist500::Dist500Base::writeConfiguration().
Referenced by performContainerFirmwareUpdate().
bool iris::dist500::FirmwareController::performContainerUpdate (const std::string & containerFilename, UpdateResultMap & resultMap, bool checkSensorConsistency = true, void * userData = 0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback = 0)
Updates firmware and parameter from the given .D5FC file.
Parameters
containerFilename Filename of the .D5FC file containing the firmware and parameter
resultMap Map receiving the update result for every sensor
checkSensorConsistency Check consistency from group sensors true = all sensors of a group must be included in the List and present, false = no check It is strongly recommended to set this parameter to true. Only set to false if you know what you are doing.
userData User-defined additional parameter
containerUpdateCallback Callback function for progress updates
Returns
Operation result true = Update for all sensors passed, false = Update for at least one sensor failed
References performContainerUpdateForSensors().
bool iris::dist500::FirmwareController::performContainerUpdate (const std::string & containerFilename, Dist500List & remainingGroupSensors, UpdateResultMap & resultMap, bool checkSensorConsistency = true, void * userData = 0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback = 0)
Updates firmware and parameter from the given .D5FC file.
Parameters
containerFilename Filename of the .D5FC file containing the firmware and parameter
remainingGroupSensors List of slave sensors
resultMap Map receiving the update result for every sensor
checkSensorConsistency Check consistency from group sensors true = all sensors of a group must be included in the List and present, false = no check It is strongly recommended to set this parameter to true. Only set to false if you know what you are doing.
userData User-defined additional parameter
containerUpdateCallback Callback function for progress updates
Returns
Operation result true = Update for all sensors passed, false = Update for at least one sensor failed
References performContainerUpdateForSensors(), and iris::dist500::Dist500Base::sensor.
bool iris::dist500::FirmwareController::performContainerUpdateDefaults (const std::string & containerFilename, Dist500List & remainingGroupSensors, UpdateResultMap & resultMap, bool checkSensorConsistency, bool defaultValues, void * userData = 0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback = 0)
Updates firmware and parameter from the given .D5FC file.
Parameters
containerFilename Filename of the .D5FC file containing the firmware and parameter
remainingGroupSensors List of slave sensors
resultMap Map receiving the update result for every sensor
checkSensorConsistency Check consistency from group sensors true = all sensors of a group must be included in the List and present, false = no check It is strongly recommended to set this parameter to true. Only set to false if you know what you are doing.
defaultValues Default values Flag true = Before the parameter update, all parameters get their default value, false = no default values
userData User-defined additional parameter
containerUpdateCallback Callback function for progress updates
Returns
Operation result true = Update for all sensors passed, false = Update for at least one sensor failed
References performContainerFirmwareUpdate(), and iris::dist500::Dist500Base::sensor.
bool iris::dist500::FirmwareController::performContainerUpdateForSensors (const std::string & containerFilename, Dist500List & sensorList, UpdateResultMap & resultMap, bool checkSensorConsistency = true, void * userData = 0, CONTAINER_UPDATE_CALLBACK containerUpdateCallback = 0) static
Updates firmware and parameter from the given .D5FC file.
Parameters
containerFilename Filename of the .D5FC file containing the firmware and parameter
sensorList List of sensors to update
resultMap Map receiving the update result for every sensor
checkSensorConsistency Check consistency from group sensors true = all sensors of a group must be included in the List and present, false = no check It is strongly recommended to set this parameter to true. Only set to false if you know what you are doing.
userData User-defined additional parameter
containerUpdateCallback Callback function for progress updates
Returns
Operation result true = Update for all sensors passed, false = Update for at least one sensor failed
References performContainerFirmwareUpdate().
Referenced by performContainerUpdate().
bool iris::dist500::FirmwareController::performFirmwareFitsHardwareCheck (const std::string & hexFile, Dist500List & sensorList, FirmwareFitHardwareResultMap & resultMap, void * userData) static protected
Performs the checks if the given firmware matches the hardware.
Parameters
hexFile Path to the firmware hex file.
sensorList List of sensors
resultMap Map receiving the check result for every sensor
userData User-defined additional parameter
Returns
Operation result true = Check for all sensors passed, false = Check for at least one sensor failed
References CANNOT_OPEN_CONTAINER, firmwareFitsHardwareCheck(), FIRWARE_CHECK_FAILED, FIRWARE_CHECK_PASSED, NO_APPLICATION_FOUND, NO_VALID_FILE_EXTENSION, and iris::dist500::Dist500Base::sensor.
Referenced by firmwareFitsHardware(), and firmwareFitsHardwareForSensors().
SENSOR_RESULT iris::dist500::FirmwareController::performFirmwarePartUpdate (const std::string & hexfileName, void * userData, UPDATE_CALLBACK updateCallback, bool application, bool onlyWriteInfo = false) protected
Updates a firmware part from the given .LDR file.
Parameters
hexfileName Filename of the .LDR file containing the firmware
userData User-defined additional parameter
updateCallback Callback function for progress updates
application Flag indicating whether the application part is to be updated (true) or the bootloader part (false)
onlyWriteInfo Flag indicating whether to only update the firmware info block and leave the firmware itself untouched (true = info only, false = full update)
Returns
Operation result
Referenced by performApplicationFirmwareUpdate(), performBootloaderFirmwareUpdate(), writeApplicationFirmwareInfoBlock(), and writeBootloaderFirmwareInfoBlock().
void iris::dist500::FirmwareController::resetToDefaultOperation (iris::configuration::Dist500Configuration & config) static protected
Resets all sensor configuration data with certain exceptions needed to enable default operation of sensor.
Parameters
config Reference to sensor configuration data
Referenced by performContainerParameterUpdate().
void iris::dist500::FirmwareController::setGroupIndex (unsigned short gi)
Sets the sensor index within a group.
Parameters
gi Sensor index within group
References groupIndex.
Referenced by iris::dist500::SensorGroup::addSensor().
void iris::dist500::FirmwareController::setSensorGroup (SensorGroup * sg)
Sets the associated SensorGroip.
Parameters
sg SensorGroup instance
References sensorGroup.
Referenced by iris::dist500::SensorGroup::addSensor().
bool iris::dist500::FirmwareController::updateContainerApplication (Dist500 & d5, struct iris::legacy::_EMBEDDED_FILE & file, bool & skipped, void * userData) static protected
Performs a application firmware update from container file.
Parameters
d5 Sensor instance
file Application firmware file
skipped Flag for skipped firmware true = firmware was skipped, false = otherwise
userData User-defined additional parameter
Returns
Operation result true = update succesful, false = update failed
References iris::dist500::Dist500Base::getConfigurationParameter(), iris::dist500::OPERATION_PASSED, performApplicationFirmwareUpdate(), and updateContainerCallback().
Referenced by performContainerFirmwareUpdate().
void iris::dist500::FirmwareController::updateContainerCallback (void * userData, unsigned int step, unsigned int totalSteps, double stepPercentage, double totalPercentage) static protected
Callback function container update.
Parameters
userData User-defined additional parameter
step Current step
totalSteps Total number of steps
stepPercentage Progress within current step
totalPercentage Total progress
References iris::dist500::CONFIG_STEPS, iris::dist500::FirmwareController::ContainerUpdateUserData::configurationAvailable, iris::dist500::FirmwareController::ContainerUpdateUserData::containerStep, iris::dist500::FirmwareController::ContainerUpdateUserData::containerTotalSteps, iris::dist500::FirmwareController::ContainerUpdateUserData::containerUpdateCallback, iris::dist500::FirmwareController::ContainerUpdateUserData::defaultValues, iris::dist500::FirmwareController::ContainerUpdateUserData::firmwareUpdateSteps, iris::dist500::RESTART_STEP, iris::dist500::Dist500Base::sensor, iris::dist500::FirmwareController::ContainerUpdateUserData::sensor, iris::dist500::FirmwareController::ContainerUpdateUserData::updateState, and iris::dist500::FirmwareController::ContainerUpdateUserData::userData.
Referenced by configurationContainerCallback(), performContainerFirmwareUpdate(), performContainerParameterUpdate(), updateContainerApplication(), updateContainerCommunication(), updateContainerFpga(), verifyContainerApplication(), verifyContainerCommunication(), verifyContainerFpga(), and waitForSensors().
bool iris::dist500::FirmwareController::updateContainerCommunication (Dist500 & d5, struct iris::legacy::_EMBEDDED_FILE & file, bool & skipped, void * userData) static protected
Performs a communication firmware update from container file.
Parameters
d5 Sensor instance
file Communication firmware file
skipped Flag for skipped firmware true = firmware was skipped, false = otherwise
userData User-defined additional parameter
Returns
Operation result true = verify succesful, false = verify failed
References iris::dist500::Dist500Base::getConfigurationParameter(), iris::dist500::OPERATION_PASSED, performBootloaderFirmwareUpdate(), and updateContainerCallback().
Referenced by performContainerFirmwareUpdate().
bool iris::dist500::FirmwareController::updateContainerFpga (Dist500 & d5, struct iris::legacy::_EMBEDDED_FILE & file, bool primary, bool skipFpgaRelease, bool & skipped, void * userData) static protected
Performs a FPGA firmware update from container file.
Parameters
d5 Sensor instance
file FPGA firmware file
primary FPGA firmware position true = first FPGA firmware, false = second FPGA firmware
skipped Flag for skipped firmware true = firmware was skipped, false = otherwise
userData User-defined additional parameter
Returns
Operation result true = verify succesful, false = verify failed
References loadFpgaImage(), iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_PASSED, and updateContainerCallback().
Referenced by performContainerFirmwareUpdate().
bool iris::dist500::FirmwareController::verifyContainerApplication (Dist500 & d5, struct iris::legacy::_EMBEDDED_FILE & file, void * userData) static protected
Performs a application firmware verifcation from container file.
Parameters
d5 Sensor instance
file Application firmware file
userData User-defined additional parameter
Returns
Operation result true = verify succesful, false = verify failed
References iris::dist500::OPERATION_PASSED, and updateContainerCallback().
Referenced by performContainerFirmwareUpdate().
bool iris::dist500::FirmwareController::verifyContainerCommunication (Dist500 & d5, struct iris::legacy::_EMBEDDED_FILE & file, void * userData) static protected
Performs a communication firmware verifcation from container file.
Parameters
d5 Sensor instance
file Communication firmware file
userData User-defined additional parameter
Returns
Operation result true = verify succesful, false = verify failed
References iris::dist500::OPERATION_PASSED, and updateContainerCallback().
Referenced by performContainerFirmwareUpdate().
bool iris::dist500::FirmwareController::verifyContainerFpga (Dist500 & d5, struct iris::legacy::_EMBEDDED_FILE & file, bool primary, bool skipFpgaRelease, void * userData) static protected
Performs a FPGA firmware verifcation from container file.
Parameters
d5 Sensor instance
file FPGA firmware file
primary FPGA firmware position true = first FPGA firmware, false = second FPGA firmware
userData User-defined additional parameter
Returns
Operation result true = verify succesful, false = verify failed
References iris::dist500::OPERATION_FAILED, iris::dist500::OPERATION_PASSED, and updateContainerCallback().
Referenced by performContainerFirmwareUpdate().
void iris::dist500::FirmwareController::waitForSensors (Dist500List & sensors, ContainerUpdateUserData & containerUpdateUserData, unsigned int timeMs, unsigned int intervals) static protected
waitForSensors Waits for sensors and invokes callback for progress bar update
Parameters
sensors List of sensors
timeMs Time in milliseconds
intervals Number of intervals between callback invocations
References iris::dist500::Dist500Base::sensor, iris::dist500::FirmwareController::ContainerUpdateUserData::sensor, and updateContainerCallback().
Referenced by performContainerFirmwareUpdate().
SENSOR_RESULT iris::dist500::FirmwareController::writeApplicationFirmwareInfoBlock (const std::string & hexfileName, void * userData, UPDATE_CALLBACK updateCallback) virtual
Updates the application firmware info block according to the given .LDR file.
Parameters
hexfileName Filename of the .LDR file containing the firmware
userData User-defined additional parameter for callback
updateCallback Callback function for progress updates
Returns
Operation result
References performFirmwarePartUpdate().
SENSOR_RESULT iris::dist500::FirmwareController::writeBootloaderFirmwareInfoBlock (const std::string & hexfileName, void * userData, UPDATE_CALLBACK updateCallback) virtual
Updates the bootloader firmware info block according to the given .LDR file.
Parameters
hexfileName Filename of the .LDR file containing the firmware
userData User-defined additional parameter for callback
updateCallback Callback function for progress updates
Returns
Operation result
References performFirmwarePartUpdate().
Member Data Documentation
bool iris::dist500::FirmwareController::determineHexFileAddressRange protected
Indicated whether addresses are to be evaluated (true) or if data is to be copied to firmware buffer (false)
Returns
Range detection flag
Referenced by hexFileCallback().
bool iris::dist500::FirmwareController::determineHexFileReleaseInfoAddressRange static protected
Indicated whether addresses are to be evaluated (true) or if data is to be copied to firmware buffer (false)
Returns
Range detection flag
Referenced by firmwareFitsHardwareCheck(), and hexFileReleaseInfoCallback().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/FirmwareController.h
SensorAPI/implementation/iris/dist500/FirmwareController.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !