IRMA MATRIX SDK: iris::drivers::Connection Class Reference
iris::drivers::Connection Class Reference
Represents a communication object capable of communicating with one sensor (or several sensors) using a Driver instance.
#include <Connection.h>
Public Types
typedef std::map< std::string, Sensor * > SensorMap
Maps sensor addresses to Sensor instances.
Public Member Functions
void dispatchMessage (const int level, const std::string addr, const UipMessage *msg)
Dispatches an incoming message to the destination sensor.
iris::synchronization::Mutex & getAccessMutex (void)
std::string getAddr (void) const
Returns the sensor address.
Driver & getDriver (void) const
Returns the corresponding driver.
iris::synchronization::Mutex & getExclusionGroupMutex (void)
std::string getUrl (void) const
Returns the sensor URL.
std::string getUrlPrefix (void) const
Returns the URL prefix.
void registerSensor (const std::string &address, Sensor *sensorInstance=0)
Registers a sensor instance.
void sendBroadcastMessage (const int level, UipMessage *msg)
Sends the given message in broadcast mode using the transport.
void sendMessage (const int level, UipMessage *msg)
Sends the given message using the transport.
void setAddress (const std::string &newAddress)
setAddress Safely sets a new address for this connection.
void unregisterAddressKeepSensor (const std::string &address)
Unregisters an address but does not delete the sensor instance (useful when updating its address, DHCP)
void unregisterSensor (const std::string &address)
Unregisters a sensor instance.
Public Attributes
iris::synchronization::Mutex mutex
iris::synchronization::Mutex privateAccessMutex
SensorMap sensorMap
Holds the current address / Sensor instance associations.
Protected Member Functions
Connection (Driver &driver, const std::string &addr)
Constructor.
virtual Sensor * createSensor (const std::string &address)
Creates a new Sensor instance for the Connection.
Sensor & getSensor (const std::string &addr)
Returns the associated Sensor instance.
virtual ~Connection ()
Destructor.
Protected Attributes
std::string addr
Sensor address (without prefix and :// separator)
Driver & driver
Associated driver instance.
Friends
class Driver
Detailed Description
Represents a communication object capable of communicating with one sensor (or several sensors) using a Driver instance.
Constructor & Destructor Documentation
iris::drivers::Connection::Connection (Driver & driver, const std::string & addr) protected
Constructor.
Creates a new Connection instance for the given driver and address
Parameters
driver Driver instance
addr Sensor address (without prefix and ://)
iris::drivers::Connection::~Connection () protected virtual
Destructor.
Also frees the associated Sensor instance if it exists
Member Function Documentation
Sensor * iris::drivers::Connection::createSensor (const std::string & address) protected virtual
Creates a new Sensor instance for the Connection.
Will usually be overloaded by concrete driver implementations to provide specialized Sensor subclasses.
Parameters
address Sensor address without driver prefix
Returns
New Sensor instance
Referenced by registerSensor().
void iris::drivers::Connection::dispatchMessage (const int level, const std::string addr, const UipMessage * msg)
Dispatches an incoming message to the destination sensor.
Parameters
level UIP level (0..2)
addr Sensor address
msg Message to be delivered
References iris::drivers::Sensor::dispatchMessage(), and sensorMap.
Referenced by iris::drivers::Driver::dispatchMessage().
std::string iris::drivers::Connection::getAddr (void) const
Returns the sensor address.
Returns
Sensor address (without prefix and :// separator)
References addr.
Referenced by iris::drivers::Sensor::getAddr(), and getUrl().
Driver & iris::drivers::Connection::getDriver (void) const
Returns the corresponding driver.
Returns
Driver instance
References driver.
Referenced by iris::drivers::Sensor::getDriver().
Sensor & iris::drivers::Connection::getSensor (const std::string & addr) protected
Returns the associated Sensor instance.
Parameters
addr Sensor address
Returns
Sensor instance
References sensorMap.
Referenced by iris::drivers::Driver::getSensor().
std::string iris::drivers::Connection::getUrl (void) const
Returns the sensor URL.
Returns
Full sensor URL (including prefix, :// separator and address)
References getAddr(), iris::drivers::DriverManager::getInstance(), getUrlPrefix(), and iris::drivers::DriverManager::makeUrl().
Referenced by iris::drivers::Sensor::getUrl().
std::string iris::drivers::Connection::getUrlPrefix (void) const
Returns the URL prefix.
Returns
URL prefix (without :// separator)
References driver, and iris::drivers::Driver::getUrlPrefix().
Referenced by getUrl(), and iris::drivers::Sensor::getUrlPrefix().
void iris::drivers::Connection::registerSensor (const std::string & address, Sensor * sensorInstance = 0)
Registers a sensor instance.
registerSensor Registers a sensor instance.
Parameters
address Sensor address
address The address where the sensor is reachable
sensorInstance a Sensor instance. Leave at null to create one.
References createSensor(), and sensorMap.
Referenced by iris::drivers::Driver::enableAddress().
void iris::drivers::Connection::sendBroadcastMessage (const int level, UipMessage * msg)
Sends the given message in broadcast mode using the transport.
Parameters
level UIP level (0..2)
msg Message to be sent
References driver, and iris::drivers::Driver::sendBroadcastMessage().
Referenced by iris::drivers::Sensor::sendBroadcastMessage().
void iris::drivers::Connection::sendMessage (const int level, UipMessage * msg)
Sends the given message using the transport.
Parameters
level UIP level (0..2)
msg Message to be sent
References addr, driver, and iris::drivers::Driver::sendMessage().
Referenced by iris::drivers::Sensor::sendMessage().
void iris::drivers::Connection::setAddress (const std::string & newAddress)
setAddress Safely sets a new address for this connection.
This allows the address part or UIP part to change.
Parameters
newAddress
Note
Accepts addresses including or not including the hash+UIP part. Default for that is "#1".
References addr, driver, and iris::drivers::Driver::isAddressValid().
Referenced by iris::drivers::Sensor::setConnectionAddress().
void iris::drivers::Connection::unregisterAddressKeepSensor (const std::string & address)
Unregisters an address but does not delete the sensor instance (useful when updating its address, DHCP)
Parameters
address Sensor address
References sensorMap.
Referenced by iris::drivers::Driver::disableAddress().
void iris::drivers::Connection::unregisterSensor (const std::string & address)
Unregisters a sensor instance.
Parameters
address Sensor address
References sensorMap.
Referenced by iris::drivers::Driver::disableAddress().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/drivers/Connection.h
SensorAPI/implementation/iris/drivers/Connection.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !