IRMA MATRIX SDK: iris::sharedlibs::SharedLibManager Class Reference
iris::sharedlibs::SharedLibManager Class Reference
Manages dynamic libraries (ie DLLs / dynlibs)
#include <SharedLibManager.h>
Public Types
typedef std::vector< SharedLib * > LibList
Holds a list of SharedLib instances representing the libs currently loaded by the SharedLibManager.
Public Member Functions
LibList getLoadedLibraries (void)
Returns a list of the currently loaded libraries.
bool isValid (const SharedLib &library) const
Checks whether the given library is valid.
SharedLib & loadLibrary (const std::string &libName, bool &alreadyLoaded)
Loads a given library and creates a wrapper object for it.
SharedLib & loadLibrary (const std::string &libName)
Loads a given library and creates a wrapper object for it.
void unloadLibraries (void)
Unloads all registered libraries.
void unloadLibrary (SharedLib &library)
Unloads the given library and frees its resources.
Static Public Member Functions
static SharedLibManager & getInstance (void)
Returns the global SharedLibManager instance.
Protected Types
typedef std::map< const SharedLib::HandleType, SharedLib * > LibHandles
Maps library handles (OS specific) to SharedLib instanced.
typedef std::map< std::string, SharedLib * > LoadedLibs
Maps library file names to SharedLib instances.
Protected Member Functions
SharedLibManager ()
Constructor.
virtual ~SharedLibManager ()
Destructor.
Protected Attributes
LibHandles libHandles
Map of currently loaded libraries (by handle)
LoadedLibs loadedLibs
Map of currently loaded libraries (by filename)
iris::synchronization::Mutex mutex
Mutex to synchronize access to loadedLibs and libHandles members.
Static Protected Attributes
static SharedLibManager instance
Global SharedLibManger instance.
Detailed Description
Manages dynamic libraries (ie DLLs / dynlibs)
Constructor & Destructor Documentation
iris::sharedlibs::SharedLibManager::SharedLibManager () protected
Constructor.
Note
Non-public to enforce singleton
iris::sharedlibs::SharedLibManager::~SharedLibManager () protected virtual
Destructor.
Note
Non-public to enforce singleton
Member Function Documentation
SharedLibManager & iris::sharedlibs::SharedLibManager::getInstance (void) static
Returns the global SharedLibManager instance.
Returns
Reference to static instance
Note
Singleton pattern
SharedLibManager::LibList iris::sharedlibs::SharedLibManager::getLoadedLibraries (void)
Returns a list of the currently loaded libraries.
Returns
List of SharedLib instances
bool iris::sharedlibs::SharedLibManager::isValid (const SharedLib & library) const
Checks whether the given library is valid.
A library is valid if it is present in the list of active libs
Parameters
library Library wrapper to be checked
Returns
true is valid, false otherwise
References iris::sharedlibs::SharedLib::getNormLibName().
SharedLib & iris::sharedlibs::SharedLibManager::loadLibrary (const std::string & libName, bool & alreadyLoaded)
Loads a given library and creates a wrapper object for it.
If the same library has been loaded before, the previously created wrapper instance is returned, not a new one.
Parameters
libName File name of library to be loaded
alreadyLoaded Return flag indicating if the given lib has been loaded before
Returns
SharedLib instance representing the library
Exceptions
Exception if the O/S signals an error while loading the library
Referenced by iris::drivers::DriverManager::loadDriver().
SharedLib & iris::sharedlibs::SharedLibManager::loadLibrary (const std::string & libName)
Loads a given library and creates a wrapper object for it.
If the same library has been loaded before, the previously created wrapper instance is returned, not a new one.
Parameters
libName File name of library to be loaded
Returns
SharedLib instance representing the library
Exceptions
Exception if the O/S signals an error while loading the library
void iris::sharedlibs::SharedLibManager::unloadLibrary (SharedLib & library)
Unloads the given library and frees its resources.
The SharedLib instance itself is also freed
Parameters
library Library to be unloaded
Note
References to the driver are invalid after that operation
References iris::sharedlibs::SharedLib::getHandle(), and iris::sharedlibs::SharedLib::getNormLibName().
Referenced by iris::drivers::DriverManager::loadDriver().
Member Data Documentation
SharedLibManager iris::sharedlibs::SharedLibManager::instance static protected
Global SharedLibManger instance.
Note
Singleton
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/sharedlibs/SharedLibManager.h
SensorAPI/implementation/iris/sharedlibs/SharedLibManager.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !