IRMA MATRIX SDK: iris::dist500::InstallationModeController Class Reference
iris::dist500::InstallationModeController Class Reference
Represents the DIST500's installation mode facility, which is used for live picture streaming from a sensor.
#include <InstallationModeController.h>
Classes
class DataSourceInfo
class DataSourceSelector
class RequestThread
Public Types
typedef std::list< DataSourceInfo > DataSourceInfoList
typedef std::list< DataSourceSelector > DataSourceSelectorList
typedef std::set< iris::uip::ushort > InstallationModeRegisterSet
enum InstallationModeType {
Full16, Distance16, Amplitude16, Full8,
Distance8, Amplitude8
}
Installation mode type, refers to image format that is streamed.
enum NotificationFlags { NotifyOnChange = 1, NotifyAtTimeIntervals = 2, NotifyAlways = 4, NotifyImmediately = 8 }
typedef void(* PROGRESS_CALLBACK) (void *userData, long pictureNumber, long maxPics, unsigned long long elapsedTime, unsigned long long maxTime)
Callback for installation mode progress.
typedef void(* STATUS_CALLBACK) (void *userData, bool running)
Callback for installation mode status.
Public Types inherited from iris::dist500::Dist500Base
typedef std::set< unsigned short > IdSet
typedef std::list< iris::uip::messageTypeDef > MessageTypeDefinitionList
typedef std::map< unsigned short, std::string > ParameterGroups
typedef std::map< unsigned short, ParameterInfo > ParameterInfos
typedef void(* TRANSFER_CONFIGURATION_CALLBACK) (void *userData, iris::uip::ulong index, iris::uip::ulong total, iris::uip::ushort groupId, iris::uip::ushort paramId)
Callback for sensor configuration transfers.
Public Types inherited from iris::dist500::Source< Picture * >
typedef Sink< Picture * > SinkType
Typedef for matching Sink instances.
Public Types inherited from iris::dist500::Source< RegisterValues * >
typedef Sink< RegisterValues * > SinkType
Typedef for matching Sink instances.
Public Types inherited from iris::dist500::Source< DebugData * >
typedef Sink< DebugData * > SinkType
Typedef for matching Sink instances.
Public Member Functions
SENSOR_RESULT disableInstallationMode (void)
Terminates a running installation mode.
void disableInstallationModeRetrigger (void)
SENSOR_RESULT disableTestrideMode (void)
Disables "Testride mode".
SENSOR_RESULT enableInstallationMode (InstallationModeType type, void *userData, STATUS_CALLBACK statusCallback, PROGRESS_CALLBACK progressCallback, unsigned int maxPictures, unsigned long long maxTime)
Starts the installation mode.
void enableInstallationModeRetrigger (void)
SENSOR_RESULT enableTestrideMode (void)
Enables "Testride mode", Testride is an internal iris tool.
InstallationModeController (iris::drivers::Sensor &sensor)
Constructor.
SENSOR_RESULT listDebugDataSources (DataSourceInfoList &sources)
SENSOR_RESULT selectDebugDataSources (const DataSourceSelectorList &requestedSources)
SENSOR_RESULT selectDebugDataSources (const DataSourceSelectorList &requestesSources, DataSourceSelectorList &knownSources)
bool setInstallationModeRegisterSet (const InstallationModeRegisterSet &regs)
SENSOR_RESULT singleShot (unsigned long &pictureNumber, unsigned long long &timestamp, unsigned short *buffer)
bool waitForInstallationModeEnd (int timeoutMs)
Waits for termination of installation mode.
virtual ~InstallationModeController ()
Destructor.
Public Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _legacyGetDeviceInfo (unsigned short group, unsigned short param, char *buffer)
Retrieves a device feature.
SENSOR_RESULT activateConfiguration (void)
activates a configuration that is already in RAM
SENSOR_RESULT captureDevice (char *application)
Captures the sensor: Marks the device as captured, which can be queried by getCaptureState.
SENSOR_RESULT checkSupportForMessage (const unsigned char command, const unsigned char version, const unsigned char subCommand, bool &isSupported)
checkSupportForMessage Checks if the sensor can respond to the specified message.
SENSOR_RESULT describeParameter (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info, const bool includeName=false)
describeParameter Returns ParameterInfo for the specified parameter which contains the type and value range.
SENSOR_RESULT determineTimeoutParameters (void)
Measures the timeout params (offset and factor) by doing some comnmunication tests.
Dist500Base (iris::drivers::Sensor &sensor)
Constructor.
UipMessage * doSendAndGetApplReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * doSendAndGetReply (int level, UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack or application level message and receives one or more replies.
UipMessage * doSendAndGetServiceReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a service level message and receives one or more replies.
UipMessage * doSendAndGetStackReply (UipMessage *message, int timeoutMs, int replyCount, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT echoTest (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Performs an echo test (pings the sensor)
SENSOR_RESULT getCaptureState (char *applicationBuffer, int maxLen)
Returns the capture state.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, unsigned short &len, bool stackLevel=false)
Reads a configuration parameter.
SENSOR_RESULT getConfigurationParameter (unsigned short group, unsigned short param, char *buffer, bool stackLevel=false)
Reads a configuration parameter from RAM of the sensor (not from flash).
virtual void getConnectionName (char *buffer)
Returns a description for the connection.
virtual void getLocalConnectionName (char *buffer)
Returns an identifier string for local connection (eg IP:port); Currently returns a fixed dummy string.
virtual void getName (char *nameBuffer, int maxLen)
Returns a description for the sensor (ConnectionName + @ + UipAddress)
SENSOR_RESULT getParameterGroupIds (IdSet &groupIds)
Retrieves a set of existing group ids.
SENSOR_RESULT getParameterGroups (ParameterGroups &groups)
Retrieves a map (ParameterGroups) of group ids to group name.
SENSOR_RESULT getParameterIds (const unsigned short groupId, IdSet &paramIds)
SENSOR_RESULT getParameterInfos (const unsigned short groupId, ParameterInfos &infos, const bool includeNames=false)
SENSOR_RESULT getParameterName (const unsigned short groupId, const unsigned short paramId, std::string &paramName)
getParameterName Returns only the name of the specified parameter
iris::drivers::Sensor & getSensor (void)
Returns the associated Sensor instance (from Driver)
unsigned char getUipAddress (void)
Returns the UIP address (integer between 1-255).
SENSOR_RESULT getWorkingMode (iris::uip::working_mode &mode)
Retrieves the sensor working mode (iris::uip::working_mode).
SENSOR_RESULT listAllSupportedMessages (MessageTypeDefinitionList &buffer)
listAllSupportedMessages lists all messages the sensor can respond to.
SENSOR_RESULT lockImmanentData (void)
lockImmanentData
SENSOR_RESULT pingNeighbour (const unsigned char neighbourAddress, const unsigned short payloadLen, const unsigned short repetitions, const unsigned short timeoutMs, unsigned short &successCount, unsigned short &averageTimeMs)
Asks a sensor to ping one of its neighbours (same FA) for a given number of repetitions.
SENSOR_RESULT pingSensor (const char *const payload, const unsigned short payloadLen, int timeoutMs=MAX_DEFAULT_IO_WAIT)
Pings a sensor.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT readConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Reads the sensor configuration RAM shadow.
SENSOR_RESULT releaseDevice (void)
Releases ("uncaptures") the sensor.
void resetTimeoutParameters (void)
Resets the timeout params to the default values (offset 0, factor 1.0)
SENSOR_RESULT restoreConfigurationFromFlash (void)
Copies the configuration from flash memory to RAM.
SENSOR_RESULT saveConfigurationToFlash (void)
Copies the configuration from RAM to flash memory.
UipMessage * sendAndGetApplReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends an application level message and receives one or more replies.
UipMessage * sendAndGetServiceReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
UipMessage * sendAndGetStackReply (UipMessage *message, int timeoutMs=MAX_DEFAULT_IO_WAIT, int replyCount=1, bool failOnLessReplies=true)
Sends a stack level message and receives one or more replies.
SENSOR_RESULT sendUipCommand (char type, unsigned char version, char command, unsigned short payloadLen, char *payload, unsigned int timeoutMs, char &replyType, unsigned char &replyVersion, char &replyCommand, unsigned short &replyPayloadLen, char *replyPayloadBuffer)
Sends a "free" UIP command to the sensor and waits for the reply.
SENSOR_RESULT setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel=false)
Sets a configuration parameter in the sensor's RAM (not in the flash).
SENSOR_RESULT setConfigurationParameterIfKnown (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool &paramWasUnknown, bool stackLevel=false)
Like setConfigurationParameter but only if that parameter is known.
void setUipAddress (unsigned char)
setUipAddress Sets a new UIP address for communication with this sensor.
void setUipTimeout (const int timeoutMs)
Sets timeout used for UIP send and get reply methods (whereafter usually a retry is performed).
SENSOR_RESULT setWorkingMode (const iris::uip::working_mode mode)
Sets the sensor working mode.
SENSOR_RESULT unlockImmanentData (void)
unlockImmanentData
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
SENSOR_RESULT writeConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
Writes the sensor configuration RAM shadow.
virtual ~Dist500Base ()
Destructor.
Public Member Functions inherited from iris::dist500::PictureSource
void pushPictureToSinks (Picture *data, unsigned long index, unsigned long indexCount)
Propagates a new Picture to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< Picture * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Member Functions inherited from iris::dist500::RegisterValuesSource
void pushRegisterValuesToSinks (RegisterValues *data, unsigned long index, unsigned long indexCount)
Propagates new RegisterValues to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< RegisterValues * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Member Functions inherited from iris::dist500::DebugDataSource
void pushDebugDataToSinks (DebugData *data, unsigned long index, unsigned long indexCount)
Propagates a new DebugData to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< DebugData * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Public Attributes
InstallationModeType instModeType
Holds the current installation mode type.
Protected Types
typedef std::set< InstallationModeController * > InstModeSensorsSet
Protected Types inherited from iris::dist500::Dist500Base
typedef std::map< unsigned short, ParameterInfo > GroupParameterInfos
typedef std::map< unsigned short, ParameterValue > GroupParameterValues
typedef std::set< int > NoRetryMessageHashSet
typedef std::bitset< 1024 > ReceptionFlags
Protected Types inherited from iris::dist500::Source< Picture * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Types inherited from iris::dist500::Source< RegisterValues * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Types inherited from iris::dist500::Source< DebugData * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Member Functions
SENSOR_RESULT _listDebugDataSources (DataSourceInfoList &sources, ReceptionFlags &receivedSources)
SENSOR_RESULT continueInstallationMode (void)
void discardCallbacks (void)
Disables all callbacks.
void firePictureCallback (unsigned char subPicNo, unsigned char subPicTotal, char subPicType, unsigned long pictureNumber, unsigned long long timestamp, unsigned short *values)
Calls the new picture callback function.
void fireRegisterValuesCallback (unsigned long pictureNumber, unsigned long long timestamp, unsigned short regCount, unsigned short *regNos, unsigned short *regVals)
Calls the new register values callback function.
Protected Member Functions inherited from iris::dist500::Dist500Base
SENSOR_RESULT _describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos, ReceptionFlags &receivedParameters, iris::uip::ushort &expectedCount)
SENSOR_RESULT _legacyReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _optimizedReadConfiguration (iris::configuration::Dist500Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
SENSOR_RESULT _readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings, const bool sendEmptyIfDefault, ReceptionFlags &receivedParams, iris::uip::ushort &expectedCount)
This is internally used in optimized sensor configuration readouts.
SENSOR_RESULT _setConfigurationParameter (unsigned short group, unsigned short param, const char *buffer, unsigned short len, bool stackLevel, bool ignoreUnknownParamErrors, bool &paramWasUnknown)
SENSOR_RESULT _writeConfiguration (iris::configuration::Configuration &config, ConfigurationMismatches &mismatches, TRANSFER_CONFIGURATION_CALLBACK callback=0, void *userData=0)
bool automaticRetriesSupported (UipMessage *message)
Checks if automatic retries are currently supported for the specified message.
SENSOR_RESULT describeAllGroupParametersWithoutNames (const unsigned short groupId, GroupParameterInfos &infos)
describeAllGroupParametersWithoutNames Gets descriptions (GroupParameterInfos) of parameters within the specified configuration group.
SENSOR_RESULT describeParameterWithoutName (const unsigned short groupId, const unsigned short paramId, ParameterInfo &info)
describeParameterWithoutName Gets type and value range information for the specified parameter.
SENSOR_RESULT getGroupName (const unsigned short groupId, std::string &groupName)
getGroupName Gets the name of the specified configuration group.
float getTimeoutFactor (void) const
Returns the timeout factor.
unsigned long getTimeoutOffset (void) const
Returns the timeout offset.
void initializeNoRetryMessageHashSet (void)
These are the messages that are not automatically repeated in case no reply arrives.
SENSOR_RESULT readAllGroupParameters (const unsigned short groupId, GroupParameterValues &values, const bool truncateStrings=true, const bool sendEmptyIfDefault=true)
Used for sensor configuration readout, returns a map with parameter values for the specified configuration group.
void registerNoRetryMessage (unsigned char type, unsigned char version, unsigned char command)
Makes the specified message not be automatically resent if no replay arrives.
SENSOR_RESULT requestKeyPuzzle (unsigned short &puzzleLen, unsigned char *puzzleBuffer)
SENSOR_RESULT unlockImmanentData (const unsigned short keyLen, const unsigned char *key)
unlockImmanentData
Protected Member Functions inherited from iris::dist500::Source< Picture * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (Picture * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Member Functions inherited from iris::dist500::Source< RegisterValues * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (RegisterValues * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Member Functions inherited from iris::dist500::Source< DebugData * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (DebugData * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Static Protected Member Functions
static void handleSpontaneousDebugDataMessage (Dist500Base *base, UipMessage *message)
static void handleSpontaneousPictureMessage30 (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for P 3.0.
static void handleSpontaneousPictureMessage31 (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for P 3.1.
static void handleSpontaneousPictureMessage32 (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for P 3.2.
static bool isSensorInUse (InstallationModeController *sensor)
static void registerRunningSensor (InstallationModeController *sensor)
static void registerStoppingSensor (InstallationModeController *sensor)
static void unregisterRunningSensor (InstallationModeController *sensor)
Static Protected Member Functions inherited from iris::dist500::Dist500Base
static void handleSpontaneousWorkingModeMessage (Dist500Base *base, UipMessage *message)
Callback function for spontaneous messages (sub-command *), here only for U 2.0.
Protected Attributes
iris::synchronization::Mutex callbackMutex
Mutex for installation mode parameters.
iris::uip::ushort instModeRegCount
iris::uip::ushort instModeRegNos [MaxInstModeRegCount]
volatile bool instModeRunning
unsigned long lastPictureNumber
Holds the last picture number in installation mode.
unsigned long long lastTimestamp
Holds the timestamp of the last picture in installation mode.
unsigned int maxPictures
Holds the installation mode picture limit.
unsigned long long maxTime
Holds the installation mode time limit.
Picture * pictureBuffer
Buffer for Picture instance.
unsigned int pictureCount
Holds the current installation mode picture count.
unsigned short pixelBuffer [1000]
Buffer for pixel values.
PROGRESS_CALLBACK progressCallback
Installation mode progress callback.
STATUS_CALLBACK statusCallback
Installation mode status callback.
iris::synchronization::Event terminationEvent
Installation mode termination event.
bool useInstallationModeRetrigger
void * userData
User-defined additional parameter for installation mode callback.
Protected Attributes inherited from iris::dist500::Dist500Base
SpontaneousHandlers handlers
Handler manger for spontaeous UIP messages (sub-command *)
NoRetryMessageHashSet noRetryMessageHashSet
iris::drivers::Sensor & sensor
Reference to associatee driver's Sensor object.
float timeoutFactor
Factor to applied to standard timeouts.
unsigned long timeoutOffset
Constant offset to be applied to standard timeouts.
unsigned char uipAddress
UIP address of sensor.
int uipTimeout
Timeout in ms used for UIP send and get reply methods.
Protected Attributes inherited from iris::dist500::Source< Picture * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Protected Attributes inherited from iris::dist500::Source< RegisterValues * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Protected Attributes inherited from iris::dist500::Source< DebugData * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Static Protected Attributes
static const int MaxInstModeRegCount = 32
static iris::synchronization::Mutex requestMutex
static RequestThread * requestThread = 0
static InstModeSensorsSet runningSensors
static InstModeSensorsSet stoppingSensors
Static Protected Attributes inherited from iris::dist500::Dist500Base
static bool automaticRetriesDisabled = false
Additional Inherited Members
Static Public Member Functions inherited from iris::dist500::Dist500Base
static void disableAutomaticRetries (void)
disables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
static void enableAutomaticRetries (void)
enables the automatic retries (except for messages where it was disabled via registerNoRetryMessage).
Detailed Description
Represents the DIST500's installation mode facility, which is used for live picture streaming from a sensor.
Member Typedef Documentation
typedef void(* iris::dist500::InstallationModeController::PROGRESS_CALLBACK) (void *userData, long pictureNumber, long maxPics, unsigned long long elapsedTime, unsigned long long maxTime)
Callback for installation mode progress.
Parameters
userData User-defined additional parameter
pictureNumber Picture number since start
maxPictures Maximum number of picture (0 = unlimited)
timestamp Picture timestamp
elapsedTime Elapsed time since start
maxTime Maximum time (0 = unlimited)
typedef void(* iris::dist500::InstallationModeController::STATUS_CALLBACK) (void *userData, bool running)
Callback for installation mode status.
Parameters
userData User-defined additional parameter
running Flag indicating the status (true = running, false = stopped)
Member Enumeration Documentation
enum iris::dist500::InstallationModeController::InstallationModeType
Installation mode type, refers to image format that is streamed.
Enumerator
Full16
Distance and amplitude, 12/16 bits.
Distance16
Distance only, 12/16 bits.
Amplitude16
Amplitude only, 12/16 bits.
Full8
Distance and amplitues, 8 bits.
Distance8
Distance only, 8 bits.
Amplitude8
Amplitude only, 8 bits.
Constructor & Destructor Documentation
iris::dist500::InstallationModeController::InstallationModeController (iris::drivers::Sensor & sensor)
Constructor.
Parameters
sensor Sensor reference from drifver framework
References iris::dist500::Dist500Base::handlers, handleSpontaneousPictureMessage30(), handleSpontaneousPictureMessage31(), handleSpontaneousPictureMessage32(), pictureBuffer, pixelBuffer, and iris::dist500::Dist500Base::SpontaneousHandlers::registerHandler().
Member Function Documentation
SENSOR_RESULT iris::dist500::InstallationModeController::continueInstallationMode (void) protected
maxPictures
References iris::uip::ampl_only_16, iris::uip::ampl_only_8, Amplitude16, Amplitude8, iris::uip::dist_only_16, iris::uip::dist_only_8, Distance16, Distance8, Full16, Full8, iris::uip::full_16, iris::uip::full_8, iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), instModeType, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
Referenced by enableInstallationMode().
SENSOR_RESULT iris::dist500::InstallationModeController::disableInstallationMode (void)
Terminates a running installation mode.
Returns
Operation result
See also
enableInstallationMode
References discardCallbacks(), iris::dist500::OPERATION_PASSED, progressCallback, iris::dist500::Dist500Base::sendAndGetApplReply(), statusCallback, terminationEvent, iris::dist500::Dist500Base::uipAddress, iris::dist500::Dist500Base::uipTimeout, and userData.
SENSOR_RESULT iris::dist500::InstallationModeController::disableTestrideMode (void)
Disables "Testride mode".
Returns
See also
enableTestrideMode
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
SENSOR_RESULT iris::dist500::InstallationModeController::enableInstallationMode (InstallationModeType type, void * userData, STATUS_CALLBACK statusCallback, PROGRESS_CALLBACK progressCallback, unsigned int maxPictures, unsigned long long maxTime)
Starts the installation mode.
Parameters
type
userData
statusCallback
progressCallback
maxPictures Number of pictures after which installation mode will auto-stop (0 = no limit)
maxTime Time in ms after which installation mode will auto-stop (0 = no limit)
Returns
Operation result
Note
At most one of maxPictures and maxTime may be non-zero, but not both !
See also
disableInstallationMode
References iris::uip::ampl_only_16, iris::uip::ampl_only_8, Amplitude16, Amplitude8, continueInstallationMode(), iris::uip::dist_only_16, iris::uip::dist_only_8, Distance16, Distance8, Full16, Full8, iris::uip::full_16, iris::uip::full_8, iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), instModeType, lastTimestamp, maxPictures, maxTime, iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, pictureCount, pixelBuffer, progressCallback, iris::dist500::Dist500Base::sendAndGetApplReply(), statusCallback, terminationEvent, iris::dist500::Dist500Base::uipAddress, iris::dist500::Dist500Base::uipTimeout, and userData.
SENSOR_RESULT iris::dist500::InstallationModeController::enableTestrideMode (void)
Enables "Testride mode", Testride is an internal iris tool.
Returns
See also
disableTestrideMode
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), iris::dist500::OPERATION_NO_REPLY, iris::dist500::OPERATION_PASSED, iris::dist500::OPERATION_WRONG_REPLY, iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::uipAddress, and iris::dist500::Dist500Base::uipTimeout.
void iris::dist500::InstallationModeController::firePictureCallback (unsigned char subPicNo, unsigned char subPicTotal, char subPicType, unsigned long pictureNumber, unsigned long long timestamp, unsigned short * values) protected
Calls the new picture callback function.
Parameters
subPicNo Number of current sub-picture (1-based)
subPicTotal Total sub-pics per cycle
subPicType Type of sub-picture (D: distance, A: amplitude)
pictureNumber Picture number (from sensor)
timestamp Timestamp (from sensor)
values Pointer to pixel data
References discardCallbacks(), lastPictureNumber, lastTimestamp, maxPictures, maxTime, pictureBuffer, pictureCount, pixelBuffer, progressCallback, iris::dist500::PictureSource::pushPictureToSinks(), iris::dist500::PictureBoundData::setPictureNumber(), iris::dist500::PictureBoundData::setTimestamp(), statusCallback, terminationEvent, and userData.
Referenced by handleSpontaneousPictureMessage30(), handleSpontaneousPictureMessage31(), and handleSpontaneousPictureMessage32().
void iris::dist500::InstallationModeController::fireRegisterValuesCallback (unsigned long pictureNumber, unsigned long long timestamp, unsigned short regCount, unsigned short * regNos, unsigned short * regVals) protected
Calls the new register values callback function.
Parameters
pictureNumber Picture number (from sensor)
timestamp Timestamp (from sensor)
regCount Number of registers
regNos Array with register numbers
regVals Array with register values
References iris::dist500::RegisterValuesSource::pushRegisterValuesToSinks().
Referenced by handleSpontaneousPictureMessage30(), handleSpontaneousPictureMessage31(), and handleSpontaneousPictureMessage32().
void iris::dist500::InstallationModeController::handleSpontaneousPictureMessage30 (Dist500Base * base, UipMessage * message) static protected
Callback function for spontaneous messages (sub-command *), here only for P 3.0.
Parameters
base Dist500Base instance (surrogate for this pointer)
message Spontaneously received message
References firePictureCallback(), fireRegisterValuesCallback(), iris::uip::_reg::registerNumber, and iris::uip::_reg::registerValue.
Referenced by InstallationModeController().
void iris::dist500::InstallationModeController::handleSpontaneousPictureMessage31 (Dist500Base * base, UipMessage * message) static protected
Callback function for spontaneous messages (sub-command *), here only for P 3.1.
Parameters
base Dist500Base instance (surrogate for this pointer)
message Spontaneously received message
References firePictureCallback(), fireRegisterValuesCallback(), iris::uip::_reg::registerNumber, and iris::uip::_reg::registerValue.
Referenced by InstallationModeController().
void iris::dist500::InstallationModeController::handleSpontaneousPictureMessage32 (Dist500Base * base, UipMessage * message) static protected
Callback function for spontaneous messages (sub-command *), here only for P 3.2.
Parameters
base Dist500Base instance (surrogate for this pointer)
message Spontaneously received message
References firePictureCallback(), fireRegisterValuesCallback(), iris::uip::_reg::registerNumber, and iris::uip::_reg::registerValue.
Referenced by InstallationModeController().
bool iris::dist500::InstallationModeController::waitForInstallationModeEnd (int timeoutMs)
Waits for termination of installation mode.
Parameters
timeoutMs Timeout in milliseconds
Returns
Result (trueTermination reached within timeout, false otherwise
References terminationEvent.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/InstallationModeController.h
SensorAPI/implementation/iris/dist500/InstallationModeController.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !