IRMA MATRIX SDK: iris::dist500::PictureFilter Class Reference
iris::dist500::PictureFilter Class Reference abstract
Interface class (ie abstract base class) defining a "picture filter".
#include <PictureFilter.h>
Public Member Functions
PictureFilter (bool modifiesPicture)
Constructor.
Public Member Functions inherited from iris::dist500::PictureSink
PictureSink ()
Constructor.
void processNewData (Picture *data, unsigned long index, unsigned long indexCount)
Implementation of Sink's abstract processNewData method.
Public Member Functions inherited from iris::dist500::Sink< Picture * >
void attachSource (SourceType *source)
Attaches to the given Source.
void detach (void)
Detaches from the associated Source (if currently attached to any)
Sink ()
Constructor.
virtual ~Sink ()
Destructor.
Public Member Functions inherited from iris::dist500::PictureSource
void pushPictureToSinks (Picture *data, unsigned long index, unsigned long indexCount)
Propagates a new Picture to all attached sinks.
Public Member Functions inherited from iris::dist500::Source< Picture * >
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Protected Member Functions
virtual bool applyFilter (Picture *picture, unsigned long &pictureIndex, unsigned long &pictureIndexCount)=0
Performs the actual filter task.
void processNewPicture (Picture *picture, unsigned long pictureIndex, unsigned long pictureIndexCount)
Passes on the new picture to the applyFilter() method.
Protected Member Functions inherited from iris::dist500::Source< Picture * >
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (Picture * data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Attributes
bool modifiesPicture
Flag indicating whether the filter modifies the picture data (ie whether copies of the data must be made)
Protected Attributes inherited from iris::dist500::Sink< Picture * >
iris::synchronization::Mutex mutex
SourceType * source
Active (ie attached) Source instance (or null if sink is currently not attached)
Protected Attributes inherited from iris::dist500::Source< Picture * >
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Additional Inherited Members
Public Types inherited from iris::dist500::Sink< Picture * >
typedef Source< Picture * > SourceType
Typedef for matching Source instances.
Public Types inherited from iris::dist500::Source< Picture * >
typedef Sink< Picture * > SinkType
Typedef for matching Sink instances.
Protected Types inherited from iris::dist500::Source< Picture * >
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Detailed Description
Interface class (ie abstract base class) defining a "picture filter".
A filter can simply do evaluation tasks on the picture data, but it may also modify them. If modifications are done, PictureFilter automatically creates copies of the original picture to avoid side effects.
A picture filter acts itself as PictureSource, which makes it possible to chain filters to others or to connect them to a sink (like an Aggregator or an UffRecorder).
Note
Concrete subclasses define the actual filter behaviour by implementing the applyFilter() method.
Constructor & Destructor Documentation
iris::dist500::PictureFilter::PictureFilter (bool modifiesPicture)
Constructor.
Parameters
source Optional PictureSource instance to attach to
modifiesPicture Flag indicating whether the filter modifies the picture data (true) or not (false). If activated, every incoming picture will be copied before further processing.
Member Function Documentation
virtual bool iris::dist500::PictureFilter::applyFilter (Picture * picture, unsigned long & pictureIndex, unsigned long & pictureIndexCount) protected pure virtual
Performs the actual filter task.
Parameters
picture Picture instance containing the new data
pictureIndex Reference to 0-based index of the picture (0 if the total number of pictures is unknown)
pictureIndexCount Reference to the total number of picture (0 if unknown)
Note
Subclasses need to implement this abstract method.
Referenced by processNewPicture().
void iris::dist500::PictureFilter::processNewPicture (Picture * picture, unsigned long pictureIndex, unsigned long pictureIndexCount) protected virtual
Passes on the new picture to the applyFilter() method.
This is the implementation of the abstract processNewPicture method of PictureSink. Copies of the pictures are created automatically if necessary.
Parameters
picture Picture instance containing the new data
pictureIndex 0-based index of the picture if the total number of pictures is known, 0 otherwise
pictureIndexCount Total number of picture (0 if unknown)
Implements iris::dist500::PictureSink.
References applyFilter(), modifiesPicture, and iris::dist500::Source< Picture * >::pushDataToSinks().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/PictureFilter.h
SensorAPI/implementation/iris/dist500/PictureFilter.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !