IRMA MATRIX SDK: iris::dist500::PictureBoundData Class Reference
iris::dist500::PictureBoundData Class Reference
Encapsulates a set of data which is generated by the sensor at a certain point in time.
#include <PictureBoundData.h>
Public Member Functions
unsigned long getPictureNumber (void)
Returns the picture number.
unsigned char getSensorNo (void) const
unsigned long long getTimestamp (void)
Returns the timestamp.
PictureBoundData (unsigned long pictureNumber, unsigned long long timestamp)
Constructor.
void setPictureNumber (unsigned long pictureNumber)
Changes the picture number.
void setSensorNo (const unsigned char no)
void setTimestamp (unsigned long long timestamp)
Changes the timestamp.
Protected Attributes
unsigned long pictureNumber
Holds the picture number (created by sensor)
unsigned char sensorNo
unsigned long long timestamp
Holds the timestamp (created by sensor)
Detailed Description
Encapsulates a set of data which is generated by the sensor at a certain point in time.
Constructor & Destructor Documentation
iris::dist500::PictureBoundData::PictureBoundData (unsigned long pictureNumber, unsigned long long timestamp)
Constructor.
Parameters
pictureNumber Picture number (created by sensor)
timestamp Timestamp (created by sensor)
Member Function Documentation
unsigned long iris::dist500::PictureBoundData::getPictureNumber (void)
Returns the picture number.
Returns
Picture number
References pictureNumber.
Referenced by iris::uff::UffRecorder::adjustBaseValues(), iris::uff::UffRecorder::processNewCountResult(), iris::uff::UffRecorder::processNewDebugData(), iris::uff::UffRecorder::processNewDoorState(), iris::uff::UffRecorder::processNewPicture(), iris::uff::UffRecorder::processNewRegisterValues(), and iris::uff::UffDecoder::repushData().
unsigned long long iris::dist500::PictureBoundData::getTimestamp (void)
Returns the timestamp.
Returns
Timestamp
References timestamp.
Referenced by iris::uff::UffRecorder::adjustBaseValues(), iris::uff::UffRecorder::processNewCountResult(), iris::uff::UffRecorder::processNewDebugData(), iris::uff::UffRecorder::processNewDoorState(), iris::uff::UffRecorder::processNewPicture(), iris::uff::UffRecorder::processNewRegisterValues(), and iris::uff::UffDecoder::repushData().
void iris::dist500::PictureBoundData::setPictureNumber (unsigned long pictureNumber)
Changes the picture number.
Parameters
pictureNumber New picture number
References pictureNumber.
Referenced by iris::dist500::InstallationModeController::firePictureCallback(), iris::uff::UffDecoder::getSingleApcEvent(), and iris::uff::UffDecoder::repushData().
void iris::dist500::PictureBoundData::setTimestamp (unsigned long long timestamp)
Changes the timestamp.
Parameters
timestamp New timestamp value
References timestamp.
Referenced by iris::dist500::InstallationModeController::firePictureCallback(), iris::uff::UffDecoder::getSingleApcEvent(), and iris::uff::UffDecoder::repushData().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/PictureBoundData.h
SensorAPI/implementation/iris/dist500/PictureBoundData.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !