IRMA MATRIX SDK: iris::dist500::Source< T > Class Template Reference
iris::dist500::Source< T > Class Template Reference
Template class defining a data source.
#include <Source.h>
Public Types
typedef Sink< T > SinkType
Typedef for matching Sink instances.
Public Member Functions
void attachSink (SinkType *sink)
Attaches the given sink to the current source.
void detachAll (void)
Detaches the source from connected sinks.
void detachSink (SinkType *sink)
Detaches the given sink from the current source.
bool hasAnySinks (void)
Checks whether the current source has any sinks attached.
virtual ~Source ()
Destructor.
Protected Types
typedef std::list< SinkType * > SinkTypeList
Defines a set of (typed) sinks.
Protected Member Functions
void attachSink (SinkType *sink, bool attachCall)
void detachSink (SinkType *sink, bool detachCall)
void pushDataToSinks (T data, unsigned long index, unsigned long indexCount)
Propagates new data to all attached sinks.
Protected Attributes
iris::synchronization::Mutex mutex
SinkTypeList pictureSinks
Holds the list of currently attaches sources.
Friends
class Sink< T >
Detailed Description
template<class T>
class iris::dist500::Source< T >
Template class defining a data source.
Member Function Documentation
template<class T> void iris::dist500::Source< T >::attachSink (SinkType * sink) inline
Attaches the given sink to the current source.
Parameters
sink Sink to attach
Referenced by iris::dist500::Source< CountResult * >::attachSink(), and iris::dist500::Sink< CountResult * >::attachSource().
template<class T> void iris::dist500::Source< T >::detachSink (SinkType * sink) inline
Detaches the given sink from the current source.
Parameters
sink Sink to detach
Referenced by iris::dist500::Sink< CountResult * >::detach(), and iris::dist500::Source< CountResult * >::detachSink().
template<class T> bool iris::dist500::Source< T >::hasAnySinks (void) inline
Checks whether the current source has any sinks attached.
Returns
true if there is at least one source attached, false otherwise
template<class T> void iris::dist500::Source< T >::pushDataToSinks (T data, unsigned long index, unsigned long indexCount) inline protected
Propagates new data to all attached sinks.
Parameters
data Data to be propagated
index 0-based index of the data if the total number of data objects is known, 0 otherwise
indexCount Total number of data objects (0 if unknown)
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/Sink.h
SensorAPI/headers/iris/dist500/Source.h
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !