IRMA MATRIX SDK: iris::dist500::Dist500Base::SpontaneousHandlers Class Reference
iris::dist500::Dist500Base::SpontaneousHandlers Class Reference
Implements a dispatcher which maps spontaneous UIP frames (sub-command *) to message handler methods.
#include <Dist500Base.h>
Public Types
typedef void(* UIP_MESSAGE_HANDLER) (Dist500Base *base, UipMessage *message)
Typedef for a callback method.
typedef std::map< unsigned short, UIP_MESSAGE_HANDLER > UipHandlerMap
Typedef for a map from type-version combinations to handlers.
Public Member Functions
void forward (UipMessage *message)
Forwards a message to the registered handler (if any)
void registerHandler (unsigned char type, unsigned char version, UIP_MESSAGE_HANDLER handler)
Registers a handler for a spontaneous message type.
SpontaneousHandlers (Dist500Base *base)
Constructor.
Static Public Member Functions
static unsigned short makeTypeAndVersion (unsigned char type, unsigned char version)
Computes a type and version (8-bit each) into one 16-bit integer.
Public Attributes
Dist500Base * base
Links to the owning Dist500Base instance.
iris::synchronization::Mutex mutex
Mutex.
UipHandlerMap uipHandlerMap
Holds the handler map.
Detailed Description
Implements a dispatcher which maps spontaneous UIP frames (sub-command *) to message handler methods.
Member Typedef Documentation
typedef void(* iris::dist500::Dist500Base::SpontaneousHandlers::UIP_MESSAGE_HANDLER) (Dist500Base *base, UipMessage *message)
Typedef for a callback method.
Parameters
base Dist500Base instance which provides the handler
message UIP spontaneous message instance
Constructor & Destructor Documentation
iris::dist500::Dist500Base::SpontaneousHandlers::SpontaneousHandlers (Dist500Base * base)
Constructor.
Parameters
base Owning Dist500Base instance
Member Function Documentation
void iris::dist500::Dist500Base::SpontaneousHandlers::forward (UipMessage * message)
Forwards a message to the registered handler (if any)
Parameters
message Spontaeous UIP message instance
References iris::uip::UipMessage::getType(), and iris::uip::UipMessage::getVersion().
Referenced by iris::dist500::Dist500::dispatchCallback().
void iris::dist500::Dist500Base::SpontaneousHandlers::registerHandler (unsigned char type, unsigned char version, UIP_MESSAGE_HANDLER handler)
Registers a handler for a spontaneous message type.
Parameters
type UIP type tag
version UIP version tag
handler Message handler to be called
Referenced by iris::dist500::CounterController::CounterController(), iris::dist500::Dist500Base::Dist500Base(), iris::dist500::DoorController::DoorController(), and iris::dist500::InstallationModeController::InstallationModeController().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/dist500/Dist500Base.h
SensorAPI/implementation/iris/dist500/Dist500Base.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !