IRMA MATRIX SDK: iris::sharedlibs::SharedLib Class Reference
iris::sharedlibs::SharedLib Class Reference
Acts as a wrapper for a dynamic library (ie DLL / dynlib) on the OS level.
#include <SharedLib.h>
Public Member Functions
void * getSymbolAddr (const std::string &symbolName, const bool throwException=false) const
Determines the address of a function (or symbol) within a dynamic library.
bool hasSymbol (const std::string &symbolName) const
Checks whether the given function or symbol is present in the library.
bool operator!= (const SharedLib &other)
Checks the given SharedLib instance for unequality.
bool operator== (const SharedLib &other)
Checks the given SharedLib instance for equality.
Protected Types
typedef void * HandleType
Internal handle type for dynlibs (OS specific)
Protected Member Functions
HandleType getHandle (void) const
Returns the internal handle.
const SharedLibManager & getLibManager (void) const
Returns the associated SharedLibManager.
std::string getNormLibName (void) const
Returns the normalized library name.
SharedLib (const HandleType handle, const std::string normLibName, const SharedLibManager &manager)
Constructor (non-public; only to be used by SharedLibManager)
virtual ~SharedLib ()
Destructor.
Protected Attributes
const HandleType handle
Holds the internal handle (type is OS specific)
const SharedLibManager & manager
References the associated SharedLibManager.
const std::string normLibName
Contains the normalized library name.
Friends
class SharedLibManager
Detailed Description
Acts as a wrapper for a dynamic library (ie DLL / dynlib) on the OS level.
Constructor & Destructor Documentation
iris::sharedlibs::SharedLib::SharedLib (const HandleType handle, const std::string normLibName, const SharedLibManager & manager) protected
Constructor (non-public; only to be used by SharedLibManager)
Utility class for dynamic libraries.
Parameters
handle
normLibName
manager
Member Function Documentation
SharedLib::HandleType iris::sharedlibs::SharedLib::getHandle (void) const protected
Returns the internal handle.
Returns
Handle (type is OS specific)
References handle.
Referenced by iris::sharedlibs::SharedLibManager::unloadLibrary().
const SharedLibManager & iris::sharedlibs::SharedLib::getLibManager (void) const protected
Returns the associated SharedLibManager.
Returns
SharedLibManager instance
References manager.
std::string iris::sharedlibs::SharedLib::getNormLibName (void) const protected
Returns the normalized library name.
Returns
Normalized name
References normLibName.
Referenced by iris::sharedlibs::SharedLibManager::isValid(), and iris::sharedlibs::SharedLibManager::unloadLibrary().
void * iris::sharedlibs::SharedLib::getSymbolAddr (const std::string & symbolName, const bool throwException = false) const
Determines the address of a function (or symbol) within a dynamic library.
Parameters
symbolName Name of the symbol
throwException Controls whether an exception is thrown if the symbol does not exist (true) or if NULL if returned in such case (false)
Returns
Symbol address if found, NULL otherwise
Parameters
symbolName
throwException
Returns
References handle.
Referenced by hasSymbol(), and iris::drivers::DriverManager::isDriver().
bool iris::sharedlibs::SharedLib::hasSymbol (const std::string & symbolName) const
Checks whether the given function or symbol is present in the library.
Parameters
symbolName Name of the symbol
Returns
true if present, fasle otherwise
Parameters
symbolName
References getSymbolAddr().
bool iris::sharedlibs::SharedLib::operator!= (const SharedLib & other)
Checks the given SharedLib instance for unequality.
Two libs are unequal by definition if they have different handles
Parameters
other
References handle.
bool iris::sharedlibs::SharedLib::operator== (const SharedLib & other)
Checks the given SharedLib instance for equality.
Two libs are equal by definition if they have the same handle
Parameters
other
References handle.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/sharedlibs/SharedLib.h
SensorAPI/implementation/iris/sharedlibs/SharedLib.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !