IRMA MATRIX SDK: iris::hexfiles::HexFileStreamReader Class Reference
iris::hexfiles::HexFileStreamReader Class Reference abstract
Implements a HEX file decoder which reads from a stream.
#include <HexFileStreamReader.h>
Public Member Functions
HexFileStreamReader (void *userData, const HexFileCallback callback)
Constructor.
Public Member Functions inherited from iris::hexfiles::HexFileReader
bool decodeFile (void)
Performs the decoding process; triggers the callback for any decoded block of bytes.
HexFileReader (void *userData, const HexFileCallback callback)
Constructor.
void setCallback (void *userData, const HexFileCallback callback)
virtual ~HexFileReader ()
Destructor.
Protected Member Functions
bool closeFile (void)
Closes the input.
virtual bool closeStream (std::istream *stream)=0
Closes the input stream.
bool openFile (void)
Opens the input.
virtual std::istream * openStream (void)=0
Opens the input stream.
bool readNextLine (char *const buffer, const unsigned char maxLen)
Reads a line from the input.
Protected Member Functions inherited from iris::hexfiles::HexFileReader
bool encodeLineAsBinary (void)
Translates the two digit hex values chars into the corresponding 8 bit values.
void fireCallback (void)
Executes the callback function bases on the current address and buffer.
bool isLineValid (void)
Checks whether the current line has a valid checksum.
Protected Attributes
std::istream * stream
Holds the underlying stream instance.
Protected Attributes inherited from iris::hexfiles::HexFileReader
unsigned long baseAddress
Current decoding address.
HexFileCallback callback
User callback function pointer.
void * callbackUserData
User-defined data for callback.
HEX_FILE_LINE currentLine
Buffer for current line in decoded form.
char * lineBuffer
Buffer for current line in raw form.
unsigned int lineNo
Current line number.
unsigned int maxLen
Maximum length of input line (including colon, CR and LF)
Additional Inherited Members
Public Types inherited from iris::hexfiles::HexFileReader
typedef void(* HexFileCallback) (void *userData, const unsigned long address, const unsigned char *const data, const unsigned char len)
Typedef for hex file decoding callback.
Protected Types inherited from iris::hexfiles::HexFileReader
enum { MAX_DATA_BYTES = 32 }
Maximum data bytes per line.
enum HEX_LINE_TYPE {
HexData, HexEof, HexExtSegmAddr, HexStartSegmAddr,
HexExtLinAddr, HexStartLinAddr
}
Hex file line type.
Static Protected Attributes inherited from iris::hexfiles::HexFileReader
static const char *const HEX_CHARS = "0123456789ABCDEF"
Array of hex chars (for decoding)
Detailed Description
Implements a HEX file decoder which reads from a stream.
Constructor & Destructor Documentation
iris::hexfiles::HexFileStreamReader::HexFileStreamReader (void * userData, const HexFileCallback callback)
Constructor.
Parameters
userData User-defined additional parameter for callback
callback Callback for decoding process
Member Function Documentation
bool iris::hexfiles::HexFileStreamReader::closeFile (void) protected virtual
Closes the input.
Returns
true if successful, false otherwise
Implements iris::hexfiles::HexFileReader.
References closeStream(), and stream.
virtual bool iris::hexfiles::HexFileStreamReader::closeStream (std::istream * stream) protected pure virtual
Closes the input stream.
Parameters
stream Stream instance
Returns
true if successful, false otherwise
Implemented in iris::hexfiles::HexFileFileStreamReader, and iris::hexfiles::MemoryHexFileReader.
Referenced by closeFile().
bool iris::hexfiles::HexFileStreamReader::openFile (void) protected virtual
Opens the input.
Returns
true if successful, false otherwise
Implements iris::hexfiles::HexFileReader.
References openStream(), and stream.
virtual std::istream* iris::hexfiles::HexFileStreamReader::openStream (void) protected pure virtual
Opens the input stream.
Returns
Stream instance (or null in case of failure)
Implemented in iris::hexfiles::HexFileFileStreamReader, and iris::hexfiles::MemoryHexFileReader.
Referenced by openFile().
bool iris::hexfiles::HexFileStreamReader::readNextLine (char *const buffer, const unsigned char maxLen) protected virtual
Reads a line from the input.
readNextLine Reads a line from the input
Parameters
buffer Buffer to receive the line
maxLen Maximum number of bytes to read
Returns
true if successful, false otherwise
false if no stream or end of file is reached; otherwise result of istream::getline()
Implements iris::hexfiles::HexFileReader.
References stream.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/hexfiles/HexFileStreamReader.h
SensorAPI/implementation/iris/hexfiles/HexFileStreamReader.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !