IRMA MATRIX SDK: iris::hexfiles::HexFileReader Class Reference
iris::hexfiles::HexFileReader Class Reference abstract
Implements a HEX file decoder for an arbitrary source.
#include <HexFileReader.h>
Classes
struct HEX_FILE_LINE
Represents a hex file line.
Public Types
typedef void(* HexFileCallback) (void *userData, const unsigned long address, const unsigned char *const data, const unsigned char len)
Typedef for hex file decoding callback.
Public Member Functions
bool decodeFile (void)
Performs the decoding process; triggers the callback for any decoded block of bytes.
HexFileReader (void *userData, const HexFileCallback callback)
Constructor.
void setCallback (void *userData, const HexFileCallback callback)
virtual ~HexFileReader ()
Destructor.
Protected Types
enum { MAX_DATA_BYTES = 32 }
Maximum data bytes per line.
enum HEX_LINE_TYPE {
HexData, HexEof, HexExtSegmAddr, HexStartSegmAddr,
HexExtLinAddr, HexStartLinAddr
}
Hex file line type.
Protected Member Functions
virtual bool closeFile (void)=0
Closes the source file.
bool encodeLineAsBinary (void)
Translates the two digit hex values chars into the corresponding 8 bit values.
void fireCallback (void)
Executes the callback function bases on the current address and buffer.
bool isLineValid (void)
Checks whether the current line has a valid checksum.
virtual bool openFile (void)=0
Opens the source file.
virtual bool readNextLine (char *const buffer, const unsigned char maxLen)=0
Reads the next line from the source file.
Protected Attributes
unsigned long baseAddress
Current decoding address.
HexFileCallback callback
User callback function pointer.
void * callbackUserData
User-defined data for callback.
HEX_FILE_LINE currentLine
Buffer for current line in decoded form.
char * lineBuffer
Buffer for current line in raw form.
unsigned int lineNo
Current line number.
unsigned int maxLen
Maximum length of input line (including colon, CR and LF)
Static Protected Attributes
static const char *const HEX_CHARS = "0123456789ABCDEF"
Array of hex chars (for decoding)
Detailed Description
Implements a HEX file decoder for an arbitrary source.
Member Typedef Documentation
typedef void(* iris::hexfiles::HexFileReader::HexFileCallback) (void *userData, const unsigned long address, const unsigned char *const data, const unsigned char len)
Typedef for hex file decoding callback.
Parameters
userData User-defined callback parameter
address Start address of byte block
data Pointer to data
len Number of bytes
Member Enumeration Documentation
enum iris::hexfiles::HexFileReader::HEX_LINE_TYPE protected
Hex file line type.
Enumerator
HexData
Data bytes.
HexEof
End of file.
HexExtSegmAddr
Extended segment address.
HexStartSegmAddr
Start segment address.
HexExtLinAddr
Linear address.
HexStartLinAddr
Linear start address.
Constructor & Destructor Documentation
iris::hexfiles::HexFileReader::HexFileReader (void * userData, const HexFileCallback callback)
Constructor.
Parameters
userData User-defined callback parameter
callback Decoding callback function
References currentLine, lineBuffer, and maxLen.
Member Function Documentation
virtual bool iris::hexfiles::HexFileReader::closeFile (void) protected pure virtual
Closes the source file.
This method is abstract and needs to be implemented by derived classes
Returns
true if successful, false otherwise
Implemented in iris::hexfiles::HexFileStreamReader.
Referenced by decodeFile().
bool iris::hexfiles::HexFileReader::decodeFile (void)
Performs the decoding process; triggers the callback for any decoded block of bytes.
Returns
true if successful, false if not
References iris::hexfiles::HexFileReader::HEX_FILE_LINE::addressHi, iris::hexfiles::HexFileReader::HEX_FILE_LINE::addressLo, baseAddress, closeFile(), currentLine, iris::hexfiles::HexFileReader::HEX_FILE_LINE::data, encodeLineAsBinary(), fireCallback(), HexData, HexEof, HexExtLinAddr, HexExtSegmAddr, HexStartLinAddr, HexStartSegmAddr, isLineValid(), iris::hexfiles::HexFileReader::HEX_FILE_LINE::length, lineBuffer, lineNo, maxLen, openFile(), readNextLine(), and iris::hexfiles::HexFileReader::HEX_FILE_LINE::type.
Referenced by iris::dist500::FirmwareController::firmwareFitsHardwareCheck().
bool iris::hexfiles::HexFileReader::encodeLineAsBinary (void) protected
Translates the two digit hex values chars into the corresponding 8 bit values.
Returns
true if successful, false otherwise
References currentLine, HEX_CHARS, and lineBuffer.
Referenced by decodeFile().
bool iris::hexfiles::HexFileReader::isLineValid (void) protected
Checks whether the current line has a valid checksum.
Returns
true if checksum is valid, false otherwise
References currentLine, and iris::hexfiles::HexFileReader::HEX_FILE_LINE::length.
Referenced by decodeFile().
virtual bool iris::hexfiles::HexFileReader::openFile (void) protected pure virtual
Opens the source file.
This method is abstract and needs to be implemented by derived classes
Returns
true if successful, false otherwise
Implemented in iris::hexfiles::HexFileStreamReader.
Referenced by decodeFile().
virtual bool iris::hexfiles::HexFileReader::readNextLine (char *const buffer, const unsigned char maxLen) protected pure virtual
Reads the next line from the source file.
This method is abstract and needs to be implemented by derived classes
Returns
true if successful, false otherwise
Implemented in iris::hexfiles::HexFileStreamReader.
Referenced by decodeFile().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/hexfiles/HexFileReader.h
SensorAPI/implementation/iris/hexfiles/HexFileReader.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !