IRMA MATRIX SDK: iris::drivers::Sensor Class Reference
iris::drivers::Sensor Class Reference
Represents a concrete sensor instance communicating via a Connection object.
#include <Sensor.h>
Public Types
typedef bool(* DispatchCallback) (Sensor &sensor, void *userData, const int level, const UipMessage *message)
Message handler signature for message dispatching.
Public Member Functions
virtual void dispatchMessage (const int level, const UipMessage *message)
Dispatches an incoming message.
iris::synchronization::Mutex & getAccessMutex (void)
std::string getAddr (void) const
Returns the sensor address.
Driver & getDriver (void) const
Returns the corresponding driver.
iris::synchronization::Mutex & getExclusionGroupMutex (void)
int getUipAddress (void) const
Returns the UIP address.
std::string getUrl (void) const
Returns the sensor URL.
std::string getUrlPrefix (void) const
Returns the URL prefix.
UipMessage * receiveMessage (const int level, int timeoutMs)
Receives an incoming message using the mailbox.
void sendBroadcastMessage (const int level, UipMessage *msg)
Sends the given message in broadcast mode using the transport.
void sendMessage (const int level, UipMessage *msg)
Sends the given message using the transport.
void setConnectionAddress (const std::string &newAddress)
setConnectionAddress Sets a new connection address for this Sensor.
void setDispatchCallback (void *userData, DispatchCallback callback)
Sets the dispatcher callback.
void setUipAddress (unsigned int uipAddress)
setUipAddress Changes the UIP address.
Static Public Member Functions
static int extractUipAddress (const std::string addr)
Extracts the UIP address from an address (separated by #).
Public Attributes
DispatchCallback dispatchCallback
Optional dispatcher callback pointer.
void * dispatchCallbackUserData
User-defined additional parameter for dispatcher callback.
MultiMailBox mailBox
Mailbox for incoming messages.
Protected Member Functions
Sensor (Connection &connection, const std::string &address)
Constructor.
virtual ~Sensor ()
Destructor.
Protected Attributes
Connection & connection
Associated Connection instance.
int uipAddress
UIP address.
Friends
class Connection
Detailed Description
Represents a concrete sensor instance communicating via a Connection object.
Member Typedef Documentation
typedef bool(* iris::drivers::Sensor::DispatchCallback) (Sensor &sensor, void *userData, const int level, const UipMessage *message)
Message handler signature for message dispatching.
Parameters
sensor Sensor instance
userData User-defined additional parameter
level UIP level (0..2)
message The message to be delivered
Returns
true if message has been processed by the callback, false otherwise
Note
When a dispatcher callback returns true, it is responsible for its deletion
Constructor & Destructor Documentation
iris::drivers::Sensor::Sensor (Connection & connection, const std::string & address) protected
Constructor.
Initializes a new Sensor instance for the given Connection
Parameters
connection Associated Connection instance
address Sensor address without driver prefix
Member Function Documentation
void iris::drivers::Sensor::dispatchMessage (const int level, const UipMessage * message) virtual
Dispatches an incoming message.
The message is first routed through the dispatch callback (if any). Otherwise, it is directly put into the mailbox.
Parameters
level UIP level (0..2)
message Message to be delivered
References dispatchCallback, dispatchCallbackUserData, mailBox, iris::drivers::MultiMailBox::putMessage(), and uipAddress.
Referenced by iris::drivers::Connection::dispatchMessage().
int iris::drivers::Sensor::extractUipAddress (const std::string addr) static
Extracts the UIP address from an address (separated by #).
Returns 0 if none was found.
Parameters
addr Sensor address
Returns
UIP address in range (1-255). Returns 0 if none was found.
Referenced by setConnectionAddress().
std::string iris::drivers::Sensor::getAddr (void) const
Returns the sensor address.
Returns
Sensor address (without prefix and :// separator)
References connection, and iris::drivers::Connection::getAddr().
Referenced by iris::dist500::Dist500Base::getConnectionName(), iris::dist500::Dist500Base::getLocalConnectionName(), and iris::dist500::updateSensorConnectionsViaBroadcast().
Driver & iris::drivers::Sensor::getDriver (void) const
Returns the corresponding driver.
Returns
Driver instance
References connection, and iris::drivers::Connection::getDriver().
Referenced by iris::dist500::FirmwareController::getSensorInfo().
int iris::drivers::Sensor::getUipAddress (void) const
Returns the UIP address.
The UIP address is the number after the hash sign in a URL.
Returns
UIP address
See also
setUipAddress
References uipAddress.
Referenced by iris::dist500::Dist500Base::Dist500Base(), getUrl(), and iris::dist500::updateSensorConnectionsViaBroadcast().
std::string iris::drivers::Sensor::getUrl (void) const
Returns the sensor URL.
Returns
Full sensor URL (including prefix, :// separator and address)
References connection, getUipAddress(), and iris::drivers::Connection::getUrl().
Referenced by iris::dist500::FirmwareController::getSensorInfo().
std::string iris::drivers::Sensor::getUrlPrefix (void) const
Returns the URL prefix.
Returns
URL prefix (without :// separator)
References connection, and iris::drivers::Connection::getUrlPrefix().
UipMessage * iris::drivers::Sensor::receiveMessage (const int level, int timeoutMs)
Receives an incoming message using the mailbox.
Parameters
level UIP level (0..2)
timeoutMs Timeout in milliseconds
Returns
Received UipMessage instance when succeeded or null if timeout has occured
References iris::drivers::MultiMailBox::getMessage(), mailBox, and uipAddress.
Referenced by iris::dist500::Dist500Base::_readAllGroupParameters(), and iris::dist500::Dist500Base::doSendAndGetReply().
void iris::drivers::Sensor::sendBroadcastMessage (const int level, UipMessage * msg)
Sends the given message in broadcast mode using the transport.
Parameters
level UIP level (0..2)
msg Message to be sent
References connection, and iris::drivers::Connection::sendBroadcastMessage().
void iris::drivers::Sensor::sendMessage (const int level, UipMessage * msg)
Sends the given message using the transport.
Parameters
level UIP level (0..2)
msg Message to be sent
References connection, and iris::drivers::Connection::sendMessage().
Referenced by iris::dist500::Dist500Base::doSendAndGetReply().
void iris::drivers::Sensor::setConnectionAddress (const std::string & newAddress)
setConnectionAddress Sets a new connection address for this Sensor.
Sensor::setConnectionAddress.
Used for DHCP.
Parameters
newAddress
See also
Connection::setAddress
References connection, extractUipAddress(), iris::drivers::Connection::setAddress(), and uipAddress.
Referenced by iris::dist500::updateSensorConnectionsViaBroadcast().
void iris::drivers::Sensor::setDispatchCallback (void * userData, DispatchCallback callback)
Sets the dispatcher callback.
Parameters
userData User-defined additional parameter for the callback (null disables the callback)
callback Callback function pointer
References dispatchCallback, and dispatchCallbackUserData.
Referenced by iris::dist500::Dist500::Dist500(), iris::dist500::updateSensorConnectionsViaBroadcast(), and iris::dist500::Dist500::~Dist500().
void iris::drivers::Sensor::setUipAddress (unsigned int uipAddress)
setUipAddress Changes the UIP address.
The UIP address is the number after the hash sign in a URL.
Parameters
uipAddress
Note
If the UIP changes, it must be updated, otherwise messages will not be received and will be discarded.
The UIP address can change on grouping or ungrouping of sensors. Direct configuration of the UIP is another possibility.
See also
getUipAddress
Dist500::setUipAddress
References uipAddress.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/drivers/Sensor.h
SensorAPI/implementation/iris/drivers/Sensor.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !