IRMA MATRIX SDK: iris::uff::UffRecorder Class Reference
iris::uff::UffRecorder Class Reference
Implements a DIST500 movie recorder.
#include <UffRecorder.h>
Public Member Functions
void adjustBaseValues (iris::dist500::PictureBoundData *data)
UffRecorder::adjustBaseValues.
void attachAll (iris::dist500::Dist500 *sensor)
Attaches all data sources of sensor.
void detachAll (void)
Detaches all data sources.
void enableDummyMode (void)
void processNewCountResult (iris::dist500::CountResult *result, unsigned long countResultIndex, unsigned long countResultCount)
Signals the availability of new data within the attached source.
void processNewDebugData (iris::dist500::DebugData *data, unsigned long dataIndex, unsigned long dataCount)
Signals the availability of new data within the attached source.
void processNewDoorState (iris::dist500::DoorState *state, unsigned long pictureIndex, unsigned long pictureIndexCount)
Signals the availability of new data within the attached source.
void processNewPicture (iris::dist500::Picture *picture, unsigned long pictureIndex, unsigned long pictureIndexCount)
UffRecorder::processNewPicture.
void processNewRegisterValues (iris::dist500::RegisterValues *values, unsigned long pictureIndex, unsigned long pictureIndexCount)
Signals the availability of new data within the attached source.
bool saveDataSourceInfos (const unsigned char sensorAddr, const iris::dist500::InstallationModeController::DataSourceInfoList &infos)
void startRecording (unsigned long maxPictures=0, unsigned long long maxTime=0)
Starts writing of data from attached sources to UFF file.
void stopRecording (void)
Stops writing of data to UFF file.
UffRecorder (const std::string &fileName, const std::string appName, const std::string appVersion, const std::string &userName, const std::string &location, iris::dist500::SensorInfoProvider *provider)
Constructor.
UffRecorder (UffRecorder *existing, iris::dist500::SensorInfoProvider *sensorInfoProvider)
Constructor.
UffRecorder (const std::string &fileName, const std::string appName, const std::string appVersion, const std::string &userName, const std::string &location)
UffRecorder (UffRecorder *existing)
bool waitForEndOfRecording (int timeoutMs)
Waits for end of recording (writing of data to UFF file).
bool writeInitialDoorState (const unsigned short doorNumber, const unsigned char leftState, const unsigned char rightState)
bool writeMetadataField (const int fieldId, const std::string &text)
bool writeSensorConfiguration (const unsigned char sensorNo, iris::configuration::Dist500Configuration &config)
bool writeSensorConfiguration (const unsigned char sensorNo, iris::configuration::Dist500Configuration &config, iris::dist500::Dist500Base::ConfigurationMismatches &mismatches)
bool writeTotalApcCountResult (const int intervalIndex, const int countIndex, const unsigned short category, const unsigned short boarding, const unsigned short alighting)
bool writeTotalManualCountResult (const int intervalIndex, const int countIndex, const unsigned short category, const unsigned short boarding, const unsigned short alighting, const std::string &comment)
virtual ~UffRecorder ()
Destructor.
Public Member Functions inherited from iris::dist500::PictureSink
PictureSink ()
Constructor.
void processNewData (Picture *data, unsigned long index, unsigned long indexCount)
Implementation of Sink's abstract processNewData method.
Public Member Functions inherited from iris::dist500::Sink< Picture * >
void attachSource (SourceType *source)
Attaches to the given Source.
void detach (void)
Detaches from the associated Source (if currently attached to any)
Sink ()
Constructor.
virtual ~Sink ()
Destructor.
Public Member Functions inherited from iris::dist500::RegisterValuesSink
void processNewData (RegisterValues *data, unsigned long index, unsigned long indexCount)
Implementation of Sink's abstract processNewData method.
RegisterValuesSink ()
Constructor.
Public Member Functions inherited from iris::dist500::Sink< RegisterValues * >
void attachSource (SourceType *source)
Attaches to the given Source.
void detach (void)
Detaches from the associated Source (if currently attached to any)
Sink ()
Constructor.
virtual ~Sink ()
Destructor.
Public Member Functions inherited from iris::dist500::DoorStateSink
DoorStateSink ()
Constructor.
void processNewData (DoorState *data, unsigned long index, unsigned long indexCount)
Implementation of Sink's abstract processNewData method.
Public Member Functions inherited from iris::dist500::Sink< DoorState * >
void attachSource (SourceType *source)
Attaches to the given Source.
void detach (void)
Detaches from the associated Source (if currently attached to any)
Sink ()
Constructor.
virtual ~Sink ()
Destructor.
Public Member Functions inherited from iris::dist500::CountResultSink
CountResultSink ()
Constructor.
void processNewData (CountResult *data, unsigned long index, unsigned long indexCount)
Implementation of Sink's abstract processNewData method.
Public Member Functions inherited from iris::dist500::Sink< CountResult * >
void attachSource (SourceType *source)
Attaches to the given Source.
void detach (void)
Detaches from the associated Source (if currently attached to any)
Sink ()
Constructor.
virtual ~Sink ()
Destructor.
Public Member Functions inherited from iris::dist500::DebugDataSink
DebugDataSink ()
Constructor.
void processNewData (DebugData *data, unsigned long index, unsigned long indexCount)
Implementation of Sink's abstract processNewData method.
Public Member Functions inherited from iris::dist500::Sink< DebugData * >
void attachSource (SourceType *source)
Attaches to the given Source.
void detach (void)
Detaches from the associated Source (if currently attached to any)
Sink ()
Constructor.
virtual ~Sink ()
Destructor.
Static Public Member Functions
static void disableUtf8 (void)
Disables UTF-8 support.
static void enableUtf8 (void)
Enables UTF-8 support.
static bool utf8Active (void)
Checks whether UTF-8 support is enabled or not.
Protected Member Functions
bool _writeSensorConfiguration (const unsigned char sensorNo, iris::configuration::Configuration &config)
void closeUnderlyingBuilder (void)
void openUnderlyingBuilder (void)
Protected Attributes
iris::synchronization::Mutex accessMutex
std::string appName
std::string appVersion
unsigned long basePictureNumber
unsigned long long baseTimestamp
iris::synchronization::Mutex baseValuesMutex
iris::legacy::Dist500MovieBuilder * builder
int countIndex
bool dummyMode
iris::synchronization::Event endOfRecording
UffRecorder * existing
std::string fileName
int intervalIndex
std::string location
bool open
int pictureCount
iris::dist500::SensorInfo sensorInfo
bool stopping
std::string userName
Protected Attributes inherited from iris::dist500::Sink< Picture * >
iris::synchronization::Mutex mutex
SourceType * source
Active (ie attached) Source instance (or null if sink is currently not attached)
Protected Attributes inherited from iris::dist500::Sink< RegisterValues * >
iris::synchronization::Mutex mutex
SourceType * source
Active (ie attached) Source instance (or null if sink is currently not attached)
Protected Attributes inherited from iris::dist500::Sink< DoorState * >
iris::synchronization::Mutex mutex
SourceType * source
Active (ie attached) Source instance (or null if sink is currently not attached)
Protected Attributes inherited from iris::dist500::Sink< CountResult * >
iris::synchronization::Mutex mutex
SourceType * source
Active (ie attached) Source instance (or null if sink is currently not attached)
Protected Attributes inherited from iris::dist500::Sink< DebugData * >
iris::synchronization::Mutex mutex
SourceType * source
Active (ie attached) Source instance (or null if sink is currently not attached)
Additional Inherited Members
Public Types inherited from iris::dist500::Sink< Picture * >
typedef Source< Picture * > SourceType
Typedef for matching Source instances.
Public Types inherited from iris::dist500::Sink< RegisterValues * >
typedef Source< RegisterValues * > SourceType
Typedef for matching Source instances.
Public Types inherited from iris::dist500::Sink< DoorState * >
typedef Source< DoorState * > SourceType
Typedef for matching Source instances.
Public Types inherited from iris::dist500::Sink< CountResult * >
typedef Source< CountResult * > SourceType
Typedef for matching Source instances.
Public Types inherited from iris::dist500::Sink< DebugData * >
typedef Source< DebugData * > SourceType
Typedef for matching Source instances.
Detailed Description
Implements a DIST500 movie recorder.
Constructor & Destructor Documentation
iris::uff::UffRecorder::UffRecorder (const std::string & fileName, const std::string appName, const std::string appVersion, const std::string & userName, const std::string & location, iris::dist500::SensorInfoProvider * provider)
Constructor.
Parameters
fileName Name of UFF file to be created
appName Application name string
appVersion Application version string
userName User name string
location Location description string
provider Provider of SensorInfo
References iris::dist500::SensorInfoProvider::getSensorInfo().
iris::uff::UffRecorder::UffRecorder (UffRecorder * existing, iris::dist500::SensorInfoProvider * sensorInfoProvider)
Constructor.
Parameters
existing Existing UffRecorder instance to join
provider Provider of SensorInfo
Note
Use this constructor variant for slaves of a sensor group. UffRecorder instance of master sensor has to be given as parameter existing
References iris::dist500::SensorInfoProvider::getSensorInfo().
Member Function Documentation
void iris::uff::UffRecorder::adjustBaseValues (iris::dist500::PictureBoundData * data)
UffRecorder::adjustBaseValues.
Parameters
data
References iris::dist500::PictureBoundData::getPictureNumber(), and iris::dist500::PictureBoundData::getTimestamp().
Referenced by processNewCountResult(), processNewDebugData(), processNewDoorState(), processNewPicture(), and processNewRegisterValues().
void iris::uff::UffRecorder::attachAll (iris::dist500::Dist500 * sensor)
Attaches all data sources of sensor.
Parameters
sensor Sensor with data sources to be attached
void iris::uff::UffRecorder::disableUtf8 (void) static
Disables UTF-8 support.
UFF file name and all strings written to UFF file are expected with ANSI encoding
void iris::uff::UffRecorder::enableUtf8 (void) static
Enables UTF-8 support.
UFF file name and all strings written to UFF file are expected with UTF-8 encoding
void iris::uff::UffRecorder::processNewCountResult (iris::dist500::CountResult * result, unsigned long countIndex, unsigned long countIndexCount) virtual
Signals the availability of new data within the attached source.
Parameters
result CountResult object
countIndex 0-based index of the picture if the total number of data objects is known, 0 otherwise
countIndexCount Total number of count objects (0 if unknown)
Implements iris::dist500::CountResultSink.
References adjustBaseValues(), iris::dist500::CountResult::getAlighting(), iris::dist500::CountResult::getBoarding(), iris::dist500::CountResult::getCategory(), iris::dist500::PictureBoundData::getPictureNumber(), and iris::dist500::PictureBoundData::getTimestamp().
void iris::uff::UffRecorder::processNewDebugData (iris::dist500::DebugData * data, unsigned long dataIndex, unsigned long dataCount) virtual
Signals the availability of new data within the attached source.
Parameters
data DebugData object
dataIndex 0-based index of the debug data if the total number of data objects is known, 0 otherwise
dataCount Total number of debug data objects (0 if unknown)
Implements iris::dist500::DebugDataSink.
References adjustBaseValues(), iris::dist500::DebugData::getData(), iris::dist500::DebugData::getDataSize(), iris::dist500::DebugData::getDataSource(), iris::dist500::PictureBoundData::getPictureNumber(), iris::dist500::DebugData::getStatus(), and iris::dist500::PictureBoundData::getTimestamp().
void iris::uff::UffRecorder::processNewDoorState (iris::dist500::DoorState * state, unsigned long stateIndex, unsigned long stateCount) virtual
Signals the availability of new data within the attached source.
Parameters
state DoorState object
stateIndex 0-based index of the state if the total number of data objects is known, 0 otherwise
stateCount Total number of state objects (0 if unknown)
Implements iris::dist500::DoorStateSink.
References adjustBaseValues(), iris::dist500::DoorState::getDoor(), iris::dist500::DoorState::getLeft(), iris::dist500::PictureBoundData::getPictureNumber(), iris::dist500::DoorState::getRight(), and iris::dist500::PictureBoundData::getTimestamp().
void iris::uff::UffRecorder::processNewPicture (iris::dist500::Picture * picture, unsigned long pictureIndex, unsigned long pictureIndexCount) virtual
UffRecorder::processNewPicture.
Parameters
picture
pictureIndex
pictureIndexCount
Implements iris::dist500::PictureSink.
References adjustBaseValues(), iris::dist500::Picture::getPicture(), iris::dist500::PictureBoundData::getPictureNumber(), and iris::dist500::PictureBoundData::getTimestamp().
void iris::uff::UffRecorder::processNewRegisterValues (iris::dist500::RegisterValues * values, unsigned long valueIndex, unsigned long valueCount) virtual
Signals the availability of new data within the attached source.
This callback method is abstract. Derived RegisterValuesSink classed therefore need to implement it.
Parameters
values RegisterValues instance containing the new data
valueIndex 0-based index of the RegisterValue if the total number of RegisterValue is known, 0 otherwise
valueCount Total number of RegisterValues (0 if unknown)
Implements iris::dist500::RegisterValuesSink.
References adjustBaseValues(), iris::dist500::PictureBoundData::getPictureNumber(), iris::dist500::RegisterValues::getRegisterValue(), and iris::dist500::PictureBoundData::getTimestamp().
void iris::uff::UffRecorder::startRecording (unsigned long maxPictures = 0, unsigned long long maxTime = 0)
Starts writing of data from attached sources to UFF file.
Parameters
maxPictures Picture count limit for recording
maxTime Time limit for recording (ms)
Note
Recording is lasting until call of method stopRecording if started with default parameters maxPictures == 0 and maxTime == 0
bool iris::uff::UffRecorder::utf8Active (void) static
Checks whether UTF-8 support is enabled or not.
Returns
true if UTF-8 support is enabled, false otherwise
bool iris::uff::UffRecorder::waitForEndOfRecording (int timeoutMs)
Waits for end of recording (writing of data to UFF file).
Useful only if recording was started with parameter maxPictures > 0 or maxTime > 0
Parameters
timeoutMs Timeout for waiting (ms)
Returns
true if no timeout occured while waiting, false otherwise
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/uff/UffRecorder.h
SensorAPI/implementation/iris/uff/UffRecorder.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !