IRMA MATRIX SDK: iris::drivers::udp::UdpDriver Class Reference
iris::drivers::udp::UdpDriver Class Reference
Implements an UIP-over-UDP driver.
#include <UdpDriver.h>
Classes
class ReceiveThread
Implements a reception thread.
Public Types
typedef std::list< boost::asio::ip::address_v4 > BroadcastAddressList
Public Types inherited from iris::drivers::Driver
typedef std::list< std::string > AddressList
Holds a list of sensor addresses.
typedef std::map< std::string, Connection * > ConnectionMap
Maps addresses to Connection objects.
typedef std::multimap< std::string, Connection * > ConnectionMultiMap
Maps main-addresses to Connection objects.
typedef void(* DEBUG_CALLBACK) (void *userData, const int level, const std::string &addr, const UipMessage *msg)
typedef iris::dist500::Dist500List Dist500List
typedef std::set< std::string > OptionNameSet
typedef void(* SCAN_CALLBACK) (void *userData, const Driver &driver, const std::string &url)
Callback for sensor address scan.
typedef std::list< iris::dist500::SensorGroup * > SensorGroupList
Public Member Functions
void handle_receive (const boost::system::error_code &error, std::size_t bytes_transferred)
Callback method for successful or failed reception processes.
AddressList performAddressScan (void *userData=0, SCAN_CALLBACK callback=0) const
Returns the list of all sensors addresses that can currently be found.
void request_receive (void)
Initiates a new receive process on the socket.
void sendBroadcastMessage (const int level, const UipMessage *message) const
Sends the given message in broadcast mode.
void sendMessage (const int level, const std::string &addr, const UipMessage *message) const
Sends the given message.
void setSenderAddress (unsigned char addr)
Sets the UIP address of the sender.
void shutdownDriver (void)
Deinitializes the driver.
void signalStart (void)
void startupDriver (void)
Initializes the driver.
UdpDriver ()
Constructor.
bool waitForStart (int timeoutMs)
virtual ~UdpDriver ()
Destructor.
Public Member Functions inherited from iris::drivers::Driver
void clearDebugListener (void)
void disableAddress (const std::string &addr, bool keepSensor=false, bool keepConnection=false)
Disables the given address for subsequent communication.
void disableAddresses (const AddressList &addresses)
Disables all given addresses for subsequent communication.
void disableAllAddresses (void)
Disables all currently enabled addresses.
void enableAddress (const std::string &addr, Sensor *sensorInstance=0)
Enables the given address for subsequent communication.
void enableAddresses (const AddressList &addresses)
Enables all given addresses for subsequent communication.
iris::synchronization::Mutex & getAccessMutex (void)
AddressList getActiveAddresses (void)
Returns the list of currently active (enabled) addresses.
Connection & getConnection (const std::string &addr)
Returns a connection object for the given sensor address.
iris::synchronization::Mutex & getExclusionGroupMutex (void)
const std::string getName (void) const
Returns the driver name.
std::string getOption (const std::string &optionName, const bool useDefaultIfNotSet=true) const
std::string getOption (const std::string &optionName, const std::string &defaultValue) const
OptionNameSet getOptionNames (const bool onlySetOptions=false)
Sensor & getSensor (const std::string &addr)
Returns the associated Sensor instance.
const std::string getUrlPrefix (void) const
Returns the URL prefix.
const std::string getVersion (void) const
Returns the driver version.
bool isActive (void) const
Checks whether the driver is active or not.
bool isAddressEnabled (const std::string &addr) const
Checks whether the given address is currently enabled.
bool isAddressValid (const std::string &addr) const
Checks whether the given address is valid or not.
bool isOptionSet (const std::string &optionName) const
bool isOptionValid (const std::string &optionName, const std::string &optionValue) const
void setDebugListener (DEBUG_CALLBACK listener, void *userData=0)
void setOption (const std::string &optionName, const std::string &optionValue)
void setOptionDefault (const std::string &optionName)
bool supportsOption (const std::string &optionName) const
virtual bool supportsParallelAccess (void) const
Indicates if parallel communication with several sensors is supported or not.
void unsetOption (const std::string &optionName)
Public Attributes
bool autoTimeouts
BroadcastAddressList broadcastAddresses
iris::synchronization::Event event
boost::asio::io_service * ios_
boost ioservice instance
iris::synchronization::Mutex mutex
char receiveBuffer [2000]
Raw (bytes) reception buffer for UDP datagrams.
iris::synchronization::Mutex receiveMutex
boost::asio::ip::udp::endpoint remote_endpoint_
boost remote endpoint instance
SCAN_CALLBACK scanCallback
AddressList scanList
Holds a list containing the scanned sensor addresses.
void * scanUserData
unsigned char senderAddress
iris::synchronization::Mutex sendMutex
boost::asio::ip::udp::socket * socket_
boost socket instance
bool started
ReceiveThread * t
Holds the receive thread instance.
Public Attributes inherited from iris::drivers::Driver
iris::synchronization::Mutex accessMutex
ConnectionMap activeConnections
Contains the map of currently active (enabled) addresses along with their corresponding Connection objects.
ConnectionMultiMap distinctConnections
Contains the map of currently active (enabled) main-addresses along with their corresponding Connection objects.
iris::synchronization::Mutex mutex
Static Public Attributes
static const std::string & AdditionalHostsOptionName
static const std::string & AdditionalNetworksOptionName
static const std::string & AutoTimeoutsOptionName
static const std::string & BindAddressOptionName
static const std::string & BindPortOptionName
static const std::string & EnableLoggingOptionName
static volatile bool finished = false
static const std::string & LogfileNameOptionName
static const std::string & Mnemonic
static const std::string & SuppressGlobalBroadcastOptionName
static const std::string & SuppressLocalSubnetBroadcastsOptionName
static const std::string & TimeoutFactorOptionName
static const std::string & TimeoutOffsetOptionName
Protected Member Functions
std::string getExclusionGroupName (void) const
void log (utilities::LogCategory *category, const void *data, const unsigned short len) const
Protected Member Functions inherited from iris::drivers::Driver
void checkOption (const std::string &optionName, const std::string &optionValue) const
void checkOptionName (const std::string optionName) const
virtual Connection * createConnection (const std::string &addr)
Creates a new Connection instance for the given address.
void dispatchMessage (const int level, const std::string &addr, const UipMessage *msg)
Dispatches an incoming message to the destination sensor.
Driver (const std::string &name, const std::string &urlPrefix, const std::string &version, const std::string &urlAddrRegEx)
Constructor.
void ensureValidAddress (const std::string &addr) const
Verifies the validity of the given address.
Connection * getInternalConnection (const std::string &addr)
void registerOption (const std::string &optionName, const std::string &defaultValue, OptionValidator *validator)
void removeOption (const std::string &optionName)
void setActive (void)
void setInactive (void)
virtual ~Driver ()
Destructor.
Protected Attributes
iris::utilities::LogEntryCache * logCache
iris::utilities::LogCategory * rxCategory
iris::utilities::LogCategory * txCategory
iris::utilities::LogCategory * txErrCategory
Protected Attributes inherited from iris::drivers::Driver
bool active
DEBUG_CALLBACK debugListener
void * debugListenerUserData
const std::string name
Descriptive name of the driver.
OptionDefaultsMap optionDefaults
OptionValuesMap options
OptionValidatorMap optionValidators
const boost::regex urlAddrRegEx
Regular expression to check for syntactical sensor addresses (without prefix and :// separator)
const std::string urlPrefix
Prefix for sensor URLs, without the :// separator.
const std::string version
Version string, eg 1.0.0.
Additional Inherited Members
Static Public Member Functions inherited from iris::drivers::Driver
static SensorGroupList groupSensors (const Dist500List sensors)
Protected Types inherited from iris::drivers::Driver
typedef std::map< std::string, std::string > OptionDefaultsMap
typedef std::map< std::string, OptionValidator * > OptionValidatorMap
typedef std::map< std::string, std::string > OptionValuesMap
Detailed Description
Implements an UIP-over-UDP driver.
Member Function Documentation
void iris::drivers::udp::UdpDriver::handle_receive (const boost::system::error_code & error, std::size_t bytes_transferred)
Callback method for successful or failed reception processes.
Parameters
error Success/error code
bytes_transferred Byte size of received packet
References iris::drivers::Driver::dispatchMessage(), iris::uip::UipMessage::getSender(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), receiveBuffer, remote_endpoint_, request_receive(), scanList, iris::uip::UipMessage::setLevel(), and iris::drivers::Driver::version.
Referenced by request_receive().
iris::drivers::Driver::AddressList iris::drivers::udp::UdpDriver::performAddressScan (void * userData = 0, SCAN_CALLBACK callback = 0) const virtual
Returns the list of all sensors addresses that can currently be found.
Returns
Address list (without URL prefix and :// separator)
Reimplemented from iris::drivers::Driver.
References scanList, and sendBroadcastMessage().
void iris::drivers::udp::UdpDriver::sendBroadcastMessage (const int level, const UipMessage * message) const virtual
Sends the given message in broadcast mode.
Parameters
level UIP level (0..2)
message Message to be sent
Reimplemented from iris::drivers::Driver.
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getReceiver(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), and socket_.
Referenced by performAddressScan().
void iris::drivers::udp::UdpDriver::sendMessage (const int level, const std::string & addr, const UipMessage * message) const virtual
Sends the given message.
Parameters
level UIP level (0..2)
addr Sensor address
message Message to be sent
Reimplemented from iris::drivers::Driver.
References iris::uip::UipMessage::getPayloadLen(), iris::uip::UipMessage::getReceiver(), iris::uip::UipMessage::getType(), iris::uip::UipMessage::getVersion(), and socket_.
void iris::drivers::udp::UdpDriver::setSenderAddress (unsigned char addr)
Sets the UIP address of the sender.
Parameters
addr UIP address between 240 and 254.
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/drivers/udp/UdpDriver.h
SensorAPI/implementation/iris/drivers/udp/UdpDriver.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !