IRMA MATRIX SDK: iris::uip::UipMessage Class Reference
iris::uip::UipMessage Class Reference
Represents a message in the UIP protocol.
#include <UipMessage.h>
Public Member Functions
UIP_LEVEL getLevel (void)
Returns the message level.
const char * getMessageClassName (void)
Returns the message class name.
char * getPayload (void)
Returns the payload.
UIP_PAYLOAD_LEN getPayloadLen (void)
Returns the payload length.
UIP_ADDRESS getReceiver (void)
Returns the receiver.
UIP_ADDRESS getSender (void)
Returns the sender.
UIP_TYPE getType (void)
Returns message type.
int getTypeHash (void)
Returns a hash value for the message type.
int getVariant (void)
Returns the message variant.
UIP_VERSION getVersion (void)
Returns the message version.
void printDebugInfo (std::ostream &ostream)
Prints a debug string for the message to an output stream.
void setLevel (UIP_LEVEL level)
Sets the message level.
UipMessage (UIP_ADDRESS receiver, UIP_ADDRESS sender, UIP_TYPE type, UIP_VERSION version, UIP_PAYLOAD_LEN payloadLen=0, char *payload=NULL)
Constructor.
virtual ~UipMessage ()
Destructor.
Public Member Functions inherited from iris::messages::Message
Message * getNextMessage (void)
Returns the linked message, if any.
bool hasNextMessage (void)
Checkes whether a linked message exists.
void linkTo (Message *other)
Links a given message to the existing one.
Message (short size=MAX_MESSAGE_SIZE)
Constructor.
virtual ~Message ()
Destructor.
Public Member Functions inherited from iris::messages::DynamicBuffer
void clear (void)
Clears the buffer.
DynamicBuffer (unsigned short maxLength, char *buffer=NULL)
Constructor.
char * getBuffer (void)
Returns the internal buffer pointer.
unsigned short getLength (void)
Returns the current buffer length.
unsigned short getMaxLength (void)
Returns the length limitation.
unsigned short getPosition (void)
Returns the current read/write position.
bool movePosition (signed short movement)
Moves the read/write pointer relative to its current position.
virtual void printDebugInfoPart (std::ostream &ostream, const unsigned short offset, const unsigned short length)
Prints a debug hex-dump of a part of the buffer to an output stream.
bool readBlock (void *data, const unsigned short size)
Reads a data block from the current position.
bool readSByte (signed char &byte)
Reads a signed byte from the current position.
bool readSLong (signed long &lng)
Reads a signed long (32 bits) from the current position.
bool readSLong64 (signed long long &lng64)
Reads a signed long long (64 bits) from the current position.
bool readString (char *string)
Reads a string from the current position.
bool readString (char *string, const unsigned short size)
Reads a string from the current position using a fixed length.
bool readSWord (signed short &word)
Reads a signed word (16 bits) from the current position.
bool readUByte (unsigned char &byte)
Reads an unsigned byte from the current position.
bool readULong (unsigned long &lng)
Reads an unsigned long (32 bits) from the current position.
bool readULong64 (unsigned long long &lng64)
Reads an unsigned long long (64 bits) from the current position.
bool readUWord (unsigned short &word)
Reads an unsigned word (16 bits) from the current position.
void reset (void)
Resets the read/write pointer to zero.
bool setLength (unsigned short newLength)
Sets the buffer length.
bool setPosition (unsigned short newPosition)
Sets the absolute position of the read/write pointer.
bool writeBlock (const void *data, const unsigned short size)
Writes a block of bytes at the current position.
bool writeSByte (const signed char byte)
Writes a signed byte at the current position.
bool writeSLong (const signed long lng)
Writes a signed long (32 bits) at the current position.
bool writeSLong64 (const signed long long lng64)
Writes a signed long long (64 bits) at the current position.
bool writeString (const char *string)
Writes a string at the current position.
bool writeString (const char *string, const unsigned short size)
Writes a string at the current position using a fixed size.
bool writeSWord (const signed short word)
Writes a signed word (16 bits) at the current position.
bool writeUByte (const unsigned char byte)
Writes an unsigned byte at the current position.
bool writeULong (const unsigned long lng)
Writes an unsigned long (32 bits) at the current position.
bool writeULong64 (const unsigned long long lng64)
Writes an unsigned long long (64 bits) at the current position.
bool writeUWord (const unsigned short word)
Writes an unsigned word (16 bits) at the current position.
virtual ~DynamicBuffer ()
Destructor.
Static Public Member Functions
static int getTypeHash (UIP_TYPE type, UIP_VERSION version)
Computes a hash value for the message type and version.
Additional Inherited Members
Static Public Attributes inherited from iris::messages::Message
static const short int MAX_MESSAGE_SIZE = 1500
Maximum message length constant.
Protected Attributes inherited from iris::messages::Message
Message * nextMessage
Optional pointer to linked message (null if none)
Protected Attributes inherited from iris::messages::DynamicBuffer
char * buffer
Pointer to buffer memory.
unsigned short length
Current size.
unsigned short maxLength
Maximum size.
bool ownAllocation
Flag indicating if buffer memory has been allocated internally or externally.
unsigned short position
Current read/write position.
Detailed Description
Represents a message in the UIP protocol.
Constructor & Destructor Documentation
UipMessage::UipMessage (UIP_ADDRESS receiver, UIP_ADDRESS sender, UIP_TYPE type, UIP_VERSION version, UIP_PAYLOAD_LEN payloadLen = 0, char * payload = NULL)
Constructor.
Parameters
receiver Receiver UIP address
sender Sender UIP address
type UIP emssage type
version UIP message version
payloadLen Payload length in bytes
payload Pointer to payload bytes
References iris::messages::DynamicBuffer::writeBlock().
Member Function Documentation
UIP_LEVEL UipMessage::getLevel (void)
Returns the message level.
Returns
UIP level (0..2)
const char * UipMessage::getMessageClassName (void) virtual
Returns the message class name.
Returns
Message class name
Reimplemented from iris::messages::Message.
char * UipMessage::getPayload (void)
Returns the payload.
Returns
Pointer to payload bytes
References iris::messages::DynamicBuffer::getBuffer().
Referenced by getVariant().
UIP_PAYLOAD_LEN UipMessage::getPayloadLen (void)
Returns the payload length.
Returns
UIP payload length in bytes
References iris::messages::DynamicBuffer::getLength().
Referenced by iris::dist500::Dist500Base::_legacyGetDeviceInfo(), iris::dist500::Dist500Base::_readAllGroupParameters(), iris::dist500::Dist500Base::activateConfiguration(), iris::dist500::FpgaController::activateMovie(), iris::dist500::CounterController::checkCategoryDefinitionAcceptance(), iris::dist500::Dist500Base::checkSupportForMessage(), iris::dist500::Dist500Base::describeParameterWithoutName(), iris::dist500::Dist500::disableExposureControl(), iris::dist500::DoorController::disableHallSensor(), iris::dist500::InstallationModeController::disableTestrideMode(), iris::dist500::Dist500::enableExposureControl(), iris::dist500::DoorController::enableHallSensor(), iris::dist500::InstallationModeController::enableTestrideMode(), iris::dist500::Dist500Base::getCaptureState(), iris::dist500::Dist500Base::getConfigurationParameter(), iris::dist500::CounterController::getCountCategories(), iris::dist500::CounterController::getCountResults(), iris::dist500::DoorController::getDoorState(), iris::dist500::Dist500::getDspRegisters(), iris::dist500::FpgaController::getFpgaRegister(), iris::dist500::CounterController::getFunctionAreaStatuses(), iris::dist500::Dist500Base::getGroupName(), iris::dist500::DoorController::getHallSensorFunction(), iris::dist500::DoorController::getHallSensorState(), iris::dist500::CounterController::getKnownCategoryTypes(), iris::dist500::Dist500Base::getParameterGroupIds(), iris::dist500::Dist500Base::getParameterName(), iris::dist500::Dist500::getSensorRevisionCode(), iris::dist500::CounterController::getSensorStatuses(), iris::dist500::Dist500::getStatusLedMode(), getVariant(), iris::dist500::Dist500Base::getWorkingMode(), iris::dist500::Dist500Base::listAllSupportedMessages(), iris::dist500::Dist500Base::lockImmanentData(), iris::dist500::FpgaController::prepareMovieUpload(), iris::dist500::FlashController::readMemory(), iris::dist500::Dist500Base::releaseDevice(), iris::dist500::CounterController::resetCounts(), iris::dist500::Dist500::resetDsp(), iris::dist500::CounterController::resetSensorStatuses(), iris::dist500::Dist500Base::restoreConfigurationFromFlash(), iris::dist500::Dist500Base::saveConfigurationToFlash(), iris::drivers::udp::UdpDriver::sendBroadcastMessage(), iris::dist500::Dist500::sendCommunicationTestMessage(), iris::drivers::icef::IcefDriver::sendMessage(), iris::drivers::udp::UdpDriver::sendMessage(), iris::dist500::Dist500Base::sendUipCommand(), iris::dist500::CounterController::setCountResults(), iris::dist500::DoorController::setDoorState(), iris::dist500::FpgaController::setFpgaRegister(), iris::dist500::DoorController::setHallSensorFunction(), iris::dist500::DoorController::setHallSensorState(), iris::dist500::Dist500::setStatusLedMode(), iris::dist500::Dist500Base::setWorkingMode(), iris::dist500::CounterController::startCounting(), iris::dist500::CounterController::stopCounting(), iris::dist500::Dist500Base::unlockImmanentData(), and iris::dist500::FpgaController::uploadMoviePicture().
UIP_ADDRESS UipMessage::getReceiver (void)
Returns the receiver.
Returns
Receiver UIP address
Referenced by printDebugInfo(), iris::dist500::Dist500Base::sendAndGetApplReply(), iris::dist500::Dist500Base::sendAndGetStackReply(), iris::drivers::udp::UdpDriver::sendBroadcastMessage(), iris::drivers::icef::IcefDriver::sendMessage(), and iris::drivers::udp::UdpDriver::sendMessage().
UIP_ADDRESS UipMessage::getSender (void)
Returns the sender.
Returns
Sender UIP address
Referenced by iris::drivers::udp::UdpDriver::handle_receive(), printDebugInfo(), iris::dist500::Dist500Base::sendAndGetApplReply(), and iris::dist500::Dist500Base::sendAndGetStackReply().
UIP_TYPE UipMessage::getType (void)
Returns message type.
Returns
UIP message type
Referenced by iris::dist500::Dist500Base::_legacyGetDeviceInfo(), iris::dist500::Dist500Base::_readAllGroupParameters(), iris::dist500::Dist500Base::activateConfiguration(), iris::dist500::FpgaController::activateMovie(), iris::dist500::Dist500Base::captureDevice(), iris::dist500::Dist500Base::checkSupportForMessage(), iris::dist500::InstallationModeController::continueInstallationMode(), iris::dist500::Dist500Base::describeParameterWithoutName(), iris::dist500::Dist500::disableExposureControl(), iris::dist500::DoorController::disableHallSensor(), iris::dist500::InstallationModeController::disableTestrideMode(), iris::dist500::Dist500Base::doSendAndGetReply(), iris::dist500::Dist500::enableExposureControl(), iris::dist500::DoorController::enableHallSensor(), iris::dist500::InstallationModeController::enableInstallationMode(), iris::dist500::InstallationModeController::enableTestrideMode(), iris::dist500::FlashController::eraseFirmware(), iris::dist500::FlashController::eraseMemory(), iris::dist500::Dist500Base::SpontaneousHandlers::forward(), iris::dist500::Dist500Base::getCaptureState(), iris::dist500::Dist500Base::getConfigurationParameter(), iris::dist500::CounterController::getCountCategories(), iris::dist500::CounterController::getCountResults(), iris::dist500::DoorController::getDoorState(), iris::dist500::Dist500::getDspRegisters(), iris::dist500::Dist500::getFirmwareFeatures(), iris::dist500::FpgaController::getFpgaRegister(), iris::dist500::CounterController::getFunctionAreaStatuses(), iris::dist500::Dist500Base::getGroupName(), iris::dist500::DoorController::getHallSensorFunction(), iris::dist500::DoorController::getHallSensorState(), iris::dist500::Dist500Base::getParameterGroupIds(), iris::dist500::Dist500Base::getParameterName(), iris::dist500::Dist500::getSensorRevisionCode(), iris::dist500::CounterController::getSensorStatuses(), iris::dist500::Dist500::getStatusLedMode(), iris::dist500::Dist500Base::getWorkingMode(), iris::drivers::udp::UdpDriver::handle_receive(), iris::dist500::Dist500Base::listAllSupportedMessages(), iris::dist500::Dist500Base::lockImmanentData(), iris::dist500::Dist500Base::pingNeighbour(), iris::dist500::Dist500Base::pingSensor(), iris::dist500::FpgaController::prepareMovieUpload(), printDebugInfo(), iris::dist500::FlashController::readFirmware(), iris::dist500::FlashController::readMemory(), iris::dist500::Dist500Base::releaseDevice(), iris::dist500::Dist500::resetCommunicationTestCounter(), iris::dist500::CounterController::resetCounts(), iris::dist500::Dist500::resetDsp(), iris::dist500::CounterController::resetSensorStatuses(), iris::dist500::Dist500Base::restoreConfigurationFromFlash(), iris::dist500::Dist500Base::saveConfigurationToFlash(), iris::drivers::udp::UdpDriver::sendBroadcastMessage(), iris::dist500::Dist500::sendCommunicationTestMessage(), iris::drivers::icef::IcefDriver::sendMessage(), iris::drivers::udp::UdpDriver::sendMessage(), iris::dist500::Dist500Base::sendUipCommand(), iris::dist500::CounterController::setCountResults(), iris::dist500::DoorController::setDoorState(), iris::dist500::FpgaController::setFpgaRegister(), iris::dist500::DoorController::setHallSensorFunction(), iris::dist500::DoorController::setHallSensorState(), iris::dist500::Dist500::setStatusLedMode(), iris::dist500::Dist500Base::setWorkingMode(), iris::dist500::CounterController::startCounting(), iris::dist500::CounterController::stopCounting(), iris::dist500::FlashController::switchFirmware(), iris::dist500::Dist500Base::unlockImmanentData(), iris::dist500::FpgaController::uploadMoviePicture(), iris::dist500::FlashController::writeFirmware(), and iris::dist500::FlashController::writeMemory().
int UipMessage::getTypeHash (void) virtual
Returns a hash value for the message type.
Returns
Hash value
Reimplemented from iris::messages::Message.
Referenced by iris::dist500::Dist500Base::automaticRetriesSupported().
int UipMessage::getTypeHash (UIP_TYPE type, UIP_VERSION version) static
Computes a hash value for the message type and version.
Returns
Hash value
int UipMessage::getVariant (void) virtual
Returns the message variant.
Returns
Variant
Reimplemented from iris::messages::Message.
References getPayload(), and getPayloadLen().
UIP_VERSION UipMessage::getVersion (void)
Returns the message version.
Returns
UIP message version
Referenced by iris::dist500::Dist500Base::_legacyGetDeviceInfo(), iris::dist500::Dist500Base::_readAllGroupParameters(), iris::dist500::Dist500Base::activateConfiguration(), iris::dist500::FpgaController::activateMovie(), iris::dist500::Dist500Base::captureDevice(), iris::dist500::Dist500Base::checkSupportForMessage(), iris::dist500::InstallationModeController::continueInstallationMode(), iris::dist500::Dist500Base::describeParameterWithoutName(), iris::dist500::Dist500::disableExposureControl(), iris::dist500::DoorController::disableHallSensor(), iris::dist500::InstallationModeController::disableTestrideMode(), iris::dist500::Dist500Base::doSendAndGetReply(), iris::dist500::Dist500::enableExposureControl(), iris::dist500::DoorController::enableHallSensor(), iris::dist500::InstallationModeController::enableInstallationMode(), iris::dist500::InstallationModeController::enableTestrideMode(), iris::dist500::FlashController::eraseFirmware(), iris::dist500::FlashController::eraseMemory(), iris::dist500::Dist500Base::SpontaneousHandlers::forward(), iris::dist500::Dist500Base::getCaptureState(), iris::dist500::Dist500Base::getConfigurationParameter(), iris::dist500::CounterController::getCountCategories(), iris::dist500::CounterController::getCountResults(), iris::dist500::DoorController::getDoorState(), iris::dist500::Dist500::getDspRegisters(), iris::dist500::Dist500::getFirmwareFeatures(), iris::dist500::FpgaController::getFpgaRegister(), iris::dist500::CounterController::getFunctionAreaStatuses(), iris::dist500::Dist500Base::getGroupName(), iris::dist500::DoorController::getHallSensorFunction(), iris::dist500::DoorController::getHallSensorState(), iris::dist500::Dist500Base::getParameterGroupIds(), iris::dist500::Dist500Base::getParameterName(), iris::dist500::Dist500::getSensorRevisionCode(), iris::dist500::CounterController::getSensorStatuses(), iris::dist500::Dist500::getStatusLedMode(), iris::dist500::Dist500Base::getWorkingMode(), iris::drivers::udp::UdpDriver::handle_receive(), iris::dist500::Dist500Base::listAllSupportedMessages(), iris::dist500::Dist500Base::lockImmanentData(), iris::dist500::Dist500Base::pingNeighbour(), iris::dist500::Dist500Base::pingSensor(), iris::dist500::FpgaController::prepareMovieUpload(), printDebugInfo(), iris::dist500::FlashController::readFirmware(), iris::dist500::FlashController::readMemory(), iris::dist500::Dist500Base::releaseDevice(), iris::dist500::Dist500::resetCommunicationTestCounter(), iris::dist500::CounterController::resetCounts(), iris::dist500::Dist500::resetDsp(), iris::dist500::CounterController::resetSensorStatuses(), iris::dist500::Dist500Base::restoreConfigurationFromFlash(), iris::dist500::Dist500Base::saveConfigurationToFlash(), iris::drivers::udp::UdpDriver::sendBroadcastMessage(), iris::dist500::Dist500::sendCommunicationTestMessage(), iris::drivers::icef::IcefDriver::sendMessage(), iris::drivers::udp::UdpDriver::sendMessage(), iris::dist500::Dist500Base::sendUipCommand(), iris::dist500::CounterController::setCountResults(), iris::dist500::DoorController::setDoorState(), iris::dist500::FpgaController::setFpgaRegister(), iris::dist500::DoorController::setHallSensorFunction(), iris::dist500::DoorController::setHallSensorState(), iris::dist500::Dist500::setStatusLedMode(), iris::dist500::Dist500Base::setWorkingMode(), iris::dist500::CounterController::startCounting(), iris::dist500::CounterController::stopCounting(), iris::dist500::FlashController::switchFirmware(), iris::dist500::Dist500Base::unlockImmanentData(), iris::dist500::FpgaController::uploadMoviePicture(), iris::dist500::FlashController::writeFirmware(), and iris::dist500::FlashController::writeMemory().
void UipMessage::printDebugInfo (std::ostream & ostream) virtual
Prints a debug string for the message to an output stream.
Parameters
ostream Output stream to receive the hex dump
Reimplemented from iris::messages::DynamicBuffer.
References getReceiver(), getSender(), getType(), and getVersion().
void UipMessage::setLevel (UIP_LEVEL level)
Sets the message level.
Parameters
level UIP level (0..2)
Referenced by iris::drivers::udp::UdpDriver::handle_receive(), and iris::drivers::icef::IcefDriver::sendMessage().
The documentation for this class was generated from the following files:
SensorAPI/headers/iris/uip/UipMessage.h
SensorAPI/implementation/iris/uip/UipMessage.cpp
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !