IRMA MATRIX SDK: iris::dist500 Namespace Reference
iris::dist500 Namespace Reference
Namespace for DIST500 related stuff (eg communication, service tasks, signal recording)
Classes
class ConfigurationInterceptorCallbackAdapter
Acts as a ConfigurationInterceptor adapter class which delegates the reviewConfiguration() event to an external callback function.
class ContainerDecoderCloser
class CounterController
This class represents the counting modules' functionality within the DIST500 sensor.
class CountResult
Encapsulates a count result.
class CountResultSink
Sink for CountResult objects.
class CountResultSinkCallbackAdapter
Acts as a CountResultSink adapter class which delegates the processNewCountResult() event to an external callback function.
class CountResultSource
Source for CountResult objects.
class DebugData
Encapsulates debug data.
class DebugDataSink
Sink for DebugData objects.
class DebugDataSinkCallbackAdapter
Acts as a DebugDataSink adapter class which delegates the processNewDebugData() event to an external callback function.
class DebugDataSource
Source for DebugData objects.
class Dist500
Represents a DIST500 sensor.
class Dist500Base
Implements basic sensor functions like communication, configuration and UIP retry and timeout control.
class DoorController
This class represents the door functionality within the DIST500 sensor.
class DoorState
Encapsulates a door state as a class.
class DoorStateSink
Sink for DoorState objects.
class DoorStateSinkCallbackAdapter
Acts as a DoorStateSink adapter class which delegates the processNewDoorState() event to an external callback function.
class DoorStateSource
Source for DoorState objects.
class FirmwareController
Implements DIST500 functions related to firmware and configuration data.
struct FlagsAndValue
Typedef for a decoded (into flags and value) pixel.
class FlashController
Implements Flash access functions provided by the DIST500 sensor There are two groups of methods that are used by a firmware release.
class FpgaController
Implements FPGA related functions within the DIST500 firmware.
class HallSensorState
Encapsulates a door state.
class HallSensorStateSink
Sink for HallSensorState objects.
class HallSensorStateSinkCallbackAdapter
Acts as a HallSensorStateSink adapter class which delegates the processNewHallSensorState() event to an external callback function.
class HallSensorStateSource
Source for HallSensorState objects.
class InstallationModeController
Represents the DIST500's installation mode facility, which is used for live picture streaming from a sensor.
class LegacyConfigurationInterceptor
class LegacyConfigurationInterceptorCallbackAdapter
Acts as a ConfigurationInterceptor adapter class which delegates the reviewConfiguration() event to an external callback function.
class LoggerController
The LoggerController class provided access to the sensor's logger and operation time counter.
struct LogMessage
union Pic
Typedef for a full DIST500 picture, addressable in an arbitrary way.
class Picture
This class represents a full DIST500 picture along with some metadata (eg picture number and timestamp)
class PictureBoundData
Encapsulates a set of data which is generated by the sensor at a certain point in time.
class PictureFilter
Interface class (ie abstract base class) defining a "picture filter".
class PictureSink
Sink for Picture objects.
class PictureSinkCallbackAdapter
Acts as a PictureSink adapter class which delegates the processNewPicture() event to an external callback function.
class PictureSource
Source for Picture objects.
union Pixel
Typedef for a pixel, either as "raw" 16 bit number or in decoded (flags plus value) form.
union Pixels1000
Typedef for a full DIST500 picture (distance plus amplitude), treated as one big picture.
union Pixels500
Typedef for a DIST500 subpicture (eg distance or amplitude)
class RegisterValues
Encapsulates a set of FPGA register values.
class RegisterValuesSink
Sink for RegisterValues objects.
class RegisterValuesSinkCallbackAdapter
Acts as a RegisterValuesSink adapter class which delegates the processNewRegisterValues() event to an external callback function.
class RegisterValuesSource
Source for RegisterValues objects.
class SensorGroup
Represents a group of DIST500 sensors (eg a function area).
class SensorInfo
Cache object for sensor meta information.
class SensorInfoProvider
Abstract class defining an interface for classes that can provide sensor metadata (such as physical sensors or UFF files)
class SensorUpdater
The SensorUpdater class.
class Sink
Template class defining a data "sink".
class Source
Template class defining a data source.
struct SubPics
Typedef for a full DIST500 picture (distance plus amplitude), adressable as two subpictures.
class UipGetDeviceInformationRequestMessage
class UipGetDeviceInformationResponseMessage
struct UpdateHistoryEntry
class WorkingModeStatus
Encapsulates a working mode.
class WorkingModeStatusSink
Sink for WorkingModeStatus objects.
class WorkingModeStatusSinkCallbackAdapter
Acts as a WorkingModeStatusSink adapter class which delegates the processNewWorkingModeStatus() event to an external callback function.
class WorkingModeStatusSource
Source for WorkingModeStatus objects.
Typedefs
typedef void(* CALLBACK_UPDATEPROGRESSMESSAGE) (uint8_t step, float stepProgress)
typedef void(* CALLBACK_UPDATESTATUSMESSAGE) (const std::string &str)
typedef void(* CONTAINER_UPDATE_CALLBACK) (void *userData, iris::dist500::Dist500 *sensor, CONTAINER_UPDATE_STATE updateState, unsigned int containerStep, unsigned int containerTotalSteps, double stepPercentage, double totalPercentage)
Callback for firmware updates with container file.
typedef std::list< Dist500 * > Dist500List
typedef std::map< uint16_t, LogMessage > LogMap
typedef std::map< std::string, Dist500 * > lookupSerialToDist500InstanceType
typedef void(* UPDATE_CALLBACK) (void *userData, unsigned int step, unsigned int totalSteps, double stepPercentage, double totalPercentage)
Callback for firmware updates.
typedef std::map< uint16_t, UpdateHistoryEntry > UpdateHistoryMap
Enumerations
enum { SaturationFlag = 0x4 }
enum CONTAINER_UPDATE_STATE {
UNDEFINED_STATE = 0, PERFORM_APPLICATION_UPDATE, PERFORM_APPLICATION_VERIFY, PERFORM_COMMUNICATION_UPDATE,
PERFORM_COMMUNICATION_VERIFY, PERFORM_FIRST_FPGA_UPDATE, PERFORM_FIRST_FPGA_VERIFY, PERFORM_SECOND_FPGA_UPDATE,
PERFORM_SECOND_FPGA_VERIFY, PERFORM_SENSOR_RESTART, PERFORM_READ_CONFIGURATION, PERFORM_WRITE_CONFIGURATION,
PERFORM_SAVE_CONFIGURATION, PERFORM_CHANGE_CONFIGURATION
}
Container update state.
enum SENSOR_RESULT {
OPERATION_PASSED = 0, OPERATION_FAILED, OPERATION_WRONG_REPLY, OPERATION_NO_REPLY,
OPERATION_INCOMPLETE_REPLY, OPERATION_WRONG_SUBSEQUENT_REPLY, OPERATION_ERRONEOUS_SUBSEQUENT_REPLY, OPERATION_RESERVED_FOR_IRIS,
OPERATION_INCONSISTENT_RESPONSE_PAYLOAD
}
Sensor operation result codes.
enum UpdaterState {
UPDATER_STATE_START, UPDATER_STATE_CONNECTIVITY_CHECK, UPDATER_STATE_CLEANING_CHECK, UPDATER_STATE_CLEANING_FINALIZE,
UPDATER_STATE_CLEANING_RESTARTABLE, UPDATER_STATE_REQUESTING_INSTALL, UPDATER_STATE_RUNNING, UPDATER_STATE_RUNNING_FINALIZABLE,
UPDATER_STATE_RUNNING_RESTARTABLE, UPDATER_STATE_RUNNING_RESTART_ERROR, UPDATER_STATE_FINALIZING_ERROR, UPDATER_STATE_FINALIZED,
UPDATER_STATE_FAILED
}
The UpdaterState enum Additionally, there is a waiting for restart boolean.
Functions
std::string ipAddressStringFromFourChars (iris::uip::uchar *fourChars)
unsigned int updateSensorConnectionsViaBroadcast ()
fillLookup Uses sensorList to fill the lookupSerialToSensorInstance container.
Variables
std::set< std::string > allCanSerialsInUpdate
std::set< std::string > allIcefSerialsInUpdate
std::set< std::string > allSerialsInUpdate
std::set< std::string > allUdpSerialsInUpdate
const unsigned int APPL_LEVEL_PORT = 0x888a
const unsigned int CONFIG_STEPS = 5
CONFIG_STEPS.
bool enableSensorInfoLegacyFallback = false
const unsigned int GROUP_CONFIG_STEP = 1
GROUP_CONFIG_STEP.
lookupSerialToDist500InstanceType lookupSerialToSensorInstance
const unsigned int MAX_DEFAULT_IO_WAIT = 1000
const unsigned int MAX_FINALIZE_WAIT = 20000
const unsigned int MAX_FLASH_ERASE_IO_WAIT = 35000
const unsigned int MAX_FLASH_WRITE_IO_WAIT = 1000
const unsigned int MAX_FPGA_RESET_IO_WAIT = 1000
const unsigned int MAX_PICTURE_IO_WAIT = 2000
const unsigned int MAX_SCAN_IO_WAIT = 500
const unsigned int MAX_SEND_ATTEMPTS = 3
const unsigned int MAX_SEND_IO_WAIT = 500
const unsigned int MAX_UPLOAD_IO_WAIT = 900000
const unsigned int RESTART_STEP = 1
RESTART_STEPS.
iris::SensorShepherd sensorShepherd
const unsigned int SERVICE_LEVEL_PORT = 0x8889
const unsigned int STACK_LEVEL_PORT = 0x8888
Detailed Description
Namespace for DIST500 related stuff (eg communication, service tasks, signal recording)
Typedef Documentation
typedef void(* iris::dist500::CONTAINER_UPDATE_CALLBACK) (void *userData, iris::dist500::Dist500 *sensor, CONTAINER_UPDATE_STATE updateState, unsigned int containerStep, unsigned int containerTotalSteps, double stepPercentage, double totalPercentage)
Callback for firmware updates with container file.
Parameters
userData User-defined additional parameter
sensor
updateState
containerStep Current container update step
containerTotalSteps Total container update steps
stepPercentage Progress within current step
totalPercentage Total progress
typedef void(* iris::dist500::UPDATE_CALLBACK) (void *userData, unsigned int step, unsigned int totalSteps, double stepPercentage, double totalPercentage)
Callback for firmware updates.
Parameters
userData User-defined additional parameter
step Current step
totalSteps Total number of steps
stepPercentage Progress within current step
totalPercentage Total progress
Enumeration Type Documentation
enum iris::dist500::SENSOR_RESULT
Sensor operation result codes.
Enumerator
OPERATION_PASSED
Everything OK.
OPERATION_FAILED
Generail failure.
OPERATION_WRONG_REPLY
Unexpected UIP reply.
OPERATION_NO_REPLY
No UIP reply.
OPERATION_INCOMPLETE_REPLY
Incomplete UIP reply.
OPERATION_WRONG_SUBSEQUENT_REPLY
Unexpected subsequent UIP reply.
OPERATION_ERRONEOUS_SUBSEQUENT_REPLY
Erroneous subsequent UIP reply.
OPERATION_RESERVED_FOR_IRIS
Function/method is reserved for iris-internal use.
Function Documentation
unsigned int iris::dist500::updateSensorConnectionsViaBroadcast ()
fillLookup Uses sensorList to fill the lookupSerialToSensorInstance container.
Queries config parameter "serial" from each sensor
Parameters
sensorList Updates instances in lookupSerialToSensorInstance by using a broadcast. Can be used with all protocols, but is only useful for protocols where addresses may change, such as with DHCP. Call when you are sure, the devices have all rebooted and are responsive.
Returns
Returns number of update sensors that respnded. Serves as indicator for sensors finishing booting and address assignments.
References iris::drivers::Driver::disableAddress(), iris::drivers::Sensor::dispatchCallback, iris::drivers::Sensor::dispatchCallbackUserData, iris::drivers::Driver::enableAddress(), iris::drivers::Sensor::getAddr(), iris::dist500::Dist500Base::getConfigurationParameter(), iris::drivers::DriverManager::getDriverFor(), iris::drivers::DriverManager::getInstance(), iris::dist500::Dist500Base::getSensor(), iris::drivers::DriverManager::getSensorFor(), iris::drivers::Sensor::getUipAddress(), iris::drivers::Driver::getUrlPrefix(), iris::drivers::DriverManager::makeUrl(), OPERATION_PASSED, iris::drivers::Driver::performAddressScan(), iris::drivers::Sensor::setConnectionAddress(), iris::drivers::Sensor::setDispatchCallback(), iris::dist500::Dist500Base::setUipAddress(), iris::drivers::DriverManager::splitAddress(), and iris::drivers::DriverManager::splitUrl().
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !