IRMA MATRIX SDK: iris::messages Namespace Reference
iris::messages Namespace Reference
Namespace containing basic message handling classes.
Classes
class DynamicBuffer
Encapsulates a binary read/write buffer that can grow dynamically.
class Message
Base type for messages providing basic functionality which can be extended by protocol-specific child classes.
Functions
std::ostream & operator<< (std::ostream &ostream, Message *message)
Prints debug information for a Message into an output stream.
std::ostream & operator<< (std::ostream &ostream, DynamicBuffer *message)
Prints debug information for a DynamicBuffer into an output stream.
Detailed Description
Namespace containing basic message handling classes.
Function Documentation
std::ostream & iris::messages::operator<< (std::ostream & ostream, Message * message)
Prints debug information for a Message into an output stream.
Parameters
ostream Output stream
message Message pointer
Returns
The original ostream reference
References iris::messages::Message::getMessageClassName(), and iris::messages::DynamicBuffer::printDebugInfo().
std::ostream & iris::messages::operator<< (std::ostream & ostream, DynamicBuffer * message)
Prints debug information for a DynamicBuffer into an output stream.
Parameters
ostream Output stream
message DynamicBuffer pointer
Returns
The original ostream reference
References iris::messages::DynamicBuffer::printDebugInfo().
IRMA MATRIX SDK Documentation
Version 1.3.6
www.irisgmbh.de | mail@irisgmbh.de
Please note: this material is confidential !